### ISSUE TITLE
💡 Feature Request - Swap Extension suggestion

### ISSUE THREAD

**Issue by Manbearpiet** [Azure/ALZ-Bicep#128]
Maybe change the advisory at this line

https://github.com/Azure/ALZ-Bicep/blob/a6db5effd9c08c721e877c1a3988c37c9a580a7a/docs/wiki/Contributing.md?plain=1#L56

To the built-in option:
Inside User Settings:
`Editor › Bracket Pair Colorization: Enabled`
or
Inside User Settings (JSON):
`"editor.bracketPairColorization.enabled": true`

This prevents another extension to be installed, native stuff tends to work usually 🤓

Also maybe looke at ms-azure-devops.azure-pipelines as an advisory :) ?

**Comment by jtracey93** [comment]
Thanks @Manbearpiet this is a great suggestion. Forgot to update this from when we originally created the contribution guide.

We'll get this updated 👍

**Comment by Manbearpiet** [comment]
Hehe I'll put in some more PR's, kinda new to the whole GitHub contribution stuff hehe.

**Comment by jtracey93** [comment]
Thanks. If you want to submit a PR for this, please feel free to update the doc in the `docs/wiki` folder and we will review.

Let me know, if not we will put on our backlog for sorting 👍

**Comment by Manbearpiet** [comment]
Added the PR, I hope this is fine like this @jtracey93 😁

**Comment by jtracey93** [comment]
Awesome thanks @Manbearpiet reviewed your PR and looks great, just waiting for checks to complete before merging it
