### ISSUE TITLE
💡 Feature Request - Enable Azure Virtual WAN scenario in the Hub Networking module

### ISSUE THREAD

**Issue by pazdedav** [Azure/ALZ-Bicep#133]
## Describe the solution you'd like

The current release (`0.1.0`) only supports the [Traditional Networking](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/traditional-azure-networking-topology) ALZ topology.

It would be great to have a feature parity with the [Portal-based experience](https://github.com/Azure/Enterprise-Scale#deploying-enterprise-scale-architecture-in-your-own-environment) and enable the second networking model based on [Azure Virtual WAN](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/virtual-wan-network-topology).

**Comment by jtracey93** [comment]
Thanks @pazdedav for raising this. We actually already have this on our backlog, to get to full parity, and is planned in for our March sprint currently.

Assigning to @faister who has this item assigned to him already.

Link to internal tracking item: https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_workitems/edit/73009
