### ISSUE TITLE
Private Module Registry

### ISSUE THREAD

**Issue by furrm** [Azure/ALZ-Bicep#138]
<h2 id=questionfeedback>Question/Feedback </h2>
<p>First of all, it's great to see the work you have done in the area of ALZ.  It's an area we are actively working on at the organisation I work for. </p>
<p>I'm interested in your thoughts around the development lifecycle and versioning strategy for BICEP module engineering. </p>
<p>We have been following <a href="https://github.com/Azure/bicep/discussions/5089">publish bicep modules to ACR with azure devops</a> with interest and have been prototyping using <a href="https://github.com/dotnet/Nerdbank.GitVersioning">Nerdbank</a> as mentioned in the thread.  Will you be aligning to the outcomes from the work in relation to the MSFT public repo? </p>
<p>I guess it would also help to understand the ACR tagging strategy too - module development versus module release. </p>

**Comment by jtracey93** [comment]
Hey @furrm, Thanks for raising this question and for your kind words RE ALZ, it means a lot!

This is something we are definitely considering and reviewing internally in the team and with the Bicep engineering team. 

But as you rightly mention the upcoming public Bicep Registry work that the Bicep engineering team are working on and discussing here https://github.com/Azure/bicep/issues/5138 is something we are actively participating in and will align to to ensure there is no conflicts or different approaches, unless absolutely required. 

Some other similar and interesting project we are also collaborating on with Bicep also use the Nerdbank versioning approach as you can see here https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Network/azureFirewalls/version.json & here https://github.com/Azure/ResourceModules/blob/main/.github/actions/templates/publishModule/action.yml

### Summary

Yes will be aligning to what is done upstream on the public Bicep registry, when it lands, and will link to and/or create documentation specific to ALZ-Bicep as required to help customers on their journey 👍

> We have no ETAs yet and are dependant on the Bicep work upstream - but this is something we are keeping a close eye on 👍

**Comment by jtracey93** [comment]
Ado sync
