### ISSUE TITLE
❓👂 Question/Feedback - principles behind policy deployment

### ISSUE THREAD

**Issue by azMantas** [Azure/ALZ-Bicep#144]
## Question/Feedback

would you please to explain the logic behind policy deployment/assignment. 
this issue is inspired [by twitter post ](https://twitter.com/Jack_Ref/status/1491001732201316353)

## Possible Answers/Solutions?
- big picture of policy deployment principles
- elaborate on the `deployment telemetry` 
- what is the meaning of `_policyDefinitionsBicepInput.txt` file under `/modules/policy/definitions/lib`

**Comment by jtracey93** [comment]
Thanks for raising this and for the thread on twitter. 

I'll take this on and record a video soon for this 👍

**Comment by azMantas** [comment]
Most of the policy definitions have `DINE` policy effect, while there is an alias for `modify`. Is there any reason why there is no 'modify' policy effect in this project?

**Comment by jtracey93** [comment]
Hey @azMantas,

For the Enable DDoS policy that is a `modify` but we use `DINE` mainly as we are mainly looking for things that have been missed that are separate resources, rather than individual properties of resources (like we for the Enable DDoS policy), in that PUT/Deployment.

Hope that makes sense👍

**Comment by azMantas** [comment]
yes, it does. Thanks for fast respond

**Comment by dgitw** [comment]
@jtracey93 Looking forward to video.

Noting that policyAssignmentManagementGroup.bicep only allows the assignment of one policy, can you elaborate on the scenario where you have multiple additional policy assignments. What is the best approach here to adding additional policies as opposed to deploying the defaults:

1. Create another deployment module similar to the alzDefaultPolicyAssignments.bicep
2. Use the policyAssignmentManagementGroup.bicep module with a deployment pipeline deploying the additional policies one by one within the pipeline
3. Something else
