### ISSUE TITLE
👂 Feedback - Use Git sparse-checkout to copy only IaC

### ISSUE THREAD

**Issue by FallenHoot** [Azure/ALZ-Bicep#146]
## Question/Feedback

No need to copy full repo, you can simply copy infra-as-code/bicep folder. PR will be created to add Deploying ALZ-Bicep Pre Requisites

## Possible Answers/Solutions?

#Copy only IaC
#Requires Git Version 2.25 or newer `git --version`
git clone --no-checkout https://github.com/Azure/ALZ-Bicep
cd ALZ-Bicep
git sparse-checkout init --cone
git sparse-checkout set infra-as-code/bicep

**Comment by jtracey93** [comment]
Hey @FallenHoot thanks for raising this and it's a great idea for the future maybe. 

But as this is an experimental feature in git and is likely to change then we won't add this to our guidance. 

Also we hopefully plan to make these modules available from the public bicep registry as mentioned in #138. 

So I'll close this one off for now.
