### ISSUE TITLE
💡 Feature Request - Provide ability to define and deploy custom Management group hierarchy

### ISSUE THREAD

**Issue by rjygraham** [Azure/ALZ-Bicep#160]
Provide flexibility in the Management group hierarchy by defining structure in a parameter file. This would potentially address this issue https://github.com/Azure/ALZ-Bicep/issues/158 in providing more flexibility in how/which Management groups get deployed.

Additionally, it may be beneficial to include Subscription to Management Group assignments in this single deployment as well.

**Comment by jtracey93** [comment]
Going to track this as one issue under #158
