### ISSUE TITLE
💡 Feature Request - Support tagging on resource groups and management object like log analytics workspaces and automation account.

### ISSUE THREAD

**Issue by KiZach** [Azure/ALZ-Bicep#170]
## Describe the solution you'd like

Support for tagging on the resource group creation process and on central logging deployment for components like log analytics workspace and automation account.

## Describe alternatives you've considered

Can be done by an after deployment script, or tags maintain script, but not a great solution.

## Additional context

Add any other context or screenshots about the feature request here. 📷

**Comment by jtracey93** [comment]
Hey @KiZach,

Thanks for raising this and you are correct we should do this. We are tracking an internal feature to update these sorts of "hygiene" elements across the modules.

I'll add this to that for tracking 👍

**Comment by KiZach** [comment]
I have made a PR for the RG and logging module. https://github.com/Azure/ALZ-Bicep/pull/171

**Comment by jtracey93** [comment]
Awesome @KiZach, have reviewed and made a suggestion 👍
