### ISSUE TITLE
🪲Az CLI Login failed. Please check the credentials and make sure az is installed on the runner.

### ISSUE THREAD

**Issue by autocloudarc** [Azure/ALZ-Bicep#176]
## Describe the bug
Unable to run the GitHub Actions workflow

## To Reproduce

1. Cloned repository
2. Created the workflow in GitHub 
4. Ran the workflow as a workflow_dispatch trigger

A clear and concise description of what you expected to happen without this bug 🙂

## Screenshots 📷

![image](https://user-images.githubusercontent.com/15109536/157351260-45add7c9-bd7e-42d5-aea2-9dfbe3452240.png)

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Correlation ID

A correlation ID really helps us investigate your issue further. Please provide one if possible. Details on how to find a correlation ID can be found here: [Correlation ID and support](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#correlation-id-and-support)

## Additional context

GitHub Secret:

AZURE_CREDENTIALS
{
  "appId": "redacted",
  "displayName": "redacted",
  "password": "redactd",
  "tenant": "redacted"
}

Relevant workflow file content

name: ALZ GitHub Actions deployment pipeline

on: [workflow_dispatch]

env:
  ManagementGroupPrefix: "alz07"
  TopLevelManagementGroupDisplayName: "Azure Landing Zones"
  Location: "centralus"
  LoggingSubId: redacted
  LoggingResourceGroupName: "alz-logging-rgp-01"
  HubNetworkSubId: redacted
  HubNetworkResourceGroupName: "alz-network-hub-rgp-01"
  RoleAssignmentManagementGroupId: "alz07-platform"
  SpokeNetworkSubId: redacted
  SpokeNetworkResourceGroupName: "spoke-networking-rgp-01"
  runNumber: ${{ github.run_number }}

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

**Comment by jtracey93** [comment]
Hey @autocloudarc,

Looks like your secret content isn't correct. 

Checkout this guidance and example for what it should look like https://github.com/marketplace/actions/azure-login#configure-a-service-principal-with-a-secret

Let us know

Thanks

Jack

**Comment by autocloudarc** [comment]
Hi @jtracey93. Thank you! Yes, that was it. Got past the authentication issue now.
