### ISSUE TITLE
Not having a DDoS Protection Standard plan is causing deployment issues

### ISSUE THREAD

**Issue by davidjones-pc** [Azure/ALZ-Bicep#181]
## Describe the bug

If you do not have a Ddos protection plan setup in Azure and set the parDdosProtectionPlanId parameter in alzDefaultPolicyAssignments.bicap to an empty string you still have the _Virtual networks should be protected by Azure DDoS Protection Standard_ policy assignment set and enabled. This causes the following error when trying to re-deploy the hub network template:

`ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"LinkedInvalidPropertyId\",\r\n    \"message\": \"Property id '' at path 'properties.ddosProtectionPlan.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.\"\r\n  }\r\n}"}]}}`

You get this error when trying to deploy a spoke:

`ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"LinkedInvalidPropertyId\\\",\\r\\n    \\\"message\\\": \\\"Property id '' at path 'properties.ddosProtectionPlan.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}`

## To Reproduce

Steps to reproduce the behaviour:

1. Set the parDdosEnabled parameter in hubNetworking.bicep to false (this may not be relevant to the issue but I have it set this way)
2. Set the parDdosProtectionPlanId parameter in alzDefaultPolicyAssignments.bicep to an empty string.
3. Deploy the policy assignment template.
4. (re)deploy the hubNetworking template and/or (re)deploy the spokeNetworking template.

## Expected behaviour

With parDdosEnabled set to false, and the parDdosProtectionPlanId set to an empty string I would not expect the policy to be assigned. 

## Correlation ID
Hub deployment: 4f412669-a92c-413b-b017-adcbb3f8ab68
Spoke deployment: 873ccc68-d142-4b63-87bd-5fca9f01291c

## Additional context

Setting the _Virtual networks should be protected by Azure DDoS Protection Standard_ policy assignment enforcement to disabled stops the error from happening on both the hub and spoke template deployments.

**Comment by jtracey93** [comment]
Thanks @davidjones-pc good catch, let me investigate a potential fix. 👍

**Comment by jtracey93** [comment]
@davidjones-pc which of the options below would you prefer:

1. DDoS policy not assigned at all
2. DDoS policy assigned but `enforcementMode` set to `DoNotEnorce` (aka Disabled) 

My preference is 2 as at least you can still see all the VNETs you haven't got it enabled on, another handy compliance report?

Thoughts?

**Comment by jtracey93** [comment]
Update. We met as a maintainer team and decided on option 1

**Comment by davidjones-pc** [comment]
I was leaning towards option 1 as I felt option 2 could result in some noise in your non-compliance stats. However, having had a quick look in Azure I can see that I could use the exemption feature to remove the "noise". I'm happy with option 1. 

Thank you @jtracey93 for the quick turn around.

**Comment by jtracey93** [comment]
@davidjones-pc no worries. We thought the same 👍

PR inbound and should be available tomorrow
