### ISSUE TITLE
🪲 Bug Report - Example ACR publish scripts don't publish policy modules

### ISSUE THREAD

**Issue by frasermolyneux** [Azure/ALZ-Bicep#186]
## Describe the bug

When using either of the included scripts: 

- https://github.com/Azure/ALZ-Bicep/blob/main/docs/scripts/createRGandcallBicep.ps1
- https://github.com/Azure/ALZ-Bicep/blob/main/docs/scripts/createRGandcallBicep.sh

The modules that sit in https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy are not published e.g:

* modules\policy\assignments\policyAssignmentManagementGroup.bicep
* modules\policy\definitions\custom-policy-definitions.bicep

This is due to the path being used of **infra-as-code/bicep/modules/**/**.bicep**

## To Reproduce

Steps to reproduce the behaviour:

1. Execute either script
2. Validate that the policy modules have not been published

## Expected behaviour

I would have expected those modules to be published so that they can be referenced as remote modules.

## Screenshots 📷

Published Modules: 
![image](https://user-images.githubusercontent.com/34033625/158053183-3d0f12ea-e54b-4fc1-8cd3-5e34f4194ac0.png)

## Correlation ID

N/A

## Additional context

I will raise another issue (question) to validate some of how I am ingesting/implementing the outputs of this repository as it is not especially clear from some of the documentation on what the best practice would be.

**Comment by jtracey93** [comment]
Thanks for raising this @frasermolyneux, we will investigate this shortly

**Comment by jfaurskov** [comment]
Thank you for your input @frasermolyneux. If you would like to contribute directly please feel free to create a pull request based on the work you have already done and we can get this sorted.
