### ISSUE TITLE
💡 Multiple Feature Requests - Orchestration, Looping, Modularity Questions

### ISSUE THREAD

**Issue by sandeepkumarv232** [Azure/ALZ-Bicep#193]
**Please clarify or provide pointers for the below issues / feature requests:**

1. Presently there is no single bicep file which can be called upon to deploy full Infra. Am looking at something like a main.bicep file that would call the child modules from their respective trees. It will be consumed with / without looping in the main.bicep file as per requirement. It will also have single mainparameter.json file.
2. If these were modularized, they could have been consumed to create one or multiple resources as per need. Looping is missing for some modules.
3. Also the modular approach missing and creation of different types of resources happening in a single massive bicep file like hubNetworking.bicep.
4. Scenario such as deploying multiple resource at parent and then deploy corresponding child resources within those deployed parent resources. It was interesting to see how you would have approached it. e.g. Create 2 Log Analytics Workspace with 1st LA workspace getting 3 different solutions and the 2nd LA workspace deployed with some other solutions.

**Comment by jtracey93** [comment]
Hey @sandeepkumarv232,

Thanks for raising these issues/feature requests 👍 I'll answer them below with numbers corresponding to the questions above.

### Answers/Responses

1. This is correct for today, but we **do** plan to release one when supported in ARM/Bicep.
    - We actually did start creating one [here](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/unstable/orchestration/hubSpoke) and planned to have it available for our public preview launch, but we unfortunately uncovered some bugs in ARM as explained on the page (linked before)
2. The modules we provided can be looped as required as this is a feature supported by Bicep as documented [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/modules) 
3. We have tried to avoid creating modules for individual resources unless absolutely required for things like scope changes within a single `.bicep` file etc. or where we can keep the code DRY, like for public IPs.
    - The `hubNetworking.bicep` module deploys an entire hub VNET and common associated networking services into it like, Azure Firewall, Bastion, DNS Zones etc. which is as per the ALZ conceptual architecture and the goal of this repo.
    - Most services and settings can be disabled/tweaked by using the various input parameters that are exposed via the module to make it flexible, where appropriate.
    - But the module can be used to deploy into multiple regions if necessary to provide a consistent pattern for the hub network etc. in each region.
4. I'm sorry but not understanding the question or feedback point here - could you please clarify further?

### Summary

I hope the above answers help and if I have misunderstood anything please feel free to correct me so I can help/assist further 👍
