### ISSUE TITLE
🪲 Bug Report - hubNetworking - Inconsistent cases for parDDoSEnabled / parDDoSPlanName in bicep vs doc & parameter.sample.json

### ISSUE THREAD

**Issue by cbezenco** [Azure/ALZ-Bicep#195]
## Describe the bug

hubNetworking - Inconsistent cases for parDDoSEnabled / parDDoSPlanName in bicep vs documentation and parameter.sample.json 

Facing following error when following documentation applying parameter.example.json + parDdosEnabled

New-AzResourceGroupDeployment: 9:55:13 PM - Error: Code=CaseSensitiveDeploymentParameterNamesFound; Message=The deployment parameters are using case sensitive names. The error parameter name(s): parDDoSEnabled,parDDoSPlanName. Please see https://aka.ms/arm-keyvault for usage details.

Steps to reproduce the behaviour:

Follow documentation and overwrite parDdosEnabled parameter (following case in hubNetwork doc page)

New-AzResourceGroup `
  -Name $varConnectionRG `
  -Location $varDeplRegion

[bool] $varDdosEnabled = 0

New-AzResourceGroupDeployment `
-TemplateFile infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep `
-TemplateParameterFile infra-as-code/bicep/modules/hubNetworking/hubNetworking.parameters.example.json `
-parDdosEnabled $varDdosEnabled `
-ResourceGroupName $varConnectionRG 

New-AzResourceGroupDeployment: 7:32:57 AM - Error: Code=CaseSensitiveDeploymentParameterNamesFound; Message=The deployment parameters are using case sensitive names. The error parameter name(s): parDdosEnabled. Please see https://aka.ms/arm-keyvault for usage details.

New-AzResourceGroupDeployment: The deployment validation failed

## Expected behaviour

No error :-)

## Screenshots 📷

NA

## Correlation ID

NA

## Additional context

Based on my investigation, I can see the mismatch in the 
hubNetworking.bicep> parDDoSEnabled
hubNetworking.parameters.example.json> parDdosEnabled
Documentation> parDdosEnabled

Similar inconsistency for parDDoSPlanName / parDdosPlanName

The error trigger only if we use Bicep parameter and -TemplateParameterFile together.

Solution > Align casing - I could do it but I am not sure how to interpret the camelCase rules so I let to the experts.

**Comment by jtracey93** [comment]
Hey @cbezenco, Thanks for raising this, good catch.

We decided as a team today that it should be proper camel casing so `parDdosEnabled` is the right way forward.

Wanted to reach out and see if you wanted to submit a PR for this and contribute to the repo?

Let us know either way so we can get this fixed 👍👍

Thanks

Jack

**Comment by cbezenco** [comment]
Thanks, I will submit PR :-)

**Comment by jtracey93** [comment]
as discussed on the PR #196 please also change this 😊
