### ISSUE TITLE
💡 Feature Request - Future parity on Private DNS Zones with Portal experiences

### ISSUE THREAD

**Issue by JimmyKarlsson112** [Azure/ALZ-Bicep#202]
## Describe the solution you'd like

Add new Private DNS Zones that were added to Portal experience to make the ALZ-Bicep same in future parity

**Comment by jtracey93** [comment]
Thanks for raising @JimmyKarlsson112.

@cloudchristoph is this something you've already covered in #165 - e.g. updated all the private DNS zones as per https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration ?

Let us know so we can close/deal with this issue 👍

**Comment by cloudchristoph** [comment]
Not covered yet. I'll update all Zone params with the current set of zones today, except for the regional ones.

**Comment by jtracey93** [comment]
Perfect thanks @cloudchristoph. If we can add the regional ones and concat the region from the parameter or deployment location into the name, this is what we do in the portal experience here: https://github.com/Azure/Enterprise-Scale/pull/947/files#diff-58a2a55a8192e9f53dbbf24829de525fd2dfe86dd56d9ea5fe4ce54f71eac970

Of course, customers can always override the parameters input value themselves, but by default lets give them a hand 👍

**Comment by cloudchristoph** [comment]
## Added from official Docs

- privatelink.dev.azuresynapse.net
- privatelink.managedhsm.azure.net
- privatelink.${parLocation}.backup.windowsazure.com
- privatelink.monitor.azure.com
- privatelink.oms.opinsights.azure.com
- privatelink.ods.opinsights.azure.com
- privatelink.agentsvc.azure-automation.net

## Fixed

- privatelink.siterecovery.windowsazure.com is not regional

## Missing in offical Private Links docs but included here

- privatelink.webpubsub.azure.com
- privatelink.azure-devices-provisioning.net

**Comment by cloudchristoph** [comment]
> Perfect thanks @cloudchristoph. If we can add the regional ones and concat the region from the parameter or deployment location into the name, this is what we do in the portal experience here: https://github.com/Azure/Enterprise-Scale/pull/947/files#diff-58a2a55a8192e9f53dbbf24829de525fd2dfe86dd56d9ea5fe4ce54f71eac970
> 
> Of course, customers can always override the parameters input value themselves, but by default lets give them a hand 👍

We have the regional ones covered within the default parameter of the Bicep files, because there we can work with the dynamic location parameter. But not in the example Parameter JSON files. Is this a problem?

**Comment by jtracey93** [comment]
> > Perfect thanks @cloudchristoph. If we can add the regional ones and concat the region from the parameter or deployment location into the name, this is what we do in the portal experience here: https://github.com/Azure/Enterprise-Scale/pull/947/files#diff-58a2a55a8192e9f53dbbf24829de525fd2dfe86dd56d9ea5fe4ce54f71eac970
> > Of course, customers can always override the parameters input value themselves, but by default lets give them a hand 👍
> 
> We have the regional ones covered within the default parameter of the Bicep files, because there we can work with the dynamic location parameter. But not in the example Parameter JSON files. Is this a problem?

I believe this is because the parameter files cannot do the interpolation like can be done in the bicep modules themselves. So, we either need to add a placeholder and advise customers to change the values themselves in the parameters files or not specify them at all in params and use the defaults.

Does that make sense (hard to explain 😄)
