### ISSUE TITLE
Azure Firewall with Virtual Hub deployment fails as unable to set Public IP

### ISSUE THREAD

**Issue by chris5287** [Azure/ALZ-Bicep#219]
https://github.com/Azure/ALZ-Bicep/blob/efa25290d42e92ab6ae88ad8903d443facb541f5/infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep#L169

This does not work with Virtual Hubs, it appears the Public IP is a read only resource that gets randomly allocated?

**Comment by jtracey93** [comment]
Hey @chris5287,

Thanks for raising this. Aware we are speaking on Friday on a call. 

However, I have just tested this and it worked for me (also we test all PRs so had me a little concerned how may of this one slipped by 😁):
![image](https://user-images.githubusercontent.com/41163455/165564021-c14924b8-14cf-42fe-8550-82e8093792b8.png)

Can you share some more info around any customizations you made and what the error is/was?

Thanks

Jack

**Comment by chris5287** [comment]
The issue occurs on the 2nd deployment, as the initial deployment seems to ignore the value provided. 

If you check your deployment you should see the Public IP against the Azure Firewall does not match the one that was provisioned?

**Comment by jtracey93** [comment]
> The issue occurs on the 2nd deployment, as the initial deployment seems to ignore the value provided. 
> 
> If you check your deployment you should see the Public IP against the Azure Firewall does not match the one that was provisioned?

Thanks will investigate in the morning 👍

**Comment by jtracey93** [comment]
Thanks @chris5287 you are indeed correct about the 2nd deployment and the public IP not being used.

I am working on a fix for this as we speak and hope to get out soon 👍
