### ISSUE TITLE
💡 Feature Request - Add zone configuration for hub network PIPs

### ISSUE THREAD

**Issue by BernieWhite** [Azure/ALZ-Bicep#241]
<h2 id=describethesolutionyoudlike>Describe the solution you'd like </h2>
<p>Currently several public IP addresses are created for numerous services in the hub networking module, this includes: </p>
<ul>
<li>Azure Firewall </li>
<li>VPN/ Expression Gateway </li>
<li>Azure Bastion </li>
</ul>
<p>Currently there is a configuration for availability zones supported with Azure Firewall which also sets the <code>zones</code> property of the public IP address through the <code>parAzureFirewallAvailabilityZones</code> parameter. </p>
<p>For VPN/ ER gateways, to fully support availability zones a AZ SKU + a public IP across more then one zone is required for zone redundancy. If you deploy via that Azure Portal, the Zone Redundancy option includes zones 1, 2, 3. </p>
<p>Currently I can't see any docs specifically calling out if Azure Bastion supports availability zones and the resource configuration does not have a telling <code>zones</code> property so I will assume not. </p>
<p>The other PIPs ideally should support availability zones to align to Well-Architected Framework (WAF) recommendation for reliability when a region supports it. </p>
<h2 id=additionalcontext>Additional context </h2>
<p>This is reported by PSRule for Azure: https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.PublicIP.AvailabilityZone/ </p>
<p>Related to #206 </p>

**Comment by jtracey93** [comment]
Ado sync

**Comment by jhajduk-microsoft** [comment]
Fixed in PR 306 - waiting for merge
