### ISSUE TITLE
💡 Feature Request - Use to latest API versions in all modules

### ISSUE THREAD

**Issue by jtracey93** [Azure/ALZ-Bicep#247]
## Describe the solution you'd like

Use latest API versions in all modules as per #245 

## Module List

> Scroll right and left

| Module | Path | Issue | PR | State |
| -------- | ----- | ------ | -- | ------ |
| containerRegistry | infra-as-code/bicep/CRML/containerRegistry/containerRegistry.bicep | TBC | TBC | TBC |
| cuaIdManagementGroup | infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdManagementGroup.bicep | TBC | TBC | TBC |
| cuaIdResourceGroup | infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdResourceGroup.bicep | TBC | TBC | TBC |
| cuaIdSubscription | infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdSubscription.bicep | TBC | TBC | TBC |
| cuaIdTenant | infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdTenant.bicep | TBC | TBC | TBC |
| subscriptionAlias | infra-as-code/bicep/CRML/subscriptionAlias/subscriptionAlias.bicep | TBC | TBC | TBC |
| mc-cafNetworkManagementRole | infra-as-code/bicep/modules/customRoleDefinitions/definitions/china/mc-cafNetworkManagementRole.bicep | TBC | TBC | TBC |
| mc-cafSecurityOperationsRole | infra-as-code/bicep/modules/customRoleDefinitions/definitions/china/mc-cafSecurityOperationsRole.bicep | TBC | TBC | TBC |
| cafApplicationOwnerRole | infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafApplicationOwnerRole.bicep | TBC | TBC | TBC |
| cafNetworkManagementRole | infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafNetworkManagementRole.bicep | TBC | TBC | TBC |
| cafSecurityOperationsRole | infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafSecurityOperationsRole.bicep | TBC | TBC | TBC |
| cafSubscriptionOwnerRole | infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafSubscriptionOwnerRole.bicep | TBC | TBC | TBC |
| customRoleDefinitions | infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep | TBC | TBC | TBC |
| mc-customRoleDefinitions | infra-as-code/bicep/modules/customRoleDefinitions/mc-customRoleDefinitions.bicep | TBC | TBC | TBC |
| hubNetworking | infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep | TBC | TBC | TBC |
| logging | infra-as-code/bicep/modules/logging/logging.bicep | N/A | #264 |  ✅ |
| managementGroups | infra-as-code/bicep/modules/managementGroups/managementGroups.bicep | TBC | TBC | TBC |
| alzDefaultPolicyAssignments | infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep | TBC | TBC | TBC |
| policyAssignmentManagementGroup | infra-as-code/bicep/modules/policy/assignments/policyAssignmentManagementGroup.bicep | TBC | TBC | TBC |
| customPolicyDefinitions | infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep | TBC | TBC | TBC |
| mc-customPolicyDefinitions | infra-as-code/bicep/modules/policy/definitions/mc-customPolicyDefinitions.bicep | TBC | TBC | TBC |
| privateDnsZones | infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep | N/A | N/A |  ✅ |
| publicIp | infra-as-code/bicep/modules/publicIp/publicIp.bicep | TBC | TBC | TBC |
| resourceGroup | infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep | TBC | TBC | TBC |
| roleAssignmentManagementGroup | infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep | TBC | TBC | TBC |
| roleAssignmentManagementGroupMany | infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroupMany.bicep | TBC | TBC | TBC |
| roleAssignmentSubscription | infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscription.bicep | TBC | TBC | TBC |
| roleAssignmentSubscriptionMany | infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscriptionMany.bicep | TBC | TBC | TBC |
| spokeNetworking | infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep | TBC | TBC | TBC |
| subscriptionPlacement | infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep | TBC | TBC | TBC |
| vnetPeering | infra-as-code/bicep/modules/vnetPeering/vnetPeering.bicep | TBC | TBC | TBC |
| hubVirtualNetworkConnection | infra-as-code/bicep/modules/vnetPeeringVwan/hubVirtualNetworkConnection.bicep | TBC | TBC | TBC |
| vnetPeeringVwan | infra-as-code/bicep/modules/vnetPeeringVwan/vnetPeeringVwan.bicep | TBC | TBC | TBC |
| vwanConnectivity | infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep | TBC | TBC | TBC |
| hubPeeredSpoke | infra-as-code/bicep/orchestration/hubPeeredSpoke/hubPeeredSpoke.bicep | TBC | TBC | TBC |

## Additional context

cc: @olljanat for awareness

**Comment by jtracey93** [comment]
Awaiting to be merged #227 before working on

**Comment by jfaurskov** [comment]
Does it make sense? From time to time api changes can cause existing properties to no longer be usable, also of course there will be quite a bit of overhead on maintaining this, for limited value that I can see. I would advocate for staying on current versions and update as/when required, i.e. when new functionality is introduced that needs to be supported or specific functionality is requested through issue/pr.

**Comment by jtracey93** [comment]
Discussion from the team is that this is an ongoing effort and there is no clear end state, as API versions will always change.

### Will do the following to close issue
- Update contribution guide to say every time you update a module, you bump the version to the latest available
    - If latest, API version causes issue, must add a comment inline as to what the issue is
- Add it to the PR Template to make sure it's clear that it must be updated

### We are considering
- Creating a script to check the version of what is being deployed against the latest available
    - And maybe making this a unit test, etc.

Thoughts @olljanat

**Comment by olljanat** [comment]
> ### Will do the following to close issue
> 
>     * Update contribution guide to say every time you update a module, you bump the version to the latest available
>       
>       * If latest, API version causes issue, must add a comment inline as to what the issue is
> 
>     * Add it to the PR Template to make sure it's clear that it must be updated

@jtracey93 Strongly agreed. Especially with the part that there should be documented reason why old API version is used.


> Does it make sense? From time to time api changes can cause existing properties to no longer be usable, also of course there will be quite a bit of overhead on maintaining this, for limited value that I can see. I would advocate for staying on current versions and update as/when required, i.e. when new functionality is introduced that needs to be supported or specific functionality is requested through issue/pr.

@jfaurskov Background for this is that I tried to implement what is described on #249 and find out that there is multiple existing issues here which exist only because old API versions are used (one example of those https://github.com/Azure/bicep/issues/5581#issuecomment-1135935353 )

It is true that in general reason to use API versioning is that it should allow implementing breaking changes. However reality looks to be that Azure team fear to do so which why this issue have been open almost **six years** https://github.com/Azure/azure-quickstart-templates/issues/2786 and latest feedback from responsible team looks to be that they know that breaking change is needed and are waiting for approval for it so I don't think that those will happen very often.
