### ISSUE TITLE
🪲 Bug Report - loadTextContent called multiple times for the same file causes bloat

### ISSUE THREAD

**Issue by KevinRabun** [Azure/ALZ-Bicep#254]
## Describe the bug

custom-policy-definitions.bicep calls loadTextContent multiple times for the same file. This causes the content of the file to be put into the output file multiple times which bloats the file significantly

## To Reproduce

Steps to reproduce the behaviour:

1. Build a bicep file that uses custom-policy-definitions.bicep and take not of the size of the output file
2. Manually replace the redundant calls to loadTextContent in custom-policy-definitions.bicep by using a var instead
3. Build the new bicep file and take note of the size of the output file

## Expected behaviour

custom-policy-definitions.bicep should only load each file it needs one time and store the content in a var to prevent file bloat

### Good example

> Note the `definitionParameters` in each of the examples

```
var publicPaasEndpointsParams = json(loadTextContent('lib/policy_set_definitions/policy_set_definition_es_deny_publicpaasendpoints.parameters.json'))

... other stuff removed for clarity

libSetChildDefinitions: [
      {
        definitionReferenceID: 'ACRDenyPaasPublicIP'
        definitionID: '/providers/Microsoft.Authorization/policyDefinitions/0fdf0491-d080-4575-b627-ad0e843cba0f'
        definitionParameters: publicPaasEndpointsParams.ACRDenyPaasPublicIP.parameters
      }
      {
        definitionReferenceID: 'AFSDenyPaasPublicIP'
        definitionID: '/providers/Microsoft.Authorization/policyDefinitions/21a8cd35-125e-4d13-b82d-2e19b7208bb7'
        definitionParameters: publicPaasEndpointsParams.AFSDenyPaasPublicIP.parameters
      }
```

### Bloated Example (code today)

```
libSetChildDefinitions: [
      {
        definitionReferenceID: 'ACRDenyPaasPublicIP'
        definitionID: '/providers/Microsoft.Authorization/policyDefinitions/0fdf0491-d080-4575-b627-ad0e843cba0f'
        definitionParameters: json(loadTextContent('lib/policy_set_definitions/policy_set_definition_es_deny_publicpaasendpoints.parameters.json')).ACRDenyPaasPublicIP.parameters
      }
      {
        definitionReferenceID: 'AFSDenyPaasPublicIP'
        definitionID: '/providers/Microsoft.Authorization/policyDefinitions/21a8cd35-125e-4d13-b82d-2e19b7208bb7'
        definitionParameters: json(loadTextContent('lib/policy_set_definitions/policy_set_definition_es_deny_publicpaasendpoints.parameters.json')).AFSDenyPaasPublicIP.parameters
      }
```
## Correlation ID

A correlation ID really helps us investigate your issue further. Please provide one if possible. Details on how to find a correlation ID can be found here: [Correlation ID and support](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#correlation-id-and-support)

## Additional context

Anything else we should know to help us troubleshoot this bug? I have created a separate but highly related issue on the bicep side here https://github.com/Azure/bicep/issues/6970

**Comment by alex-frankel** [comment]
0.7 is going to release on 6/10, so it still might make it in. We'll see :)
