### ISSUE TITLE
❓👂 Question/Feedback -AzOps Integration/Accelerator

### ISSUE THREAD

**Issue by shivashant25** [Azure/ALZ-Bicep#284]
## Question/Feedback

Let us know your question or feedback here?

Hi @jtracey93, I have completed the deployment flow and have all the resources ready. Now I want to set up a GitHub repository for the same. 

If I follow the ARM template (https://github.com/Azure/Enterprise-Scale) approach for deploying ALZ. It automatically creates a GitHub repo and adds content to it. Is there a similar automated approach or documentation using a bicep template?

Here's the reference of the github repo which is created using ARM template approach

![image](https://user-images.githubusercontent.com/81952290/178302583-368fa4a2-cd6a-46b9-bb4e-98646c3a0885.png)

Please need help with this.

**Comment by jtracey93** [comment]
Hi @shivashant25,

Thanks for the issue/question.

The screenshot you show is actually AzOps thats an external tool that can be used in any Azure environment. There is an open issue for Bicep support in AzOps today here: https://github.com/Azure/AzOps/issues/523 

However, you could hook up AzOps once you have deployed ALZ-Bicep by following: https://github.com/azure/azops/wiki/github-actions

We have a number of consumption methods for ALZ-Bicep as listed here: https://github.com/Azure/ALZ-Bicep/wiki/ConsumerGuide in which we have example pipelines you can use: https://github.com/Azure/ALZ-Bicep/wiki/PipelinesGitHub

We are also planning an "accelerator" repo that you can use as a template repo and then just plug in your credentials and away you go. Would this be something you see value in? Would love for your insights on what you'd expect from an accelerator repo for ALZ-Bicep.

Thanks

Jack

**Comment by shivashant25** [comment]
Thank you @jtracey93 for your response and for providing the resource.

Yes, the accelerator repo will help us, and we can give a try to implement it in our environment.
