### ISSUE TITLE
Spoke vNET for Identity Subscription

### ISSUE THREAD

**Issue by gin1974** [Azure/ALZ-Bicep#285]
The existing Enterprise-Scale Landing Zone Arm templates currenlty include an option to have an Identity Subscirption that can host Active Directory Domain Controlleers. A vNET spoke is created that is peered to the Hub vNET. Are there any plans to incorprorate this into the ALZ-Bicep modules?

**Comment by jtracey93** [comment]
Hey @gin1974,

You can do this today with the [`hubPeeredSpoke` module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/orchestration/hubPeeredSpoke) 👍

This module was created from a discussion around the identity subscription also, it's worth a read if you're interested here: https://github.com/Azure/ALZ-Bicep/issues/173

Do you think we should call this out in our wiki a little more? If so, can you suggest a location in the wiki to call it out? 👍

Looking forward to hearing from you, but hopefully you can use the [`hubPeeredSpoke` module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/orchestration/hubPeeredSpoke) right away to achieve your requirement 👍

Thanks

Jack

**Comment by gin1974** [comment]
Thanks for the reply Jack. This is what I was looking for. Didn't see that in the closed feature requests. It would possibly be good to call this out here https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/orchestration/hubPeeredSpoke and specify that this can be looped to create multiple hub-spoke peerings as per the option in the Enterprise-Scale ARM templates for the identity scubscription that often hosts DC's
