### ISSUE TITLE
💡 Feature Request - Subscription ID placement in Management Groups

### ISSUE THREAD

**Issue by VRThompson** [Azure/ALZ-Bicep#295]
Dear ALZ Team,

I have a number of new clients where I would like to deploy this landing zone via Bicep, I was working through the steps in my test lab but would like an easier way to define where my subscriptions go.

For example if my client has 10 subscriptions I would like to within the Bicep code define the Subscription ID and where I would like to place that within the Management group Structure (eg. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx goes to Landing Zones - Online).  See example Screenshot : 

![Screenshot 2022-07-28 081416](https://user-images.githubusercontent.com/104138152/181445165-47cdccc6-58d7-49c0-8dbd-e5f3db27b0c5.jpg)

Would this be possible soon as I have a few clients within the next month I would like to deploy this to?

Many thanks and keep up the excellent work.

Thanks

**Comment by jtracey93** [comment]
Thanks @VRThompson, picking this up and starting working on now, good suggestion indeed.

**Comment by jtracey93** [comment]
@VRThompson PR submitted today and will review with my ALZ Bicep team tomorrow https://github.com/Azure/ALZ-Bicep/pull/298

**Comment by jtracey93** [comment]
This has been reviewed and merged👍

Enjoy and look forward to any feedback 👍

**Comment by VinceThompson** [comment]
@jtracey93 thanks very much for this just what I wanted.  👍
