### ISSUE TITLE
💡 Feature Request - Allow for subscription naming on placement

### ISSUE THREAD

**Issue by bartlannoeye** [Azure/ALZ-Bicep#307]
### Problem statement
Azure subscriptions are one of the few items that can be renamed after creation. It's not uncommon to ask the CSP or a team member for a number of new subscriptions, or even create "a dozen" yourself when setting up a new tenant. While it's certainly possible to name this correctly on creation, it adds some complexity:

* the person creating the subscriptions needs to know the naming conventions or be given a list (eg. CSP handling multiple customers, but not being the one setting the naming convention)
* the person parameterizing ALZ needs to correctly map all subscription ids in the ALZ templates to make sure the "networking" platform sub isn't placed under landing zones.

There's also the use case were a brownfield tenant is moved to ALZ and a heap of existing subs need to be moved and renamed towards a naming convention as result of a governance exercise.

### Preferred solution
Being able to name subscriptions in the subscriptions placement module, by converting the `parSubscriptionIds` parameter to an object array or adding a second (mutually exclusive?) parameter.

## Describe alternatives you've considered

Manual naming labor 👎

**Comment by jtracey93** [comment]
Hey @bartlannoeye,

Have been giving this some thought so apologies for delay. 

Unfortunately I don't think this one is something we would do or add as a feature. 

## Why?

- No ARM, and therefore bicep, API to allow subscription renames
    - Potentially could use subscription aliases but that puts a lot of dependencies on higher level permissions like tenant scoped and also access to billing account etc.
        - Which in a CSP scenario wouldn't be possible anyway as the client wouldn't have access to the billing account so therefore couldn't create an alias. 
- Someone is going to have to find all the IDs anyway at some point to be able to rename them, if a suitable API did exist anyway - therefore not really saving any time for anyone ☹️

## Wrap up 

So with all this in mind I don't think we will be implementing this I'm afraid. 

I'll leave the issue open for a few days in case you think I'm missing something completely, in which case do let me know (it is possible 😂)

Thanks and let me know your thoughts

Jack

**Comment by bartlannoeye** [comment]
Came to a similar conclusion (lack of ARM/Bicep API) last week when digging deeper into this, hoping you'd pull it out of your sleeve ;). I guess manual renames might be the fastest to do then.

**Comment by jtracey93** [comment]
Afraid so @bartlannoeye :(
