### ISSUE TITLE
❓👂 Question/Feedback - Use relative urls in markdown docs

### ISSUE THREAD

**Issue by bartlannoeye** [Azure/ALZ-Bicep#308]
<h2 id=questionfeedback>Question/Feedback </h2>
<p>Currently most (all?) docs have absolute URLs. Is this an intended action to always link back to the main repo?
This prevents forking ALZ and updating docs without checking every single file targeting that specific doc to have a relative link. </p>
<h2 id=possibleanswerssolutions>Possible Answers/Solutions? </h2>
<p>Consider converting all doc links to relative paths. </p>

**Comment by jtracey93** [comment]
Hey @bartlannoeye,

is this mainly relating to the wiki docs?

**Comment by bartlannoeye** [comment]
Hey @jtracey93, I did a quick check and have 210 hits on which about half points to the wiki and other point to code files/directories/markdown files.

I did some extra tests and noticed that there might be a case where keeping the absolute links might be beneficial though for documentation UX: private forks on free tiered GitHub give following message when browsing to the wiki path: 

    Upgrade to GitHub Team or make this repository public to enable this feature.

However, one might wonder if an organization prefers going through the hassle of making a private fork for any good reason, then they can probably afford the Team upgrade as well.

**Comment by jtracey93** [comment]
With this in mind @bartlannoeye I think we might leave it as it is. 

Agreed?

**Comment by jtracey93** [comment]
@bartlannoeye did we want to close this one as per our teams chat?

**Comment by bartlannoeye** [comment]
Yes @jtracey93.

For the record: absolute links are sure to work (and link to the official docs), even in case an organization goes for a private fork. There is no intent to add complexity of making everything relative for the odd chance someone wants to tweak docs to their needs. If desired, an organization can fix specific links/docs in their fork or document in their preferred tooling (e.g. Confluence).
