### ISSUE TITLE
💡 Feature Request - Please add version information to repo root 

### ISSUE THREAD

**Issue by KevinRabun** [Azure/ALZ-Bicep#311]
<h2 id=describethesolutionyoudlike>Describe the solution you'd like </h2>
<p>I'd like a json file at the root of the repo that conveys version information about the ALZ. The version number should match the release version number so that a consumer knows what version they are using in their environment for deployments. </p>

**Comment by jtracey93** [comment]
Great request and will make this part of our release criteria that we are looking at this month.  

Cc; @mblant

**Comment by jtracey93** [comment]
trigger

**Comment by jtracey93** [comment]
Have added here: https://github.com/Azure/ALZ-Bicep/blob/main/version.json

Thoughts?

cc: @mblant
