### ISSUE TITLE
🪲 Bug Report - Typo in a few docs

### ISSUE THREAD

**Issue by jtracey93** [Azure/ALZ-Bicep#319]
![image](https://user-images.githubusercontent.com/41163455/191821357-5f27da39-91c4-4da9-a37b-5d6bcb3e7136.png)
Says hubPeeredSpoke but should be subPlacementAll

![image](https://user-images.githubusercontent.com/41163455/191821824-be60fe9d-8bce-4ed2-b986-6bf5e3c56d26.png)

**Comment by jtracey93** [comment]
@johnlokerse that would be amazing. I'll assign to you now 👍

Thank you

**Comment by johnlokerse** [comment]
Opened a PR to keep track of the progress: [PR 331](https://github.com/Azure/ALZ-Bicep/pull/331)
