### ISSUE TITLE
🪲 Bug Report - PowerShell Error `Error: New-AzTenantDeployment : Error parsing boolean value. Path '', line 1, position 1.`

### ISSUE THREAD

**Issue by shivashant25** [Azure/ALZ-Bicep#320]
## Question/Feedback

Hi, I'm facing an issue while setting ALZ environment using Powershell ISE. I cloned the repo using Git commands. But facing an issue. Here's the screenshot of the issue and the error.

Error: New-AzTenantDeployment : Error parsing boolean value. Path '', line 1, position 1.
At line:1 char:1
 New-AzTenantDeployment -TemplateFile "managementGroups.bicep" -Templa ...
      CategoryInfo          : CloseError: (:) [New-AzTenantDeployment], JsonReaderException
      FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureTenantDeploymen 
   tCmdlet

![image](https://user-images.githubusercontent.com/81952290/192548683-e16990eb-dc98-472b-8c0e-d1e18c9baede.png)

Please look into this. Thanks

**Comment by johnlokerse** [comment]
Hi @shivashant25 - I tried to reproduce the problem, but managementGroup.bicep validates successfully on my side. Can you share the parameter file that you are supplying to managementGroup.bicep?

**Comment by jtracey93** [comment]
I would suggest using powershell core and updating to the latest az modules for powershell. 

Looks like your powershell and az modules are out of date.

**Comment by shivashant25** [comment]
Hi @jtracey93,

I Installed **PowerShell core with PowerShell version 7.2.6** and Az module using the command **Install-Module -Name Az -Repository PSGallery -Force**. But I'm still facing the same error. I had deployed the whole ALZ setup using CloudShell. It worked as expected in CloudShell.

![image](https://user-images.githubusercontent.com/81952290/192769632-26aa70ab-f7d9-4a5b-b018-7c9c9e0981fb.png)

Here's the parameters file:

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "parTopLevelManagementGroupPrefix": {
      "value": "eslz"
    },
    "parTopLevelManagementGroupDisplayName": {
      "value": "eslz"
    },
    "parTopLevelManagementGroupParentId": {
      "value": ""
    },
    "parLandingZoneMgAlzDefaultsEnable": {
      "value": true
    },
    "parLandingZoneMgConfidentialEnable": {
      "value": false
    },
    "parLandingZoneMgChildren": {
      "value": {}
    },
    "parTelemetryOptOut": {
      "value": false
    }
  }
}

**Comment by johnlokerse** [comment]
@shivashant25 Your parameter file looks good to me. I found this thread on the GitHub repo of Bicep: https://github.com/Azure/bicep/discussions/3140. Can this help you?

**Comment by shivashant25** [comment]
Hi @johnlokerse, I tried the workaround. It is working as expected. I'm closing this issue.

Thanks for the help :).
