### ISSUE TITLE
Module: Custom Policy Definitions never succeeds

### ISSUE THREAD

**Issue by hannovdm** [Azure/ALZ-Bicep#326]
I consistently get the below error when executing:

New-AzManagementGroupDeployment `
>>   -TemplateFile infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep `
>>   -TemplateParameterFile infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json `
>>   -Location southafricanorth `
>>   -ManagementGroupId pal

ERROR -----------------------------------

New-AzManagementGroupDeployment: 10:28:55 - The deployment 'customPolicyDefinitions' failed with error(s). Showing 3 out of 4 error(s).
Status Message: The policy set definition 'Deploy-Diagnostics-LogAnalytics' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Diagnostics-ACI,Deploy-Diagnostics-ACR,Deploy-Diagnostics-AnalysisService,Deploy-Diagnostics-ApiForFHIR,Deploy-Diagnostics-APIMgmt,Deploy-Diagnostics-ApplicationGateway,Deploy-Diagnostics-WebServerFarm,Deploy-Diagnostics-Website,Deploy-Diagnostics-AA,Deploy-Diagnostics-AVDScalingPlans,Deploy-Diagnostics-Bastion,Deploy-Diagnostics-CDNEndpoints,Deploy-Diagnostics-CognitiveServices,Deploy-Diagnostics-CosmosDB,Deploy-Diagnostics-Databricks,Deploy-Diagnostics-DataExplorerCluster,Deploy-Diagnostics-DataFactory,Deploy-Diagnostics-DLAnalytics,Deploy-Diagnostics-EventGridSub,Deploy-Diagnostics-EventGridTopic,Deploy-Diagnostics-EventGridSystemTopic,Deploy-Diagnostics-ExpressRoute,Deploy-Diagnostics-Firewall,Deploy-Diagnostics-FrontDoor,Deploy-Diagnostics-Function,Deploy-Diagnostics-HDInsight,Deploy-Diagnostics-iotHub,Deploy-Diagnostics-LoadBalancer,Deploy-Diagnostics-LogicAppsISE,Deploy-Diagnostics-MariaDB,Deploy-Diagnostics-MediaService,Deploy-Diagnostics-MlWorkspace,Deploy-Diagnostics-MySQL,Deploy-Diagnostics-NIC,Deploy-Diagnostics-NetworkSecurityGroups,Deploy-Diagnostics-PostgreSQL,Deploy-Diagnostics-PowerBIEmbedded,Deploy-Diagnostics-RedisCache,Deploy-Diagnostics-Relay,Deploy-Diagnostics-SignalR,Deploy-Diagnostics-SQLElasticPools,Deploy-Diagnostics-SQLMI,Deploy-Diagnostics-TimeSeriesInsights,Deploy-Diagnostics-TrafficManager,Deploy-Diagnostics-VM,Deploy-Diagnostics-VirtualNetwork,Deploy-Diagnostics-VMSS,Deploy-Diagnostics-VNetGW,Deploy-Diagnostics-WVDAppGroup,Deploy-Diagnostics-WVDHostPools,Deploy-Diagnostics-WVDWorkspace'. (Code:InvalidCreatePolicySetDefinitionRequest)
Status Message: The policy set definition 'Deploy-MDFC-Config' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-ASC-SecurityContacts'. (Code:InvalidCreatePolicySetDefinitionRequest)
Status Message: The policy set definition 'Deploy-Sql-Security' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Sql-AuditingSettings,Deploy-Sql-SecurityAlertPolicies,Deploy-Sql-Tde,Deploy-Sql-vulnerabilityAssessments'. (Code:InvalidCreatePolicySetDefinitionRequest)
CorrelationId: 99a7a417-13df-4582-8fb0-1c71fd5df703

**Comment by jtracey93** [comment]
Hey @hannovdm,

This is a bit of an untold story of Azure/ARM and eventual consistency.

If you re-run this, say 5 mins after, it should work the second time around.

Can you confirm? We will then add something to our FAQ. This is something we are working on with the various PGs and it is being improved over time, but something we just have to handle today.

**Comment by hannovdm** [comment]
Hi,

I noticed something else in the output, even though I specified a different -ManagementGroupId pal on the cli, in the parameter file it still had 'alz'. Once I also changed that to 'pal', it worked without errors. I guess I assumed that the cli param would overrule.

Id                      : /providers/Microsoft.Management/managementGroups/pal/providers/Microsoft.Resources/deployment
                          s/customPolicyDefinitions
DeploymentName          : customPolicyDefinitions
ManagementGroupId       : pal
Location                : southafricanorth
ProvisioningState       : Failed
Timestamp               : 06/10/2022 09:54:25
Mode                    : Incremental
TemplateLink            :
Parameters              :
                          Name                          Type                       Value
                          ============================  =========================  ==========
                          parTargetManagementGroupId    String                     "alz"
                          parTelemetryOptOut            Bool                       false

Outputs                 :
DeploymentDebugLogLevel :

Thank you for your quick response.

**Comment by jtracey93** [comment]
Hey @maxgaulhofer, it was closed as it wasnt an issue and confirmed as resolved by the raiser as per:
![image](https://user-images.githubusercontent.com/41163455/195636351-b9fbc521-2b70-4f20-871d-23b64268ab05.png)

If you have an issue, please raise a new one and we will be happy to help 👍👍👍
