### ISSUE TITLE
💡 Feature Request - Private DNS Zone Location specific

### ISSUE THREAD

**Issue by gin1974** [Azure/ALZ-Bicep#329]
## Describe the solution you'd like

Hi there,

Really great work in this space and enjoying the progress!

Are there any time scales for introducing location specific DNS zones into the modules, to support ASR of private endpoints as per this guide https://github.com/adstuart/azure-privatelink-multiregion

**Comment by jtracey93** [comment]
Hey @gin1974,

Thanks!

As for the request you can do this today using the [`privateDnsZones` module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/privateDnsZones) and just specifying a separate deployment in your pipelines targeting a different resource group in the new region and you should be good to go.

As for wrapping this in to ALZ-Bicep as a default. I am working closely with Adam and the engineering teams to investigate the scenario further before we commit to making an all-up change to ALZ DNS Guidance, which we are tracking on a feature internally at this time.

But you should be unblocked by just deploying the [`privateDnsZones` module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/privateDnsZones) again to a resource group in a different location and setting the parameters as you require for the other region 

Thanks

Jack
