### ISSUE TITLE
❓👂specify custom resource group in  ALZ/Bicep hubPeeredSpoke module

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/ALZ-Bicep#336]
## Question/Feedback

Hi
I've deployed the ALZ/Bicep hubPeeredSpoke module for peering and udr. It works fine but it creates a default resourcegroup with the name of '(id name)-westeurope-spoke-networking'
We have an different naming convention so I would like to specify another name for the resource group
Does somebody know how to do this?

## Possible Answers/Solutions?

I don't see that I can specify this in the parameter file. Is there another way I can customize this?

**Comment by jtracey93** [comment]
Hey @jerrolmossel,

Thanks for the issue. 

This is possible today in the module by specifying the following parameter: parResourceGroupNameForSpokeNetworking

As per the docs: https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/orchestration/hubPeeredSpoke/README.md

This parameter isn't in the example parameter files but can be easily added by adding an additional object to the parameter file with that parameter name shared above and specifying the value you desire. 

Thanks

Jack

**Comment by jerrolmossel** [comment]
Hi Jack,

Thank you for your quick repons. I'm new to bicep but just before you responded I had a epiphany ;).
Your answer confirms it. I tested it and it works now :). Fairly easy to customize the deployment.

KR,
Jerrol
