### ISSUE TITLE
❓👂 Question/Feedback - Custom Naming for Public IPs - Hub Networking

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/ALZ-Bicep#337]
## Question/Feedback

Hi,

I'm deploying the ALZ\Bicep Module: Hub-Networking and I get fixed public IP names which originates from the 'hubNetworking.bicep' template.

I want to use names according our naming convention.
Does somebody know how to get this done? 

Module modBastionPublicIp '../publicIp/publicIp.bicep' = if (parAzBastionEnabled) {
  name: 'deploy-Bastion-Public-IP'
  params: {
    parLocation: parLocation
    parPublicIpName: '${parAzBastionName}-PublicIp'
    parPublicIpSku: {
      name: parPublicIpSku
    }
    parPublicIpProperties: {
      publicIpAddressVersion: 'IPv4'
      publicIpAllocationMethod: 'Static'
    }
    parTags: parTags
    parTelemetryOptOut: parTelemetryOptOut

hubNetworking.bicep' template:

module modGatewayPublicIp '../publicIp/publicIp.bicep' = [for (gateway, i) in varGwConfig: if ((gateway.name != 'noconfigVpn') && (gateway.name != 'noconfigEr')) {
  name: 'deploy-Gateway-Public-IP-${i}'
  params: {
    parLocation: parLocation
    parPublicIpName: '${gateway.name}-PublicIp'
    parPublicIpProperties: {
      publicIpAddressVersion: 'IPv4'
      publicIpAllocationMethod: 'Static'
    }
    parPublicIpSku: {
      name: parPublicIpSku
    }
    parTags: parTags
    parTelemetryOptOut: parTelemetryOptOut

module modAzureFirewallPublicIp '../publicIp/publicIp.bicep' = if (parAzFirewallEnabled) {
  name: 'deploy-Firewall-Public-IP'
  params: {
    parLocation: parLocation
    parAvailabilityZones: parAzFirewallAvailabilityZones
    parPublicIpName: '${parAzFirewallName}-PublicIp'
    parPublicIpProperties: {
      publicIpAddressVersion: 'IPv4'
      publicIpAllocationMethod: 'Static'
    }
    parPublicIpSku: {
      name: parPublicIpSku
    }
    parTags: parTags
    parTelemetryOptOut: parTelemetryOptOut

## Possible Answers/Solutions?

I looked at the parameters section to see if there is a parameter I can use to specify the public ip names according to our naming convention but there isn't one.
https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/hubNetworking/README.md

**Comment by jtracey93** [comment]
Hey @jerrolmossel,

Todays this isn't possible completely via a parameter input. But you could change the underlying `.bicep` file and either hardcode the desired name or add a parameter for it yourself, then deploy that?

If you do parameterise it you could even look to create a PR back to this repo and contribute back to the project? 👍

Out of interest what is your naming pattern, is it the CAF one? Or is it different?

We see naming as a common ask, but very rarely consistency in approaches between customers, so just looking for an insight as to where you are?

**Comment by jerrolmossel** [comment]
I hardcoded the desired name in the bicep template and it worked. 
Thanks!

**Comment by jerrolmossel** [comment]
I hardcoded the desired name in the bicep template and it worked. 
Thanks!
