### ISSUE TITLE
💡 Feature Request - Change deployment scope for MG Diagnostics

### ISSUE THREAD

**Issue by chrisking81** [Azure/ALZ-Bicep#338]
Thanks for the recently added modules to set the diagnostic settings on the MG hierarchy.

My customer would like to use these but is currently blocked, due to the fact that the orchestration module is a 'tenant' scoped deployment.

My customer has no permissions to \ or Tenant Root Group, due to segregation of duties. 

Could we please investigate whether we can change the orchestration module to be a 'management group' scoped deployment?

**Comment by jtracey93** [comment]
Great ask @chrisking81 and thanks for raising this following our chat this afternoon.

We will triage and prioritise this on our scrum call today.

cc: @lachaves
