### ISSUE TITLE
❓👂 Question/Feedback - Management Group Diagnostic Settings Enablement - New Module

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/ALZ-Bicep#339]
## Question/Feedback

Hi, 

I see that recently (4 days ago) a new module 4.1 was added to the deployment flow

I just completed an ALZ deployment without module 4.1 as I cloned the ALZ-Bicep repo from github last week 

What are the consequences for my current deployment? Do I have to do something with module 4a?
(No alarm as we still are in tst/acc phase)

## Possible Answers/Solutions?

Please advice.

**Comment by jtracey93** [comment]
Hey @jerrolmossel,

This is just a new feature add. No breaking changes as per the [release notes](https://github.com/Azure/ALZ-Bicep/releases)

> You can get notified of new releases following the guidance we have in the [FAQ here in the Wiki](https://github.com/Azure/ALZ-Bicep/wiki/FAQ#how-do-i-get-notified-of-the-latest-releases-in-alz-bicep)

So if you would like to adopt the new feature, you certainly can, just update your fork/clone of the repo. And then just follow the steps in the deployment flow to deploy step/module 4.1.

This just adds diagnostic logging on the Management Groups and sends them to the Log Analytics Workspace for even more platform logging 👍

Let us know if this helps or if you have any questions 

Cheers

Jack

cc: @lachaves

**Comment by jerrolmossel** [comment]
Hi Jack,

Yes, it helped. Thanks again!

**Comment by jerrolmossel** [comment]
Hi Jack,

Yes, it helped. Thanks again!
