### ISSUE TITLE
❓👂 Resource group 'asc-export-alz' is created after ALZ deployment

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/ALZ-Bicep#347]
## Question/Feedback

Hi,

After the ALZ deployment  resource group 'asc-export-alz' is created which stores a hidden resource with the name of 'ExportToWorkspace'
I see it's been created by the Azure policy initiative Assignment - Deploy Microsoft Defender for Cloud configuration

![image](https://user-images.githubusercontent.com/51243261/196927377-26cba6ec-6e9c-4376-a268-d8e1943fb48f.png)

Why is it created in a seperate resource group and not in the resource group where my log analytic workspace resides?

## Possible Answers/Solutions?

Is it best practice to keep a seperate resource group ('asc-export-alz') for this or can I use te resource group where the log anaytic workspace is created?

**Comment by jtracey93** [comment]
Hey @jerrolmossel,

This is indeed created by the policy to store the export configuration settings for that subscription to send its data to the Log Analytics Workspace in the management subscription.

This is a per subscription setting that must be set, hence the resource group being created per subscription to store that subscriptions settings to send the MDFC logs to the central Log Analytics Workspace 👍

Further docs here: https://learn.microsoft.com/en-us/azure/defender-for-cloud/continuous-export?tabs=azure-policy

Thanks

Jack

**Comment by jerrolmossel** [comment]
Clear, thank you! :)
