### ISSUE TITLE
💡 Feature Request - Add support for groups in a policy initiative

### ISSUE THREAD

**Issue by vedagudipati** [Azure/ALZ-Bicep#357]
## Describe the solution you'd like

When creating a policy initiative, currently it is not possible to add the policies within the initiative to specific groups. The ability to club the policies into groups will help summarize the purpose of the policies contained within the policy initiative, especially for a large policy sets.

**Comment by jtracey93** [comment]
Hey @vedagudipati,

This is a great idea and I understand from our discussions internally that you already have the work done and wish to PR this in, so will assign to you and watch out for the PR 👍
