### ISSUE TITLE
🪲 Bug Report - Custom roles deployments on canary management group conflict

### ISSUE THREAD

**Issue by cvitale** [Azure/ALZ-Bicep#362]
## Describe the bug

Deploying custom roles module on a new hierarchy under the same tenant (e.g. canary) goes in conflict with other existing hierarchy. This is expected since role definition name (guid) is calculated from the descriptive name, for example _Network management (NetOps)_ in [/infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafNetworkManagementRole.bicep](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafNetworkManagementRole.bicep#:~:text=var%20varRole%20%3D%20%7B,.name).

## To Reproduce

Steps to reproduce the behaviour:

1. deploy till Custom Role Definitions module under a top parent management group with id XXX
2. deploy till Custom Role Definitions module under a top parent management group with id YYY

## Expected behaviour

Custom role definition name should be generated using top parent management group id too.

## Correlation ID

3ef77205-9315-433b-950e-3a3c081f0eeb

**Comment by jtracey93** [comment]
Thanks @cvitale for raising this. Can you share the error you receive or a screenshot to assist here please? 👍

**Comment by cvitale** [comment]
![image](https://user-images.githubusercontent.com/765246/199261400-dbc800a7-d003-48f5-9404-3dbf102914d2.png)

Here you have it. Thank you.

**Comment by jtracey93** [comment]
This is being picked up by @DaFitRobsta
