### ISSUE TITLE
Bug Report - Unable to deploy Azure China Policy Definitions due to addition of 'Deploy-Budget' Definition

### ISSUE THREAD

**Issue by jim-mclean** [Azure/ALZ-Bicep#365]
## Describe the bug

The addition of the 'Deploy-Budget' to the Azure China policy definitions is causing this error:

  {
      "status": "Failed",
      "error": {
          "code": "InvalidPolicyRuleIfNotExistsDetails",
          "message": "The policy definition 'Deploy-Budget' rule is invalid. The policy effect 'type' field references an invalid resource provider 'Microsoft.Consumption'."
      }
  }

## To Reproduce

Steps to reproduce the behaviour:

az cloud set --name AzureChinaCloud

az login --service-principal --username=$ARM_CLIENT_ID --password=7foY~DV585TgIYAHz8_76-k1K47vx3F~.S --tenant $ARM_TENANT_ID --output none

az deployment mg create --name alz-policy --management-group-id $ROOT_GROUP --location chinanorth3 --template-file "./ALZ-Bicep/infra-as-code/bicep/modules/policy/definitions/mc-customPolicyDefinitions.bicep"  --parameters "./ALZ-Bicep/infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json" --parameters parTargetManagementGroupId=$ROOT_GROUP

## Expected behaviour

Be able to deploy all policies defined in the [mc-customPolicyDefinitions.bicep](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/mc-customPolicyDefinitions.bicep) to Azure China

## Screenshots 📷

![image](https://user-images.githubusercontent.com/670040/199249903-0a8eaf5e-83b1-47f0-a15d-1058218ebd7a.png)

## Correlation ID

6665947e-db57-4d60-b741-27b03c3287c2

**Comment by jtracey93** [comment]
Hey @jim-mclean,

Thanks for raising the issue. Whilst we work on fixing this, you can remove these lines (https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/mc-customPolicyDefinitions.bicep#L176-L179) from your copy of the `mc-customPolicyDefinitions.bicep` module

If you remove this and re-deploy it should work, although let us know if you find any others and we will make a batch of changes to fix all of these.

If we dont hear back, we will just fix this one in the coming weeks

Thanks

Jack

**Comment by jim-mclean** [comment]
Thanks for the quick reply.  No other issues.

Looking forward to having this resolved as we have a pipeline that periodically pulls in changes and that will remain broken until this is resolved.

Going forward would it be possible to run a test deployment against an Azure China Tenant as part of your release process?  Just a quick deployment check would have caught this.

**Comment by jtracey93** [comment]
Yup you make a fair point and we do have an item on our internal backlog around test enhancements

Ill add this to there

**Comment by jtracey93** [comment]
Also created better way to help exclude in #377 so waiting on this to merge, then will update policies for China in #374 and then this should close out this bug. Hoping to complete today/tomorrow

**Comment by jtracey93** [comment]
#378 fixed this
