### ISSUE TITLE
💡 Feature Request - Multi-Region ALZs

### ISSUE THREAD

**Issue by xelizondo** [Azure/ALZ-Bicep#375]
Per this https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/enterprise-scale/faq#how-do-we-enable-more-azure-regions-when-we-use-azure-landing-zone-architecture

Could additional functionality be extended to accommodate multi-region ALZs (platform and workloads) scenarios where customer wants to deploy n regions and have things plumbed correctly per region base for example, diagnostics set to their regional LAW, hubs peered between them etc. although AAD logs would only go to 1 LAW since it is not regional. 

@danycontre  per our chat

**Comment by jtracey93** [comment]
Hey @xelizondo,

Thanks for the issue.

This is possible today with the modules, you'd just need to pass in different parameters for the different regions as you require.

So technically this is already possible.

You'd just need to make an additional policy assignment for the diagnostics stuff to send the stuff to a different LAW, but this is not something we recommend in ALZ guidance 👍

Happy to discuss further, let me know if this helps

Thanks

Jack

**Comment by xelizondo** [comment]
@jtracey93 Thanks for the reply. Dany mentioned something similar. let me review as I am just getting familiar with this ALZ-Bicep repo. If I have questions I will reach out to you.

**Comment by jtracey93** [comment]
@xelizondo please do and if we need to add any docs or clarity, happy to do that but let us know.

Perhaps you could contribute if you wish to also if anything is needed 👍👍

**Comment by xelizondo** [comment]
Yes, I will attempt to build this on a fork perhaps with a bit of Dany's help

**Comment by jtracey93** [comment]
linking to #387 as a relation
