### ISSUE TITLE
💡 Feature Request - RoleAssignments for PolicyAssignments on RG-Scope

### ISSUE THREAD

**Issue by SeSeicht** [Azure/ALZ-Bicep#376]
## Describe the solution you'd like

Currently only MG and Subscription scoped RoleAssignments for Policiy-Assignments are able. I need the same for Resource-Group Scope

## Additional context

RG Scope is sometimes needed if you want to have a more specific Role Assignment instead of using the subscription Scope.

**Comment by jtracey93** [comment]
Thanks @SeSeicht have assigned to you as we discussed.
