### ISSUE TITLE
Update policy assignment for deny public IP

### ISSUE THREAD

**Issue by jfaurskov** [Azure/ALZ-Bicep#386]
## Describe the solution you'd like

On the Enterprise scale repo a [PR](https://github.com/Azure/Enterprise-Scale/pull/1103) changes the policy and assignment for deny public ip. Please modify ALZ-Bicep to reflect this change.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by jtracey93** [comment]
ADO
