### ISSUE TITLE
🪲 Bug Report - Sync ALZ-Bicep repo

### ISSUE THREAD

**Issue by neok-g** [Azure/ALZ-Bicep#397]
Since 8 days there is a new version 1.1.0 of policy "Deploy SQL Database Transparent Data Encryption" (ID = Deploy-Sql-Tde) see: 
https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Sql-Tde.html
https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-Tde.json

However the ALZ-Bicep repo still contains version 1.0.0:
https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_definitions/policy_definition_es_Deploy-Sql-Tde.json

I understood that the enterprise scale repo was daily copied to the ALZ-bicep repo via a Git Action?
But it does not seem to work properly?

**Comment by jtracey93** [comment]
Hey @neok-g,

The sync does run daily, however it is not auto-merged as we like to check and make any additional bicep specific changes.

The PR #384 is on my list to look at today and merge in and then cut a release, stay tuned 👍

**Comment by neok-g** [comment]
@jtracey93 Thanks for your quick response
