### ISSUE TITLE
🪲 Bug Report - alzDefaultPolicyAssignments deployment fails without parPrivateDnsResourceGroupId

### ISSUE THREAD

**Issue by stalejohnsen** [Azure/ALZ-Bicep#406]
## Describe the bug

Testing ALZ Bicep v0.11.0 and deployment of default alz policy assignment fails with parPrivateDnsResourceGroupId = ''. If the parameter is set to the correct resource group ID the deployment is successfully deployed. parPrivateDnsResourceGroupId is not included in min parameters and description states that it is not required. If left empty, the policy Deploy-Private-DNS-Zones will not be assigned to the corp Management Group. Default: Empty String"

## To Reproduce

Steps to reproduce the behaviour:

1. Deploy alzDefaultPolicyAssignments.bicep with alzDefaultPolicyAssignments.parameters.min.json in v0.11.0, not including parPrivateDnsResourceGroupId parameter. 
2. Deployment fails on ALZBicep-polAssi-deployPrivateDNS-** 

## Expected behaviour

Deployment of alzDefaultPolicyAssignments should be successful without including parPrivateDnsResourceGroupId parameter.   

## Screenshots 📷

![image](https://user-images.githubusercontent.com/98233333/204638041-018d4cd0-5cec-4068-bf7b-8e057500fc75.png)

## Correlation ID

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidTemplate\\\",\\r\\n    \\\"message\\\": \\\"Deployment template validation failed: 'The deployment metadata 'SUBSCRIPTION' is not valid.'.\\\",\\r\\n    \\\"additionalInfo\\\": [\\r\\n      {\\r\\n        \\\"type\\\": \\\"TemplateViolation\\\",\\r\\n        \\\"info\\\": {\\r\\n          \\\"lineNumber\\\": 1,\\r\\n          \\\"linePosition\\\": 2714,\\r\\n          \\\"path\\\": \\\"properties.template.resources[1].name\\\"\\r\\n        }\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by jtracey93** [comment]
PR #407 will fix this and hopefully merged in the morning :)
