### ISSUE TITLE
🪲 Bug Report - VPN/ExpressRoute Gateway has different standards compared to vwan or hub setup.

### ISSUE THREAD

**Issue by FallenHoot** [Azure/ALZ-Bicep#409]
## Describe the bug

I noticed two bugs:
`vwanConnectivity.bicep`, that you can flag VPN/ExpressRoute Gateway true/false, but you can't do this in the `hubNetwoking.bicep`. Is this by design?

It is also stated that it is default `false`, but that is not true as it clearly states it is actually enabled by default.

```
@sys.description('Switch to enable/disable VPN Gateway deployment. Default: false')
param parVpnGatewayEnabled bool = true

@sys.description('Switch to enable/disable ExpressRoute Gateway deployment. Default: false')
param parExpressRouteGatewayEnabled bool = true

```

Within the vwanConnectivity.parameters.all.json vwanConnectivity.parameters.min.json
```
"parVpnGatewayEnabled": {
      "value": true
    },
    "parExpressRouteGatewayEnabled": {
      "value": true
    }
```

## To Reproduce

Steps to reproduce the behaviour:

Enabled by default for vwan and doesn't allow for it to be turned off for hub

## Expected behaviour

Should have the option of true/false for hub. 
Should be disabled by default for both vwan and hub.

## Screenshots 📷

N/A

## Correlation ID

N/A

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by jtracey93** [comment]
Hey @FallenHoot,

Thanks for the issue.

It is possible to disable the VPN/ExR GWs as per the docs here: https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/hubNetworking/generateddocs/hubNetworking.bicep.md#parameters
![image](https://user-images.githubusercontent.com/41163455/205293660-b63ab807-1271-4fcf-a4b1-c141b3c434ec.png)

The docs for VWAN are conflicting, good spot, I will create a new issue to track this part and link to this issue. However, we have just moved to programatically generated docs as part of #304 and release `v0.12.0` so we can remove the hardcoded defaults in docs and relay on what the code actually is:
![image](https://user-images.githubusercontent.com/41163455/205294286-a4e25874-8aa7-4f42-8e42-53e29250702d.png)
https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md#parvpngatewayenabled

I will therefore close this issue out as this is possible and there is no bug. Please raise a new feature request if you would like to see more consistency between the approaches in H&S & VWAN ExR/VPN GW deployments 👍

**Comment by FallenHoot** [comment]
@jtracey93, that is the issue of not reading each individual README file like a due diligence end-user would :). Without searching directly for this or knowing about this, I would think by default it would be disabled at default. 

Why have the following preloaded:
```
"parVpnGatewayConfig": {
      "value": {
        "name": "alz-Vpn-Gateway",
        "gatewayType": "Vpn",
        "sku": "VpnGw1",
        "vpnType": "RouteBased",
        "generation": "Generation1",
        "enableBgp": false,
        "activeActive": false,
        "enableBgpRouteTranslationForNat": false,
        "enableDnsForwarding": false,
        "asn": "65515",
        "bgpPeeringAddress": "",
        "bgpsettings": {
          "asn": "65515",
          "bgpPeeringAddress": "",
          "peerWeight": "5"
        }
      }
    },
```

What I have done is simply removed the loop, fixed it so it would be two different functions, and added parExpressRouteGatewayEnabled and parVpnGatewayEnabled to reflect how vwan has it. 

```
module modAzVpnGatewayPublicIp '../publicIp/publicIp.bicep' = if (parVpnGatewayEnabled) {
  name: 'deploy-VPNGateway-Public-IP-'
  params: {
    parLocation: parLocation
    parAvailabilityZones: parAzVpnGatewayAvailabilityZones
    parPublicIpName: 'VPNGateway-PublicIP'
    parPublicIpProperties: {
      publicIpAddressVersion: 'IPv4'
      publicIpAllocationMethod: 'Static'
    }
    parPublicIpSku: {
      name: parPublicIpSku
    }
    parTags: parTags
    parTelemetryOptOut: parTelemetryOptOut
  }
}

module modAzErGatewayPublicIp '../publicIp/publicIp.bicep' = if (parExpressRouteGatewayEnabled) {
  name: 'deploy-ERGateway-Public-IP'
  params: {
    parLocation: parLocation
    parAvailabilityZones: parAzErGatewayAvailabilityZones
    parPublicIpName: 'ERGateway-PublicIP'
    parPublicIpProperties: {
      publicIpAddressVersion: 'IPv4'
      publicIpAllocationMethod: 'Static'
    }
    parPublicIpSku: {
      name: parPublicIpSku
    }
    parTags: parTags
    parTelemetryOptOut: parTelemetryOptOut
  }
} 
```

Doing it this way allows it to have the same function across the network deployments and the ability to simply change the flag to deploy the resource if needed.
