### ISSUE TITLE
🪲 Bug Report - Module Docs Default Values are Conflicting in Places

### ISSUE THREAD

**Issue by jtracey93** [Azure/ALZ-Bicep#410]
## Describe the bug

Module Docs Default Values are Conflicting in Places. We should remove any instance of "default value = xxx" in the `description` decorators so we can rely on what the actual default value is from a code perspective.

This issue originates from #409 

## To Reproduce

See below:
![image](https://user-images.githubusercontent.com/41163455/205294860-3341103d-9419-4cb5-a4a1-d5bad19bc6cf.png)
https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md#parvpngatewayenabled

## Expected behaviour

Docs to be accurate 😁

**Comment by JamJarchitect** [comment]
PR has been merged. Closing issue
