### ISSUE TITLE
🪲 Bug Report - PolicyAssignment lib generating wrong name/paths

### ISSUE THREAD

**Issue by JimmyKarlsson112** [Azure/ALZ-Bicep#426]
## Describe the bug

There is two issues with Lib generation for Policy assignment.
1. The generated lib file adds '${modManagementGroups.outputs.outTopLevelManagementGroupId} instead of  '${varTopLevelManagementGroupResourceId} for definationID. 
2. The path deep is "one to few" on loadjsoncontent
loadJsonContent('../../policy/.. should be loadJsonContent('../../../policy/..

## To Reproduce

Steps to reproduce the behaviour is to check the difference between 

1. Can view the difference between _policyAssignmentsBicepInput.txt and variable section alzDefaultPolicyAssignments.bicep

## Expected behaviour

Lib files generated should have the correct filename and the path should be correct

**Comment by jtracey93** [comment]
Hey @JimmyKarlsson112,

Good spot. Are you spotting this as you are adding additional policy assignments as per the guidance https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies here?

Just trying to gauge the urgency on the bug 👍

Let me know

Thanks

Jack

**Comment by JimmyKarlsson112** [comment]
Correct! Working on a brownfield scenario where we are adding customers custom policies. 
As we are aware of it and can do a "manual" workaround it is not super urgent.

**Comment by jtracey93** [comment]
Hey @JimmyKarlsson112,
Thanks for the info that you are able to workaround this. Related to AB#25950 - new bug we created and will include to look into in January sprint.
