### ISSUE TITLE
❓👂 Question/Feedback - Variable Group csu-bicep-environment not documented

### ISSUE THREAD

**Issue by kevball2** [Azure/ALZ-Bicep#428]
## Question/Feedback

There are 3 pipelines that reference variable group csu-bicep-environment, it does not appear that the variables in this group are documented anywhere.

## Possible Answers/Solutions?

Update the documentation to reflect the variable that should be part of this group

**Comment by jtracey93** [comment]
Hey Kevin,

These pipelines are used for internal testing of this project for PRs etc. 

The variable group exists in our Azure DevOps which isn't public. 

We are working on an accelerator repo that will have more pipeline examples and should be out in the coming months. 

Stay tuned and in the meantime feel free to raise issues if you need anything.

**Comment by kevball2** [comment]
@jtracey93 , 

Thanks for the Feedback, 
I am looking to incorporate the same pipelines (PR validation and build) with a customer deployment I am working on currently. Could I just get a list of the variables? If not I will modify to be able to re-create the same functionality in Azure DevOps

**Comment by jtracey93** [comment]
I believe they are

- azclilogin
- azclitenant
- azclipwd
- Location

You can see them in the pipeline where you see `$(SOMENAME)` the SOMENAME is the name of the variables in the variable group that aren't defined elsewhere in the pipeline 👍
