### ISSUE TITLE
💡 Feature Request - Make the sub management groups under platform optional

### ISSUE THREAD

**Issue by mwolvetang** [Azure/ALZ-Bicep#429]
## Describe the solution you'd like

[AB#26016](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/26016)

The templates default to creating 3 sub management groups under the Platform Management Group (MG) and these are then used for the policy assignments. I would like the option, controlled by a parameter, to create just the Platform MG and assign the policies there.

## Additional context
For our clients we go for the 'Enterprise-scale for small enterprises' (TreyResearch) Landing Zone which has only one subscription in the Platform MG. It looks like this:
![image](https://user-images.githubusercontent.com/65391769/211790755-ca3aeaea-7502-4552-8352-bc1516721754.png)

We have multiple clients and want to deploy the Landing Zone to all of them without having to manual change anything afterward.

**Comment by jtracey93** [comment]
Thanks for raising @mwolvetang good suggestion and ask. 

Would the same capability we have for the landing zones children be a good fit here? https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/managementGroups#child-landing-zone-management-groups-flexibility

Let us know and we can then get on the backlog.

**Comment by mwolvetang** [comment]
> Would the same capability we have for the landing zones children be a good fit here? https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/managementGroups#child-landing-zone-management-groups-flexibility

That is the exact flexibility I was looking for.

**Comment by JamJarchitect** [comment]
PR is in:

https://github.com/Azure/ALZ-Bicep/pull/446
