### ISSUE TITLE
❓👂 Question/Feedback - add existing instance to the LB

### ISSUE THREAD

**Issue by ArthiSaravana** [Azure/ALZ-Bicep#431]
## Question/Feedback

how to add existing vms to the load balancer through bicep? am able to add new vm while creating load balancers. not sure how to add existing nic card or ip address to the load balancer. any idea on this?

# Possible Answers/Solutions?

Just want us to confirm your thinking, let us know any possible answers you've considered and we can confirm 👍

**Comment by JamJarchitect** [comment]
Hi Arthi,

If you are keeping your Infrastructure-as-Code up to date in source control, any configuration for Azure resource code will be current with what is deploye

To add your VMs to your load balancers, I will point you in the direction of the sample code we have in our documentation:

https://learn.microsoft.com/azure/load-balancer/quickstart-load-balancer-standard-internal-bicep?tabs=CLI#review-the-bicep-file

The two sections which are important in this sample code is the `ipConfigurations` section in `resource networkInterface` as well as the `loadBalancingRules` properties under `resource loadBalancer` 

Also do not forget your dependencies in there, you need the load balancer before the NIC or it will not be able to form as part of your backend pool.

Hope this helps!

**Comment by ArthiSaravana** [comment]
this is the code guide me to add 2 existing vms to the LB. but not sure how to add the existing 2 vms(existing 2nic card) to the LB.

param loadbalancerName string = 'loadbalancer213'
param location string = 'australiaeast'

var lbSkuName = 'Standard'
var lbFrontEndName = 'frontend-ip'
var subnetid = resourceId('Microsoft.Network/virtualNetworks/subnets', virtualNetworkName, subnetName)
var virtualNetworkName = 'lb-vnet'
var subnetName = 'lb-subnet'
var BackendPoolName = 'BackendPool1'
var lbprobe = 'ProbeA'

resource internalloadbalancer 'Microsoft.Network/loadBalancers@2022-07-01' = {
  name: loadbalancerName
  location: location
  sku: {
    name: lbSkuName
  }
  properties: {
    frontendIPConfigurations: [
      {
        name: lbFrontEndName
        properties: {
          subnet: {
            id: subnetid
          }
          privateIPAddress: '10.0.0.7'
          privateIPAllocationMethod: 'Static'
        }
      }
    ]
    backendAddressPools: [
      {
        name: BackendPoolName
      }
    ]
    loadBalancingRules: [
      {
        name: 'HTTPRule'
        properties: {
          frontendIPConfiguration: {
            id: resourceId('Microsoft.Network/loadBalancers/frontendIPConfigurations', loadbalancerName, lbFrontEndName)
          }
          backendAddressPool: {
            id: resourceId('Microsoft.Network/loadBalancers/backendAddressPools', loadbalancerName, BackendPoolName)
          }
          frontendPort: 80
          backendPort: 80
          enableFloatingIP: false
          idleTimeoutInMinutes: 4
          protocol: 'Tcp'
          enableTcpReset: false
          loadDistribution: 'Default'
          probe: {
            id: resourceId('Microsoft.Network/loadBalancers/probes', loadbalancerName, lbprobe)
          }
        }
      }
    ]      
probes: [
      {
        name: lbprobe
        properties: {
          intervalInSeconds: 5
          numberOfProbes: 2
          port: 80
          probeThreshold: 2
          protocol: 'TCP'
        }
      }
    ]
  }
}

**Comment by JamJarchitect** [comment]
As this is more focused around Azure Bicep itself rather than ALZ Bicep, I would advise you to raise an issue on the main repository itself rather than on this one:

https://github.com/azure/bicep
