### ISSUE TITLE
ALZ deloyements-single deployments

### ISSUE THREAD

**Issue by ArthiSaravana** [Azure/ALZ-Bicep#436]
## Question/Feedback

need help in deploying hub and spoke architecture in single deployment with the help of modules. In stitch all of the modules together in a bicep file to create a single deployment. 

help me to deploy all resources(AD, firewall, bastion, Log analytics etc..) under multiple subscription with modules in one go.

this is hub one:
<img width="422" alt="automation" src="https://user-images.githubusercontent.com/97679779/214271093-3c9b3283-d3e8-4a9e-bfd7-e88c390a3b1f.png">

**Comment by jtracey93** [comment]
Hey @ArthiSaravana,

Please review the MS Learn module here on guidance on how to achieve this with Bicep https://learn.microsoft.com/training/modules/create-composable-bicep-files-using-modules/?WT.mc_id=learnlive-20220405A%3FWT.mc_id%3Dlearnlive-20220405A

**Comment by ArthiSaravana** [comment]
Hey jtracey93,

need help!! I have 2 modules stg1 and stg2 and 1 main file. I want to deploy the stg1 and stg2 in different subscription. 
stg1 in sub1 and stg2 in sub2. 

I have written code to deploy multiple stg in same subscription. but no idea how to deploy multiple storage accnt in different subscription in single deployment. if I get this idea I can proceed further on the single deployment with multiple resources.

code:
main:
targetScope = 'subscription'
param location string = 'australiaeast'

param resourceGroupNames array = [
  'rg1'
  'rg2'
]

resource rgs 'Microsoft.Resources/resourceGroups@2021-04-01' = [for resourceGroupName in resourceGroupNames: {
  name: resourceGroupName
  location: location
}]

module straccnt 'stg1.bicep' = {
  name: 'resourceDeploy'
  scope: resourceGroup('rg1')
  params: {
    storageaccountname: 'stgd302903987'
    location: location 
  }
  dependsOn: [
    rgs
  ]
}


module stg 'stg2.bicep' = {
  name: 'storagedeploy'
  scope: resourceGroup('rg2')
  params: {
    stgName: 'stgd30290334'
    location: location 
  }
  dependsOn: [
    rgs
  ]
}

stg1:
param  location string = resourceGroup().location

param stgName string =  'stgd302903987'


resource mystorageaccount 'Microsoft.Storage/storageAccounts@2021-02-01' = {
  name: stgName
  location: location
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
  }
  sku: {
    name: 'Standard_LRS'
  }
}

stg2:
param  location string = resourceGroup().location

param storageaccountname string = 'stgd30290334'

resource mystorageaccount 'Microsoft.Storage/storageAccounts@2021-02-01' = {
  name: storageaccountname
  location: location
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
  }
  sku: {
    name: 'Standard_LRS'
  }
}

**Comment by jtracey93** [comment]
Hey @ArthiSaravana,

For clarity, this repo is for ALZ Bicep. It is not a Bicep general support repo, that can be found over here: https://github.com/azure/bicep 👍

I think you need to read the usage of the `resourceGroup()` scope function as you can pass in a subscription ID as well as a resource group to target different resource groups in different subscriptions. e.g. `resourceGroup(subscriptionId, resourceGroupName)` from: https://learn.microsoft.com/azure/azure-resource-manager/bicep/bicep-functions-scope#resourcegroup

So i think adding the sub ID in the `resourceGroup()` function for one of your modules will solve your issues

Thanks

Jack
