### ISSUE TITLE
💡 Feature Request - Ability to deploy the alzDefaults assignments with enforcement mode set to Disabled

### ISSUE THREAD

**Issue by FlashG75** [Azure/ALZ-Bicep#439]
## Describe the solution you'd like

I would like to see the addition of a parameter in the alzDefaultPolicyAssignments.parameters.all.json file that allows you to set the enforcement mode to DoNotEnfore (Disabled). Currently the way to achieve this is by setting this value in each assignment json individually within the lib folder 

## Additional context

I have a requirement to build a new ALZ without any subscriptions. Once deployed, move the existing subscriptions across into this new ALZ. There is a requirement for all policy assignments to be set to Disabled initially. This would allow us to determine what may need to be remediated before we enable them.

**Comment by JamJarchitect** [comment]
Hi @FlashG75 

Thanks for your issue submission - this will be taken to the team for consideration into the solution.

AB#26527
