### ISSUE TITLE
Bug Report: Deny RDP, Deploy-Diag-LA and Deploy-MDFC definitions not found when deploying ALZDefault policies

### ISSUE THREAD

**Issue by DaniMathews** [Azure/ALZ-Bicep#449]
**Describe the bug**
Policy definitions appear to be missing from ALZ-Bicep\infra-as-code\bicep\modules\policy\assignments\lib\policy_assignments

Receive errors upon deployment: (I can resolve the "deny rdp from internet" error by copying from "\ALZ-Bicep\infra-as-code\bicep\modules\policy\definitions\lib\policy_definitions" into the policy assignments folder but I cannot resolve the policy sets by copying them along with their parameter files into policy assignments folder.
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicySetDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy set definition '/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics' could not be found.\"\r\n  }\r\n}"
            }
        ]
    }
}
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy definition '/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Authorization/policyDefinitions/Deny-RDP-From-Internet' could not be found.\"\r\n  }\r\n}"
            }
        ]
    }
}
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicySetDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy set definition '/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config' could not be found.\"\r\n  }\r\n}"
            }
        ]
    }
}
**Steps to reproduce**

1. Deploy ALZDefault Management Groups (without confidential) using custom parameter for "parTopLevelManagementGroupDisplayName"
2. Set parameters for logging to deploy Log Analytics into Australia East within a subscription sitting in the root management group (we're not doing sub deployment as part of this brownfield environment)
3. Create devops pipeline - comment out blocks for everything except 'Management Groups', "Logging' and 'Policy'
4. Run pipeline

**Screenshots**

**Comment by jtracey93** [comment]
Hey @DaniMathews,

Have you seen and followed the Deployment Flow guidance here: https://github.com/Azure/ALZ-Bicep/wiki/DeploymentFlow#high-level-deployment-flow

It looks like you haven't loaded the custom policy definitions in (step 2 from the deployment flow). https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions

Let us know

Thanks

Jack

**Comment by DaniMathews** [comment]
Hi Jack,

My deployment is using the ALZDefault policy module. Do I need to use the custom module as well?

Kind Regards
Daniella

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DaniMathews** [comment]
Hi Jack,

My bad, I misunderstood that 'custom' means custom to the entire deployment and not just when you want to add custom definitions specific to the customer. I thought this line in the doco
"If you want to make all of the default Azure Policy Assignments that we recommend in the Azure Landing Zones conceptual architecture and reference implementation you can use the ALZ Default Policy Assignments module to do this for you"

meant that you didn't need to use the custom module at all. I understand now that it it's still required to 'load' the definitions and the assignment module is for assigning.

There's so much noise at Microsoft at the moment that I wasn't able to concentrate properly on my engagement!

Thanks for the quick response, deployment is working now.

Kind Regards
Daniella
________________________________

**Comment by jtracey93** [comment]
Glad we got it sorted. 👍
