### ISSUE TITLE
❓👂 Question/Feedback - Private DNS Zone link for spoke network

### ISSUE THREAD

**Issue by stijn-geselle-arxus** [Azure/ALZ-Bicep#450]
## Question/Feedback

I've been playing around with ALZ-Bicep lately, but unless I'm missing something, I couldn't figure out how to create a Virtual network link on a Private DNS Zone. I'm managing the Private DNS Zones centrally within the hub subscription and I'm using the `hubPeeredSpoke` module to create new spokes in new subscriptions. This perfectly adds the VWAN VNet link, but apparently does not do this for Private DNS Zones.

Within the `vwanConnectivity` module we can link the Private DNS Zones to a single VNet using `parVirtualNetworkIdToLink`, but I would expect to use the `hubPeeredSpoke` module where we can pass an array of Private DNS Zones (or resource IDs) to link the new spoke VNet to.

Or does the current implementation imply that Private DNS Zones in a hub-spoke architecture should only be linked to one VNet? I was under the assumption that all spoke VNets need a link in order to be able to resolve them.

**Comment by stijn-geselle-arxus** [comment]
Well, what we do at some of our customers is link each VNet (hub and spokes) to the Private DNS Zone(s) so that all resources can resolve e.g. private endpoints through Azure DNS. This is because not all customers want or need a custom DNS server or DNS Private Resolver, for example when there's no connectivity with on-premises.

From what I understand when reading the CAF article you linked, is that only the hub VNet (or a shared services VNet in case of VWAN) should be linked to the Private DNS Zone(s) and that a custom DNS server of DNS Private Resolver should be used as a DNS forwarder for these zones. Each spoke then needs to use those DNS forwarders as DNS server, removing the requirement of linking each Private DNS Zone to each spoke.

**Comment by jtracey93** [comment]
Hey @stijn-geselle-arxus,

So do you have a requirement that requires "corporate" connectivity and therefore centralised DNS but not using any custom DNS services, like ADDS etc.,?

And therefore you want to stick with using Azure DNS natively and just link the private DNS zones to all VNets?

**Comment by stijn-geselle-arxus** [comment]
Hi Jack, 

Yes indeed. This flexibility would enable us to handle all types of customers, since not all of them have an ADDS environment and/or do not need a custom DNS solution. Some of our customers are cloud-only without any on-premise connectivity where the native Azure DNS suffices.

**Comment by JamJarchitect** [comment]
PR is in and ready for review for this feature:
