### ISSUE TITLE
💡 Feature Request - Add in additional parameter for vWAN virtual hub routing preference

### ISSUE THREAD

**Issue by gerrynicol** [Azure/ALZ-Bicep#451]
[AB#26742](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/26742)

Hi Team,
Please could the vWAN bicep module (/infra-as-code/bicep/modules/vwanConnectivity) have a parameter included for hub routing preference as per the document below.

https://learn.microsoft.com/en-us/azure/virtual-wan/howto-virtual-hub-routing-preference

**Comment by jtracey93** [comment]
Thanks @gerrynicol, great ask. I will add to backlog and see if we can sneak in alongside the other vWAN update we have in progress.

Thanks

Jack
