### ISSUE TITLE
💡 Management Group ID Suffix Support

### ISSUE THREAD

**Issue by KevinRabun** [Azure/ALZ-Bicep#452]
## Describe the solution you'd like

[AB#26777](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/26777)

It would be useful to be able to provide a naming suffix for management group IDs that behaves the same that the current prefix does. This would allow for more configurability to meet naming convention standards for various ALZ consumers. The goal would be to provide a suffix as an optional parameter that would be added to the end of management group ID names. The suffix should start with a '-' but if a suffix is not provided then no trailing '-' would be visible.

## Describe alternatives you've considered

As this is to do with ALZ management group naming an alternative has not been considered.

**Comment by jtracey93** [comment]
Thanks @KevinRabun and for discussing this with me over teams. 

@jamjarchitect can you please add this as a feature and user story to ADO?

**Comment by JamJarchitect** [comment]
This has since been created as a feature and story in ADO.
