### ISSUE TITLE
❓👂 Question/Feedback - Deprecated Default Policy

### ISSUE THREAD

**Issue by awoodsimpson** [Azure/ALZ-Bicep#454]
Hi,

In the alzDefaults the following policy is deprecated: [Deprecated]: Configure diagnostic settings for storage accounts to Log Analytics workspace (/providers/Microsoft.Authorization/policyDefinitions/6f8f98a4-f108-47cb-8e98-91a0d85cd474) and needs updating to this one: /providers/Microsoft.Authorization/policyDefinitions/59759c62-9a22-4cdf-ae64-074495983fef

I've tried doing it myself but the Initiative doesn't appear to update, could someone assist?

Thanks

**Comment by jtracey93** [comment]
Hey @awoodsimpson,

We fixed this upstream in the ESLZ repo here https://github.com/Azure/Enterprise-Scale/issues/1034 we just are yet to pull this in and cut a release for ALZ-Bicep.

We will be cutting one before the end of February and this will include the update initiative and definitions

**Comment by awoodsimpson** [comment]
> Hey @awoodsimpson,
> 
> We fixed this upstream in the ESLZ repo here [Azure/Enterprise-Scale#1034](https://github.com/Azure/Enterprise-Scale/issues/1034) we just are yet to pull this in and cut a release for ALZ-Bicep.
> 
> We will be cutting one before the end of February and this will include the update initiative and definitions

Thanks @jtracey93

**Comment by jtracey93** [comment]
This will be out out in release v0.13.0 which will be out today
