### ISSUE TITLE
Grant 'Owner' to root not only in case of Service Principal, but in case of every identity

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#458]
The documentation implies, granting Owner to `/` is only necessary, if you are working with a Service Principal. But the following instruction is required for every identity, that wants to deploy on tenant scope. Am I wrong?
https://github.com/Azure/ALZ-Bicep/blob/13303cdf0f9ff5f49e79442347461c23ebde3d5b/docs/wiki/DeploymentFlow.md?plain=1#L96

It would have saved me some time, if it was mentioned under 'Deployment Identity' as well. I ask you to put this Link:  
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-tenant?tabs=azure-cli#required-access  
e.g. on Line 86. Because granting Owner to `/` to my Deployment-Admin user seems to be necessary as well.

**Comment by jtracey93** [comment]
Hey @baartch,

Thanks for raising the issue and sorry you ran into this.

You are correct it doesn't matter what type of identity you are using you need Owner at `/` for some of the deployments.

Would you be willing to submit a PR to update this wiki page with how you would of liked to of found it. It's as simple as just editing the page in the browser by clicking on this link: https://github.com/Azure/ALZ-Bicep/edit/main/docs/wiki/DeploymentFlow.md 

And then just create a new branch and propose the changes in a PR, which the edit process will walk you through, and we can then review and merge it if all good 👍

Let us know if you wont be able to and we will put on the backlog to solve, but would be awesome to have you contribute 👍👍

Thanks

Jack
