### ISSUE TITLE
Orchestration - mgDiagSettingsAll error - InvalidAuthenticationToken

### ISSUE THREAD

**Issue by cyb3n3tic** [Azure/ALZ-Bicep#465]
Hi,

I'm sure this is something I have done however I am carefully stepping through deployment and have run into the following error when running Module: Orchestration - mgDiagSettingsAll

I have edited mgDiagSettingsAll.parameters.all.json to include the management subscription for parLogAnalyticsWorkspaceResourceId then run the powershell script, the error I get is:

The deployment 'mgDiagSettingsAll' failed with error(s). Showing 3 out of 20 error(s).
Status Message:  (Code:InvalidAuthenticationToken)
Status Message:  (Code:InvalidAuthenticationToken)
Status Message:  (Code:InvalidAuthenticationToken)
CorrelationId: e0647abe-8048-4690-9d71-ab48135e20e0

Any ideas please? All good until I reached this point.

**Comment by jtracey93** [comment]
Hey @cyb3n3tic,

Thanks for the issue.

How are you deploying this? Via Az PowerShell or Az CLI? 

Whatever you are using, have you tried logging out and back in to refresh the tokens? Also have you tried just re-running it after a short wait as the RBAC may not of inherited down the scopes if trying to do this super quick?

Let us know

**Comment by cyb3n3tic** [comment]
Hi,

I'm using PowerShell within cloudshell. I have just tried logging out of the portal and back in again but still getting the same error, most odd.

How can I set the deployment debug log level, assuming that would give more insight into the error?

Cheers

**Comment by jtracey93** [comment]
Hey @cyb3n3tic,

add `-verbose` or `-debug` to the end of the `new-azdeploy....` command. (probably debug)

Have you check RBAC on the LAW and management groups?

**Comment by cyb3n3tic** [comment]
Thanks. I will run with debug and check RBAC - will reply here whatever the outcome

**Comment by cyb3n3tic** [comment]
Most frustrating, I stepped through with debug and see running/success all the way until the end when I recieve the same InvalidAuthenticationToken status message and failed provisioning status output. Nothing really useful from debug or verbose that I could make out tbh.

I have tried a different browser to try to rule out refresh tokens as the cause, same error.
I briefly thought I had spotted the issue with the LAW resource ID but with that corrected still the same error.

Looking at the deployment I see a successful operation for pid-xxxxxx but above that toLa failed with a status of Conflict, Status message is just the InvalidAuthenticationToken code and no message detail.

The account is owner at root of all resources, I assume that having worked through deployment steps 1 - 4 that RBAC is as required for 4.1.

Appreciate any other ideas
[deployment_operations.txt](https://github.com/Azure/ALZ-Bicep/files/10859952/deployment_operations.txt)

**Comment by jtracey93** [comment]
Hey @cyb3n3tic,

Sorry you are having issues, our automated tests passed for this module and I have just manually deployed myself and all works okay.
![image](https://user-images.githubusercontent.com/41163455/222121214-02618893-1b81-4017-ad2f-59c2215405ce.png)

I deployed the following modules in this order:

1. Management Groups
2. Subscription Placement All - moved a sub into the Management Management Group
3. Logging 
4. Management Group Diagnostic Settings

> All done from CloudShell and using PowerShell with my user account that has Owner at `/` scope

A couple of questions from me:

1. Have you moved the subscription that holds the Log Analytics Workspace into the ALZ hierarchy of management groups? (not that this should matter)
2. Did you update the parameter files for the Management Group Diagnostic Settings module and specifically the parameter called `parLogAnalyticsWorkspaceResourceId` to have a value that looks something like this `/subscriptions/10fa35d3-18aa-414a-945c-e5f613c7d503/resourcegroups/rg-alz-logging-001/providers/microsoft.operationalinsights/workspaces/alz-log-analytics`
3. Have you tried doing it from CloudShell yourself, just to rule out a local client issue?

Let me know

Thanks

Jack

**Comment by cyb3n3tic** [comment]
Thanks Jack, appreciate the continued support.
I have been sticking with the order as shown in the Module Deployment Sequence, so
1 	Management Groups
2 	Custom Policy Definitions
3 	Custom Role Definitions
4 	Logging & Sentinel
4.1 	Management Groups Diagnostic Settings - where I am currently stuck.

I have just tried manually moving the management subscription to the ALZ location but having done so still no joy. I'm doing all this in CloudShell in the portal.

This is a demo/testing environment so other than being mindful of overspend (I'm looking at you DDoS protection plan!) there is no restriction. In a Youtube session one time you mentioned a script to blow away a landing zone, would you be able to share that so I can start again perhaps? I imagine I can just delete the little deployed so far unless you think the script would be the better option?

Cheers

**Comment by cyb3n3tic** [comment]
And sorry, yes, I have updated the parLogAnalyticsWorkspaceResourceId parameter

**Comment by cyb3n3tic** [comment]
I have just tried from local client instead and seeing the exact same result. I'm baffled!

**Comment by jtracey93** [comment]
Sorry was in meetings. My cleanup/wipe script for ALZ can be found here: https://github.com/jtracey93/PublicScripts/tree/master/Azure/PowerShell/Enterprise-scale (please read the README.md fully to understand what it will do etc. we take no responsibility for what it does)

Clean it up and then perhaps re-deploy and let us know. Alos might be worth checking your Az PowerShell module is up-to-date in cloudshell by using the comand `get-module -Name "Az" -ListAvailable` to check the current version (should be 9.4.0) and then updating if not by following https://learn.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-9.4.0#update-the-azure-powershell-module

If no luck we can look to setup a call to investigate further 👍

Keep us posted

**Comment by cyb3n3tic** [comment]
Much appreciated, starting the clean up now and will start again. I will let you know.

**Comment by cyb3n3tic** [comment]
Thanks for the offer but let's close this for now, if I run in to the same issue on my next attempt I'll see if the offer still stands.

Appreciate the great work you are doing here.

**Comment by cyb3n3tic** [comment]
Thanks again, problem certainly my end I'm sure - gremlin snuck in somewhere along the line!
