### ISSUE TITLE
Policy Assignment - Deny Public IP (depreciated) - fails on deployment

### ISSUE THREAD

**Issue by jon-mca** [Azure/ALZ-Bicep#467]
Hi,

Apologies if this has been raised elsewhere, I'm getting deployment failures with the most recent release (0.13.0) where Azure is trying to update a policy definition assignment called Deny-PublicIP.

I initially raised this with Microsoft Support and have told me that the Deny-PublicIP definition has been depreciated and to not include this definition during deployment, they state this:
**_Thank you for your patience on this case.
I have got some feedback I would like to share with you based on our findings with a technical advisor for this service.
So, it appears that the policy (Deny-PublicIP) you are trying to modify has deprecated. Kindly make sure you don't include that policy in the deployment._**

I couldn't see a way to disable / skip deploying this policy definition so to workaround this, I've created a fork and commented out the policy definition assignment in question which has unblocked the deployments on my side:
[https://github.com/peppercorninsurance/ALZ-Bicep](https://github.com/peppercorninsurance/ALZ-Bicep)

The commit done on our fork:
https://github.com/peppercorninsurance/ALZ-Bicep/commit/a8a5db1431372ca0329aeea4160b286c750e191a

**The error that is thrown**
`ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n        \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.\\\",\\r\\n        \\\"details\\\": [\\r\\n          {\\r\\n            \\\"code\\\": \\\"BadRequest\\\",\\r\\n            \\\"message\\\": \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"InvalidPolicyDefinitionIdUpdate\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The policy assignment 'Deny-Public-IP' create request is invalid. Cannot update existing assignment's policy definition '/providers/Microsoft.Management/managementGroups/pcai/providers/Microsoft.Authorization/policyDefinitions/Deny-PublicIP' with new policy definition '/providers/Microsoft.Authorization/policyDefinitions/6c112d4e-5bc7-47ae-a041-ea2d9dccd749'.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}`

**Reproduction**
Run a bicep file against a tenant that includes something similar to the following:
```
targetScope = 'tenant'

// INFO: treat these as variables for the benefit of reproducing the issue
var parDdosProtectionPlanId = ''
var parAutomationAccountName = 'pcai-automation-account'
var parTopLevelManagementGroupPrefix = 'pcai'
var parLocation = 'northeurope'
var parLogAnalyticsWorkspaceLogRetentionInDays = 365
var parTelemetryOptOut = true

// INFO: not the actual email, replace with something more suitable.
var parMsDefenderForCloudEmailSecurityContact = 'john.doe@example.com'

// INFO: not an actual ID, replace with an actual ID.
var modLogging.outputs.outLogAnalyticsWorkspaceId = 'SomeExampleWorkspaceId'

module modPolicyAssignments 'path/to/ALZ-Bicep/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep' = {
  scope: managementGroup(parTopLevelManagementGroupPrefix)
  name: 'alz-policy-assignments'
  params: {
    parDdosProtectionPlanId: parDdosProtectionPlanId
    parAutomationAccountName: parAutomationAccountName
    parTopLevelManagementGroupPrefix: parTopLevelManagementGroupPrefix
    parLogAnalyticsWorkSpaceAndAutomationAccountLocation: parLocation
    parLogAnalyticsWorkspaceLogRetentionInDays: '${parLogAnalyticsWorkspaceLogRetentionInDays}'
    parLogAnalyticsWorkspaceResourceId: modLogging.outputs.outLogAnalyticsWorkspaceId
    parMsDefenderForCloudEmailSecurityContact: parMsDefenderForCloudEmailSecurityContact
    parTelemetryOptOut: parTelemetryOptOut
  }
}
```

Happy to provide further details.

Thanks for your time!

**Comment by jtracey93** [comment]
Hey @jon-mca,

Thanks for raising the bug.

We actually made the change to this `Deny-Public-IP` assignment back in [`v0.12.0`](https://github.com/Azure/ALZ-Bicep/releases/tag/v0.12.0) where we provided details on how to handle this upgrade to that version there, which still applies today if you weren't on `v0.12.0` already.

![image](https://user-images.githubusercontent.com/41163455/222774096-b8468e74-ad1d-4e28-b08e-193c3dfbae56.png)

As the breaking change states, you will need to remove the assignment for `Deny-Public-IP` from the `corp` and `identity` Management Groups and then you will be able to use the `alzDefaultPolicyAssignments.bicep` module from `v0.13.0` (or `v0.12.0`) to make the new assignment of the non-deprecated policy definition of https://www.azadvertizer.net/azpolicyadvertizer/6c112d4e-5bc7-47ae-a041-ea2d9dccd749.html

We also have this process documented here https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive#how-to-migrate-alz-custom-policies-to-azure-built-in-policies

Please can you review the docs and follow the steps mentioned in them and let us know that you have resolved this?

Let us know

Thanks

Jack

**Comment by jon-mca** [comment]
Hi @jtracey93,

My apologies, I obviously overlooked that and will do as you suggest. Thanks for pointing that out.

I'll get this sorted out and let you know how it goes.

Thanks again

**Comment by jon-mca** [comment]
Marking as closed, will get around to this when I get time.
