### ISSUE TITLE
❓Need guidance to customize "managementGroups.bicep" in case I need to add 5 to 6 sub-child management groups under both of the child management groups named "'ashtechie-internalaccess' and 'ashtechie-externalaccess'.

### ISSUE THREAD

**Issue by AshTechieDevOps** [Azure/ALZ-Bicep#469]
I was successfully able to customize   "managementGroups.bicep" as per my requirements, however still need guidance  to customize "managementGroups.bicep" in case I need to add 5 to 6 sub-child management groups under both of the child management groups named "'ashtechie-internalaccess' and 'ashtechie-externalaccess' as shown in below.

// Landing Zones & Child Management Groups
var varLandingZoneMg = {
  name: '${parTopLevelManagementGroupPrefix}-landingzones${parTopLevelManagementGroupSuffix}'
  displayName: 'ashtechie-landingzones'
}

// Used if parLandingZoneMgAlzDefaultsEnable == true
var varLandingZoneMgChildrenAlzDefault = {
  internalaccess: {
    displayName: 'ashtechie-internalaccess'
  }
  externalaccess: {
    displayName: 'ashtechie-externalaccess'
  }
}

**Comment by jtracey93** [comment]
Hey @AshTechieDevOps,

Have you reviewed our guidance and recommendations in https://aka.ms/alz/tailoring on how you should tailoring your ALZ Management Groups.

It sounds like what you are trying to do is actually not what we recommend and this is why it is not enabled in the modules easily as you will also need to change a lot of other modules, like `mgDiagSettingsAll`, `subPlacementAll` etc..

If you wish to still customize like this, against our recommendations, then you will need to amend the various modules to support the different hierarchy.

You may find it easier to add then management groups to a "level 4" section and potential loop based on using some of the code for how we do "level 3":

https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep#L199-L211

However you may find it easier to just add the management groups manually and "hardcode" them depending on your bicep experience level. The only property that is important to build your hierarchy is `properties.details.parent.id` which should be set the the ID of the management group you want the new management group to be created under.

A brief example below:

```bicep
resource mg1 'Microsoft.Management/managementGroups@2021-04-01' = {
  name: 'mg1'
  properties: {
    displayName: 'Level 4 MG 1'
    details: {
      parent: {
        id: '/providers/Microsoft.Management/managementGroups/ashtechie-landingzones-internalaccess'
      }
    }
  }
}

resource mg2 'Microsoft.Management/managementGroups@2021-04-01' = {
  name: 'mg2'
  properties: {
    displayName: 'Level 4 MG 2'
    details: {
      parent: {
        id: '/providers/Microsoft.Management/managementGroups/ashtechie-landingzones-externalaccess'
      }
    }
  }
}

resource mg3 'Microsoft.Management/managementGroups@2021-04-01' = {
  name: 'mg3'
  properties: {
    displayName: 'Level 5 MG 3'
    details: {
      parent: {
        id: mg2.id
      }
    }
  }
}
```

But as this is not a recommended approach in ALZ, as per our tailoring guidance we will not provide support or add this to the module at this time. Please feel free to create a feature request as a new issue with detail on the "why" this is required to help us understand the design and requirement.

Thanks

Jack
