### ISSUE TITLE
❓👂 Question/Feedback - Azure Landing Zones Bicep - Deployment Flow - Virtual WAN

### ISSUE THREAD

**Issue by SteveWalker77** [Azure/ALZ-Bicep#475]
## Question/Feedback

I am currently working through the Azure Landing Zones Bicep - Deployment Flow module deployment sequence, and I am at module number 5 (Hub Networking).  

I am trying to deploy the virtual WAN using option 1 - Using Orchestration Module
1. Virtual WAN Connectivity

Each time I attempt to deploy this I get the following error:
![Screenshot](https://user-images.githubusercontent.com/98813833/224745213-3e1ea159-d2c6-4dbb-bf3f-cf69ebdc213f.png)

I am new to Bicep so any pointers would be greatly received.

**Comment by jtracey93** [comment]
Hey @SteveWalker77,

Thanks for raising. Could you please go into the resource group `rg-alz-vwan-001` and drill into the failed deployment for more information and try and find the failing resource. 

> Instructions on how here: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#resource-group-deployments

Can you also confirm you update the values to the correct values, based on your deployment, in the [`vwanConnectivity.parameters.all.json` file](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json)

Let us know

Thanks

Jack

**Comment by SteveWalker77** [comment]
It seems that I have a failed deployment 'deploy-Private-DNS-Zones'.

![image](https://user-images.githubusercontent.com/98813833/224772710-e4ed5e85-624b-442f-8e21-248d6045db8c.png)

When I drill into the operation details, I can see the status message:

{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Virtual network resource not found for '/subscriptions/subscriptionremoved/resourceGroups/HUB_Networking_POC/providers/Microsoft.Network/virtualNetworks/alz-hub-uksouth'"
    }
}

**Comment by jtracey93** [comment]
Thanks for digging in here @SteveWalker77, did you update the [`parVirtualNetworkIdToLink` parameter](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md#parvirtualnetworkidtolink) in the parameters file for the module? 

https://github.com/Azure/ALZ-Bicep/blob/c3423b445e030d5046ed057b5d15a559a324d9c6/infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json#L150

**Comment by SteveWalker77** [comment]
I currently have this in my vwanConnectivity.parameters.all.json file:

  "parVirtualNetworkIdToLink": {
      "value": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/HUB_Networking_POC/providers/Microsoft.Network/virtualNetworks/alz-hub-uksouth"
    },

**Comment by jtracey93** [comment]
Hi @SteveWalker77, this is incorrect. You need to update this with the resource ID of a virtual network that you want to link all the created private DNS Zones too. 

As a Virtual WAN Hub cannot be linked to Private DNS Zones directly today.

Please update this value and re-deploy and it should work for you. Or you can set the value to `""` (aka empty) and we will not create the link for you and this should also make it succeed

**Comment by SteveWalker77** [comment]
**@jtracey93** I changed the vwanConnectivity.parameters.all.json file and set the value to be empty as you suggested.  This has allowed the deployment to complete.

"parVirtualNetworkIdToLink": {
      "value": ""
      
Will the linking of Private DNS Zones directly to the Virtual WAN Hub be an option in the future?

**Comment by jtracey93** [comment]
Awesome stuff @SteveWalker77.

As for the Private DNS Zones and a virtual WAN Hub, please raise that as a feedback request here for the Product Team/Group: https://feedback.azure.com/d365community

I will now close this issue as resolved

**Comment by SteveWalker77** [comment]
Thanks for all your support Jack.
