### ISSUE TITLE
Support peering existing VNets

### ISSUE THREAD

**Issue by gbeaud** [Azure/ALZ-Bicep#477]
## Describe the solution you'd like

- Deploying the module on existing VNets overwrites existing subnets, which is not idempotent despite ARM's theoretical behavior
- This module can only be used once per VNet, as the next time it is run, it will overwrite subnets. This is a limitation since we may like to deploy it again to apply modifications later (e.g. changing the range). The way it is built only supports a one-off deployment for new VNets and then forces users to use another method for further modifications and management.
- I wish I could use this module to capture and manage my entire network:
1. A parameter file would have a list/dictionary to capture all Vnets with their name, range, some settings etc...
2. The code would iterate over the Vnets, and if the Vnet already exists, it doesn't recreate the VNet (which would overwrite the subnets), but simply applies the settings and peering to hub
3. If the VNet described doesn't exist, then it creates it like it's already doing today

## Describe alternatives you've considered

- I wish I could code this logic myself in a main.bicep that is calling your modules but the problem is that your module overwrites subnets in any case so we need to modify the module to make it work as I can't just modify this behavior from a main.bicep
- I'm happy to propose modifications and make a pull request to implement my suggestions but let me know beforehand if you validate the approach
- Key challenge: how to test if a resource exists or not in Bicep? (We don't want the user to give a bool parameter for existence)

## Additional context

![image](https://user-images.githubusercontent.com/79973892/226292031-0f73590b-5d84-4f50-837b-c94151752039.png)

**Comment by gbeaud** [comment]
Thanks Jack for the quick feedback! I posted a comment in the issue you shared to emphasize its importance 👍

Well my best guess, given the limitations, would be to add a "newVNet" bool parameter, which the user would set to true when deploying a new VNet and to false for further management. In the module we would check for this parameter: if true it creates the VNet, if false it uses a "existing" resource type to perform modifications like peering etc...

Limitations:
- Not dynamic (doesn't update automatically)
- Puts the burden on the user 
- We lose some functionality by using an existing resource, right? (I guess we can still do the peering but not change the range and other settings, right?)

On the other hand it would be a one-off setting so not very cumbersome for the user: each new deployment starts with a "true" and then ongoing operations continue with "false" - just one parameter to change once.

Let me know your thought 😊
Cheers
Guillaume

**Comment by jtracey93** [comment]
Thanks @gbeaud for coming back here. 

What about the idea of a deployment script that takes away the need for a new param as we can handle the logic there?

Let me know

**Comment by csaba-almasi** [comment]
> Thanks @gbeaud for coming back here.
> 
> What about the idea of a deployment script that takes away the need for a new param as we can handle the logic there?
> 
> Let me know

This would be very welcome for our setup as well, currently implementing the workaround using this approach

**Comment by jtracey93** [comment]
We are likely to hold off on this for a few months as this may be on the road to being fixed properly in the network RP.

**Comment by csaba-almasi** [comment]
> We are likely to hold off on this for a few months as this may be on the road to being fixed properly in the network RP.

No offense @jtracey93 since it's not this team's responsibility but that issue has been known for almost 7 years now and still no resolution to it.

**Comment by jtracey93** [comment]
I hear you, and no offense taken. It's hurt me too for that long.

But I have faith as have been pushing for this internally and its looking positive

**Comment by JimmyKarlsson112** [comment]
Any updates on this from Network RP team?

**Comment by oZakari** [comment]
Closing this as virtual networks can now be updated without modifying associated subnets. This is capable as of API version 2023-09-01 and ALZ-Bicep is currently set to 2024-01-01. Please see this [blog ](https://techcommunity.microsoft.com/blog/azurenetworkingblog/azure-virtual-network-now-supports-updates-without-subnet-property/4067952)for additional info. Note, the virtual network module we will be transitioning to for AVM also takes this change into account.
