### ISSUE TITLE
Initiative "Enable Azure Monitor for VMs" has been marked as legacy, should the code be updated to use "[Preview]: Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)"?

### ISSUE THREAD

**Issue by vladimirs-davidovs** [Azure/ALZ-Bicep#484]
## Question/Feedback

In "\infra-as-code\bicep\modules\policy\assignments\alzDefaults\alzDefaultPolicyAssignments.bicep" there is an assignment of the "Enable Azure Monitor for VMs" initiative with the following definition Id "/providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a". Currently the initiative is marked as legacy, and the description says "Legacy - Enable Azure Monitor for the virtual machines (VMs) in the specified scope (management group, subscription or resource group). Takes Log Analytics workspace as parameter. Use the new initiative named: **Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)**". Initiative seems to be actually named "**[Preview]: Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)**" and has a definition Id of "/providers/Microsoft.Authorization/policySetDefinitions/9dffaf29-5905-4145-883c-957eb442c226". 
Should "alzDefaultPolicyAssignments.bicep" code be updated to replace the Legacy initiative with the new one?

## Possible Answers/Solutions?

Update "alzDefaultPolicyAssignments.bicep" code to replace the Legacy initiative "/providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a" with the new one "/providers/Microsoft.Authorization/policySetDefinitions/9dffaf29-5905-4145-883c-957eb442c226".

**Comment by jtracey93** [comment]
Hey @vladimirs-davidovs, Thanks for the issue and ask.

We are actually tracking this ask upstream in the Enterprise Scale repo, where all the policies source of truth is 👍

You can see this in issue: https://github.com/Azure/Enterprise-Scale/issues/1055

We have this on our backlog and are working with the AMA PG teams to get this work done for ALZ however, we do not believe AMA is yet ready, with all the dependencies, to make migrating ALZ to AMA just yet the right move. But we will do it, once everything is aligned and ready. Myself and Paul were even on a call late into the evening yesterday with the PG discussing this, so its top of mind; rest assured.

I will close this issue and invite you to follow the issue above in our upstream ESLZ repo.

Thanks

Jack
