### ISSUE TITLE
❓👂 Question/Feedback - Missing policies from Enterprise Scale repo?

### ISSUE THREAD

**Issue by MarcoJanse** [Azure/ALZ-Bicep#491]
## Question/Feedback

After deploying the Policy definitions and the ALZ-defaults module, I seem to be missing policies from the [ALZ-Policies | Enterprise Scale Repo](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#what-policy-definitions-are-assigned-within-the-azure-landing-zones-custom--built-in).  For example, at the [Intermediate Root](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#intermediate-root), there should be a policy assignment called ***Audit-UnusedResourcesCostOptimization***.  This is a custom policy set definition and I can find it in the Enterprise Scale repo here: [https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Audit-UnusedResourcesCostOptimization.json](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Audit-UnusedResourcesCostOptimization.json). I understood that the ALZ-Bicep repo syncs these policy definitions using GitHub action. However, if I look at [https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_set_definitions](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_set_definitions), there is only a handful of policy definitions there and most commits are more than two months old. Am I missing something?

## Possible Answers/Solutions?

I reviewed the codeTour `upstreamPolicyUpdateProcess.tour` in the repo and read the [https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive](https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive), but I can't quite grasp why there is a difference between them. 

I'm proabaly missing something, so any help would be highly appreciated. 
Also, keep up the good work with this fantastic repository! :thumbsup:

**Comment by jtracey93** [comment]
Hey @MarcoJanse,

This is because we haven't updated the policies yet in ALZ Bicep or ALZ Terraform. We are working on this in this sprint, this month, and hope to have out soon. 

So stay tuned 👍👍
