### ISSUE TITLE
❓👂 Question/Feedback - add info in consumer guide wiki in regards to forking and release tagging

### ISSUE THREAD

**Issue by MarcoJanse** [Azure/ALZ-Bicep#492]
## Question/Feedback

I'm consuming the ALZ-Bicep repo by forking it. I noticed that tags are not being synced when forking a repo. This is default behaviour I think, but it raises the question how to consume this properly by forking as the tags are being used for release versions.

## Possible Answers/Solutions?

As the tags are being used for release versions, I would assume you should also sync the tags when forking and checkout/create a working branch based on the latest official release? 

The issue might be primarily my lack of Git basics knowledge, but then again, I might not be the only one struggling with this, so some clarification in the consumer guide could be beneficial.

Keep up the good work with this amazing repository! 👍

**Comment by jtracey93** [comment]
Hey @MarcoJanse,

Thanks for raising this issue/question. 

We are very close to releasing our updated guidance on how to consume ALZ Bicep in a more prescriptive and structured way with a reference architecture and directory layout, including pipelines etc. this is something we have been calling "the ALZ Bicep Accelerator". 

We hope to have it wrapped up and available for consumption by the end of this month. 

Looping in @oZakari who is leading this effort and currently updating docs, so he can add this one to his list to update with the accelerators release 👍

**Comment by jtracey93** [comment]
The accelerator is now live. Checkout the wiki
