### ISSUE TITLE
❓👂 Question/Feedback - Update Accelerator wiki page to include custom parameters

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/ALZ-Bicep#504]
## Question/Feedback

Update the wiki page to call out that you may have to update the parameters files in config/custom-parameters or at least certainly review them before running.

This is not clear and could lead to someone just running it with undesired configurations.

## Possible Answers/Solutions?

A simple call out would be enough, making sure they know to review them.

**Comment by jtracey93** [comment]
Hey @MilesCameron-DMs, is this on the deployment flow page or on each module `README` or both?

Give us some suggestions 👍 Also if you want to contribute via a PR, we'd really appreciate it (plus you get your name on the repo contributors list, whats not to love?)

Let us know

Thanks

Jack

**Comment by MilesCameron-DMs** [comment]
Hey @jtracey93 - thanks for getting back to me so promptly.

Its on the Accelerator page:

https://github.com/Azure/ALZ-Bicep/wiki/Accelerator

I will create a PR 👍

**Comment by jtracey93** [comment]
Hey @MilesCameron-DMs, hold fire. We are just about to pull that page as we aren't quite ready yet.

@oZakari will take onboard the feedback for when we re-release the content, in the coming days!
