### ISSUE TITLE
❓👂 Question/Feedback - Update Accelerator wiki page with more information on Get-ALZGithubRelease

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/ALZ-Bicep#505]
## Question/Feedback

The wiki page https://github.com/Azure/ALZ-Bicep/wiki/Accelerator#upgrading-alz-bicep-versions mentions Get-ALZGithubRelease but this is not a cmdlet included in the module and needs to be loaded separately:

![image](https://user-images.githubusercontent.com/78753426/234062301-26f47825-e75a-49f5-8bf6-e2a297731f97.png)

This is mentioned on another issue as closed but the wiki article does not mention this and it is not available directly via the module:

https://github.com/Azure/ALZ-PowerShell-Module/issues/46

## Possible Answers/Solutions?

Make it available directly somewhere and/or update the wiki article to make it clearer.

**Comment by jtracey93** [comment]
@oZakari can you advise here please? The function isn't public yet, right as a release of the module needs to be cut?

**Comment by oZakari** [comment]
Hi @MilesCameron-DMs, thanks for letting us know. I didn't mean for the documentation to go live so my apologies on that. We need to cut a new release for the ALZ-PowerShell module as Jack mentioned prior.
