### ISSUE TITLE
Facing issues with new feature PrivateDnsZoneLinkToSpoke

### ISSUE THREAD

**Issue by Sahil-13** [Azure/ALZ-Bicep#517]
## Describe the bug

I am using hubpeeredspoke module to create a spoke and peering and other things, the new feature that performed PrivateDnsZoneLinkToSpoke is throwing an error - 

ERROR: InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Resources/deployments/ALZBicep-modPDnsLinkToSpoke-westeurope-mb5mxrnsifp56-rg' at line '1' and column '19927' is defined multiple times in a template. Please see https://aka.ms/arm-syntax-resources for usage details.'.

## To Reproduce

Steps to reproduce the behaviour:

1. In the hubPeeredSpoke.parameters.all.json paramter files 
2. Added all the resource IDs for private DNS to be linked to spoke vNet 

## Expected behaviour

In an ideal scenario - the vNet link should get created.

**Comment by Sahil-13** [comment]
@jtracey93 Awesome, thank you prompt response.

**Comment by jtracey93** [comment]
@Sahil-13 this is now fixed

**Comment by Sahil-13** [comment]
@jtracey93 Thank you quick resolution. May I please highlight 2 issues I experienced while creating private DNS link. 

1. The deployment failed with error: 'Subscription id: 'subscriptions' does not exist. - I didn't realize this earlier but I found that indice used at split function to reterive subcription Id is incorrect. 
`module modPrivateDnsZoneLinkToSpoke '../../modules/privateDnsZoneLinks/privateDnsZoneLinks.bicep' = [for zones in parPrivateDnsZoneResourceIds: if (!empty(parPrivateDnsZoneResourceIds)) {
  scope: resourceGroup(split(zones, '/')[1], split(zones, '/')[4] )`

it should be 2 instead of 1

`module modPrivateDnsZoneLinkToSpoke '../../modules/privateDnsZoneLinks/privateDnsZoneLinks.bicep' = [for zones in parPrivateDnsZoneResourceIds: if (!empty(parPrivateDnsZoneResourceIds)) {
  scope: resourceGroup(split(zones, '/')[2], split(zones, '/')[4] )`

2. After this fix the deployment started running but it took approx 33 minutes and failed with error message - `"message":"The aggregated deployment error is too large. Please list deployment operations to get the deployment details.` which could be possible because I had passed around 68 Private DNS resource IDs to perform DNSlink. To investigate further, when I check the deployments in the resource group, I see errors with some links worked and some did not failed with error "conflict" - for example sharing this one of many correlation id - b07632c9-8d7b-467d-8dac-f7a0e08c3dc5. 

But interesting thing is - all DNS link for all 68 private DNS zone resource IDs was successfully established when I checked in the portal. 

Not sure if this is expected due to parallel deployment.

**Comment by jtracey93** [comment]
Hey @Sahil-13,

Thanks for spotting have raised a new bug in #519 to track this, already have the fix and testing

**Comment by jtracey93** [comment]
@Sahil-13 #519 has been fixed and i tested :) in the PR #520

**Comment by Sahil-13** [comment]
@jtracey93 thanks a lot, the fix worked like a charm!
