### ISSUE TITLE
Azure DevOps Pipeline Step "Az CLI Deploy Role Assignment" failed

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ALZ-Bicep#528]
## Question/Feedback

Error message.

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/providers/Microsoft.Management/managementGroups/alz-platform/providers/Microsoft.Resources/deployments/create_role_assignment-20230516.1","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidRoleAssignmentId","message":"The role assignment ID 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not valid. The role assignment ID must be a GUID."}]}}

## Possible Answers/Solutions?

Checked       inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep \
        --parameters @infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroup.servicePrincipal.parameters.all.json \
        --location $(Location) \
        --management-group-id $(RoleAssignmentManagementGroupId) \
        --name create_role_assignment-$(RunNumber)

Then checked roleAssignmentManagementGroup.servicePrincipal.parameters.all.json:
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "parRoleAssignmentNameGuid": {
      "value": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    },
    "parRoleDefinitionId": {
      "value": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    },
    "parAssigneePrincipalType": {
      "value": "ServicePrincipal"
    },
    "parAssigneeObjectId": {
      "value": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    },
    "parTelemetryOptOut": {
      "value": false
    }
  }
}

Can you please how to get the proper value for these?

**Comment by picccard** [comment]
> This module provides role assignment capabilities across Management Group & Subscription scopes. Role assignments are part of [Identity and Access Management (IAM)](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/identity-and-access-management), which is one of the critical design areas in Enterprise-Scale Architecture. 


I think you should have a look at these docs. The parameters for this module is unique for your environment.

- [https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/roleAssignments](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/roleAssignments)
- [https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentManagementGroup.bicep.md](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentManagementGroup.bicep.md)

**Comment by jamesyoung007** [comment]
Thanks the docs helped. 
Not sure this should be a new issue, but I am going to ask here, if it is required to log a new issue, please advise.
I updated the parameter file with unique values, I rerun the pipeline, and it failed with error messages:
ERROR: {"error":{"code":"DeploymentNotFound","message":"Deployment 'create_hub_network_rg-20230516.5' could not be found."}}
So I had to delete resource group Hub_Networking_POC and try it again, which will proceed.
IaC's idempotent feature should allow it to be rerun without having to remove resources, right?

**Comment by picccard** [comment]
Ok so I assume you are trying to deploy the azure-pipeline from here [/wiki/PipelinesADO](https://github.com/Azure/ALZ-Bicep/wiki/PipelinesADO)?

Since the doc marks the pipeline as a _sample_, I've never used it as a single pipeline with _all_ the steps, I've only used it as a blueprint for my own pipelines. I've split the pipeline into multiple pipelines, one for each module. That allowed me to experiment with each module at the time and get to know it.

Have a look at the DeploymentFlow of the modules [here](https://github.com/Azure/ALZ-Bicep/wiki/DeploymentFlow#high-level-deployment-flow)

I'm unsure why you got that error, but I can see from the name create hub network rg, that is has to do with the deployment of the hub-resourcegroup, and not from the roleAssignment-module as your first post did.

And Yes, the modules in ALZ-Bicep allows you to redeploy again and again and only see incremental changes on the infra (idempotent, yes)

**Comment by jamesyoung007** [comment]
Thank you very much, I was doing a quick test, I will split them up as well, much appreciated!

**Comment by jamesyoung007** [comment]
On the doc, it shows parRoleAssignmentNameGuid is not required, but the pipeline task failed when its value was not provided.

**Comment by jamesyoung007** [comment]
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/providers/Microsoft.Management/managementGroups/alz-platform/providers/Microsoft.Resources/deployments/create_role_assignment-20230517.1","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidRoleAssignmentId","message":"The role assignment ID '[guid(managementGroup().name, parameters('parRoleDefinitionId'), parameters('parAssigneeObjectId'))]' is not valid. The role assignment ID must be a GUID."}]}}

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "parRoleAssignmentNameGuid": {
      "value": "[guid(managementGroup().name, parameters('parRoleDefinitionId'), parameters('parAssigneeObjectId'))]"
    },
    "parRoleDefinitionId": {
      "value": "c41da26f-f3a2-5cbb-a127-bf227b054afa"
    },
    "parAssigneePrincipalType": {
      "value": "ServicePrincipal"
    },
    "parAssigneeObjectId": {
      "value": "21bca949-8910-49ba-b9f3-17df936335a9"
    },
    "parTelemetryOptOut": {
      "value": false
    }
  }
}

Can you please advise how to get parRoleAssignmentNameGuid's value in our environment?

**Comment by jamesyoung007** [comment]
Another quick update is that wnen these steps in the sample pipeline are split into individual steps, they worked fine and can be run repeatedly.

**Comment by picccard** [comment]
Ok glad it worked when chopped up in smaller pieces.

I will also recommend to check out the new [accelerator folder](https://github.com/Azure/ALZ-Bicep/tree/main/accelerator). That is the direction the project is heading regarding CI/CD. Currently there is only github actions pipelines, but the pipeline-scripts are also usable with Azure Pipeline.

**Comment by jamesyoung007** [comment]
Thanks Eskil, you are so helpful.

**Comment by jamesyoung007** [comment]
I still have two questions:
1. Can you please advise how to get parRoleAssignmentNameGuid's value in our environment?
2. How can we use these pipeline-scripts with Azure Pipeline, is there a sample yaml file for it?

**Comment by jamesyoung007** [comment]
If I test these pipeline-scripts with Azure Pipeline successfully, can I raise Pull Request for you guys to consider?

**Comment by jtracey93** [comment]
> I still have a question:
> 
> 
> 
> Can you please advise how to get parRoleAssignmentNameGuid's value in our environment?

Please remove that parameter from your parameter files. As this value will be automatically generated as a random guid, it's not something you find this one.

**Comment by jamesyoung007** [comment]
Thanks Jack for the quick response, but it failed after I removed parameter from your parameter file: roleAssignmentManagementGroup.servicePrincipal.parameters.all.json

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "parRoleDefinitionId": {
      "value": "c41da26f-1234-1234-a127-bf227b054afa"
    },
    "parAssigneePrincipalType": {
      "value": "ServicePrincipal"
    },
    "parAssigneeObjectId": {
      "value": "21bca949-1234-1234-b9f3-17df936335a9"
    },
    "parTelemetryOptOut": {
      "value": false
    }
  }
}


ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/providers/Microsoft.Management/managementGroups/alz-platform/providers/Microsoft.Resources/deployments/create_role_assignment-20230518.1","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"PrincipalTypeNotSupported","message":"Principals of type Application cannot validly be used in role assignments."}]}}

**Comment by jtracey93** [comment]
@jamesyoung007 how did you find the SPNs object ID as I suspect it is incorrect from this error.

**Comment by jamesyoung007** [comment]
I manually changed some bit, because I don't want to reveal our true id.

**Comment by jtracey93** [comment]
That's fine. The ID I still suspect is wrong based on that error. 

See a similar thread here https://github.com/Azure/terraform-azurerm-appgw-ingress-k8s-cluster/issues/1

**Comment by jamesyoung007** [comment]
This is how I get the client ID:
1. Go to Azure DevOps Project
2. Then go to Service connections.
3. Edit, and copy Service Principal Id.
4. Go back to Azure Portal AAD.
5. Search the Service Principal Id in App registrition.
6. Then copy the object ID instead of Service Principal Id or Application (client) ID.

**Comment by jtracey93** [comment]
Could you try this script instead to find the ID `az ad sp list --filter "displayName eq '<APP_REGISTRATION_NAME>'" --query '[].{name:appDisplayName, objectId:id}'`

Then use the object ID value from here

**Comment by jamesyoung007** [comment]
Thank you so much, Jack, I used the wrong value, with your command, it got the correct ID and I rerun the pipepline, it worked perfect, many thanks.
