### ISSUE TITLE
Azure Firewall Policy Failure after HubNetworking redeploy.

### ISSUE THREAD

**Issue by gin1974** [Azure/ALZ-Bicep#530]
## Describe the bug

HubNetworking.bicep issue with redploy after parameter change to gateway subnet route table

The azure firewall policy changes to provisioning state: Failed

Error below
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"FirewallPolicyUpdateFailed","message":"Put on Firewall Policy "" Failed with 1 faulted referenced firewalls"}]}]}}

## To Reproduce

Steps to reproduce the behaviour:

1. Deploy HubNetworking.bicep with AZ FW & VPN Gateway - All Works
2. Update the Parameter file with Route table id for Gateway subnet
3, RedpeloyHubNetworking.bicep. The gateway subnet has the updated route table associated
4. The Azure FW policy shows fails

## Expected behavior

- Deployment should succeed
- The deployment does succeed if I delete the AZ firewall and policy and redploy.
 
## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Correlation ID

A correlation ID really helps us investigate your issue further. Please provide one if possible. Details on how to find a correlation ID can be found here: [Correlation ID and support](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#correlation-id-and-support)

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by jtracey93** [comment]
@gbeaud we were only chatting about this today, could you share some insights?

**Comment by gbeaud** [comment]
@jtracey93 my observations with Az FW deployments as code:

- There is a native issue in the way the ARM template is created: if you take a running, valid firewall + policy with multiple rule collection groups, extract the ARM template and redeploy as-is, it fails (actually it deploys some resources, typically the firewall + the policy + only 1 rule collection group but reports a failure). You need to redeploy the same template as many times as you have RCGs in the policy, and each deployment will fail but still add a new RCG. I have shared that feedback to PG who has taken it seriously.
- However the error message shared by gin1974 is not the same; the one I had was "policy is in updating state from previous operation". They may or may not be related, I don't know. 
- Sometimes making frequent deployments was blocking the policy, which remained in updating states forever, and I had to ask support to delete if from their side as none of their workaround was working (running GET/PUT to refresh the state)
- The same kind of issues has happened to me when deploying with CARML/ALZ-Bicep, and also when writing my own code from scratch. The first deployment fails, then it works *somehow* ok but remains quite an unreliable process from my experience as it sometimes fails for no understandable reason. A trick I found to reduce errors is to remove the firewall from the deployment, so each deployment only covers the policy (I think this is already part of ALZ-Bicep by using the boolean parameter to include or not the FW - that's helpful!)
- There is an example of FW as code that however does not fail and enables to deploy multiple RCGs at once: [https://github.com/JanneMattila/azure-firewall-demo](url) ; from my researches this is the best example of Az FW as code, and it also proposes a smart way to organize RCGs in folders (hub / on-prem / spoke 1 / spoke 2 ...). This is technically working and also making the operating model easy.

**Comment by jtracey93** [comment]
Thanks @gbeaud 

@gin1974 could you please share a correlation ID for this failed deployment?

Also have you or could you open an Azure support ticket, as we suspect this is actually an issue with the Azure Firewall RP/API and not this module.

Let us know these details and we can assist further 

Thanks

Jack

**Comment by jtracey93** [comment]
AB#29538

**Comment by DaFitRobsta** [comment]
@gin1974, I've performed a few tests in EastUS and WestUS3 by deploying the hubnetworking.bicep with your reproducible instructions and only failed one time. Subsequent attempts resulted in success. I was wondering if you've been able to reproduce this bug since you first reported it. Azure is constantly being updated and I'm wondering if an update addressed this issue.
Thank you
