### ISSUE TITLE
Azure DevOps Pipeline step: Az CLI Deploy Subscription Placement failed

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ALZ-Bicep#531]
## Question/Feedback

Azure DevOps Pipeline step: Az CLI Deploy Subscription Placement failed

  - task: AzureCLI@2
    displayName: Az CLI Deploy Subscription Placement
    name: create_subscription_placement
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep \
        --parameters @infra-as-code/bicep/modules/subscriptionPlacement/parameters/subscriptionPlacement.parameters.all.json \
        --location $(Location) \
        --management-group-id $(ManagementGroupPrefix) \
        --name create_subscription_placement-$(RunNumber)

## Possible Answers/Solutions?

Error message:
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Resources/deployments/create_subscription_placement-20230518.4","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","target":"/providers/Microsoft.Management/managementGroups/alz/providers/Microsoft.Resources/deployments/create_subscription_placement-20230518.4","message":"{\r\n  \"Message\": \"The request is invalid.\"\r\n}"}]}}

**Comment by jtracey93** [comment]
Please provide your parameters file here so we can assist further. @jamesyoung007

**Comment by jamesyoung007** [comment]
Thanks for quick reply, after checking the parameter file, I found that I provided wrong value of the sub ID.
Then I updated it and tried again, it worked perfectly, thanks a lot, much appreciated!
