### ISSUE TITLE
❓👂 Question/Feedback - PLEASE CHANGE ME TO SOMETHING DESCRIPTIVE

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ALZ-Bicep#535]
## Question/Feedback

Hey team, we tried to add network watcher as part of our deployment, but the deployment failed, the error was suggesting that network watcher already exist, but I don't see the code in any of Bicep files.

resource symbolicname 'Microsoft.Network/networkWatchers@2022-07-01' = {
  name: 'string'
  location: 'string'
  tags: {
    tagName1: 'tagValue1'
    tagName2: 'tagValue2'
  }
  properties: {}
}

## Possible Answers/Solutions?

Can you please advise how ALZ-BICEP handles networkWatchers' creation in its Bicep scripts?

**Comment by jtracey93** [comment]
Hi @jamesyoung007,

The azure platform automatically enables network watcher in the same region as where you create a vnet, as documented here https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-create#network-watcher-is-automatically-enabled

So ALZ Bicep doesn't need to do this in its code. 

Thanks

Jack
