### ISSUE TITLE
💡 Feature Request - Add validation to Accelerator workflows

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/ALZ-Bicep#536]
## Describe the solution you'd like

Add validation to the accelerator workflows using whatif and environments in GitHub.

I have tested this and despite the issues set out in #249 it allows some validation before deploying to production and is relatively easy to implement.

## Describe alternatives you've considered

None.

## Additional context

How i implemented:

1. Copied the Deploy-* pipeline scripts and renamed to Validate-*
2. Amended Validate-* to use whatif
3. Amended the workflow to run a validate job using the new validate PowerShell scripts
4. Added a production environment to the GitHub repo
5. Configure the Required reviewers protection rule on the environment

Workflow:

- Create a feature branch
- Commit and create a pull request
- Workflow runs validation using whatif
- Workflow pauses due to protection rule - time to review the whatif
- Once the whatif is reviewed and we are happy with the change, approve the deployment.

**Comment by oZakari** [comment]
Hey @MilesCameron-DMs, thanks for submitting this and for sharing your approach. This is on my backlog, but if you would like to create a PR using the pipeline scripts you created that would be appreciated as well!

**Comment by MilesCameron-DMs** [comment]
Created PR: #539 

I amended it slightly so it just re-uses the Deploy-* pipeline scripts and just passes a boolean for whatif

**Comment by oZakari** [comment]
Merged #539 - Another backlog item to add What-if output to PR comments.
