### ISSUE TITLE
What is the relationship between bicep file and bicep.md file

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ALZ-Bicep#540]
## Question/Feedback

1. cuaIdManagementGroup.bicep
2. cuaIdManagementGroup.bicep.md in the folder of  generateddocs

## Possible Answers/Solutions?

Also would like to know how to generate markdown file based on bicep file, many thanks.

**Comment by jtracey93** [comment]
hey @jamesyoung007 please see https://github.com/Azure/ALZ-Bicep/wiki/Contributing#manually-generating-the-parameter-markdown-files
