### ISSUE TITLE
vwan - deploy-Private-DNS-Zones  The aggregated deployment error is too large

### ISSUE THREAD

**Issue by Acenl12** [Azure/ALZ-Bicep#541]
## Describe the bug
infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
deploy-Private-DNS-Zones 
The aggregated deployment error is too large. Please list deployment operations to get the deployment details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)

## To Reproduce
$inputObject = @{
>>   DeploymentName        = 'alz-vwanConnectivityDeploy-{0}' -f (-join (Get-Date -Format 'yyyyMMddTHHMMssffffZ')[0..63])
>>   ResourceGroupName     = "rg-$TopLevelMGPrefix-vwan-001"
>>   TemplateFile          = "infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep"
>>   TemplateParameterFile = "infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json"
>> }

## Correlation ID
97d287cd-4bf9-4963-9533-6072b4f39e4b

**Comment by picccard** [comment]
You could have a look at the deployment details on the resource group in the portal. I don't know if this would help, but it might reveal some more details.

<img width="600" alt="image" src="https://github.com/Azure/ALZ-Bicep/assets/7443949/e5c4a0d9-d075-4a5e-a76a-fec8ef3b2184">

**Comment by jtracey93** [comment]
Thanks @picccard. @Acenl12 as @picccard has mentioned above we'd need some more info the help troubleshoot here. 

Does looking at the deployment give you any more info?

**Comment by Acenl12** [comment]
![image](https://github.com/Azure/ALZ-Bicep/assets/38886380/25d5819f-60d6-4d6f-8aeb-df3c60bc7593)
When I click on of them I see this: 
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "A virtual network cannot be linked to multiple zones with overlapping namespaces. You tried to link virtual network with 'privatelink.queue.core.windows.net' and 'privatelink.queue.core.windows.net' zones."
    }
}

**Comment by jtracey93** [comment]
Is this the same for all the zones @Acenl12 ?

If so it would seem you have linked the vnet with a number of different DNS zones with the same names or the same ones but with different vnet link names.

**Comment by Acenl12** [comment]
I only specified the vnet to link in the template,  the first 20 succeed and then the rest fails.  I didn't link anything manually.
________________________________

**Comment by Acenl12** [comment]
Is there a way to download the full deployment log of that deployment and attach it here? That makes it easier for both of us i think
________________________________

**Comment by jtracey93** [comment]
Can you provide your parameters file (react anything sensitive)?

**Comment by jtracey93** [comment]
Also @Acenl12 have you use this subscription before for other ALZ testing etc? And have they been cleaned up?

**Comment by Acenl12** [comment]
> Also @Acenl12 have you use this subscription before for other ALZ testing etc? And have they been cleaned up?

Yes I created a new subscription and deployed the ALZ-Bicep-VWAN in there

**Comment by picccard** [comment]
Your error says `A virtual network cannot be linked to multiple zones with overlapping namespaces.`
Could you have a look at your existing Private DNS zones and see if there exists any, and/or they are already linked to your hub-vNet?

I'm showing my private DNS zones as an example here:

![image](https://github.com/Azure/ALZ-Bicep/assets/7443949/e5919762-8df3-426c-9643-aa90c8e4a3d8)
