### ISSUE TITLE
🪲 Bug Report - InvalidAuthenticationToken Error when running mgDiagSettingsAll.bicep

### ISSUE THREAD

**Issue by teamlittman** [Azure/ALZ-Bicep#544]
## Describe the bug

I'm setting up a new ALZ based on the bicep development flow using Powershell. I've set the parPlatformMgAlzDefaultsEnable = false for my scenario. All was working well until step 4.1 Management Groups Diagnostic Settings when I encountered the following 3 errors:
Status Message:  (Code:InvalidAuthenticationToken)

## To Reproduce

Steps to reproduce the behaviour:
I run this:
New-AzManagementGroupDeployment `
  -TemplateFile infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep `
  -TemplateParameterFile infra-as-code/bicep/orchestration/mgDiagSettingsAll/parameters/mgDiagSettingsAll.parameters.all.json `
  -Location australiaeast `
  -ManagementGroupId alz

## Expected behaviour

Complete with no errors.

## Correlation ID

938b8666-a410-428b-ba99-d3598090d3ca

## Additional context

Obviously I have modified the mgDiagSettingsAll.parameters.all.json file. And I believe I have this param correct
    "parLogAnalyticsWorkspaceResourceId": {
      "value": "/subscriptions/<the-sub-id>/resourceGroups/rg-alz-logging-001/providers/Microsoft.OperationalInsights/workspaces/alz-log-analytics"
    },
Where <the-sub-id> is the subscription id of my platform management groups LAW. I found this in the JSON view of the LAW.

Any help appreciated.

**Comment by jtracey93** [comment]
Looks like youve got a double // after subscriptions @teamlittman

**Comment by jtracey93** [comment]
Also @teamlittman we had this in issue #470 and it turned out to be the RP wasn't registered on the management subscription. 

Are you able to confirm that the subscription that hosts the Log Analytics Workspace has the `Microsoft.Insights` resource provider registered? You can run `Get-AzResourceProvider -ProviderNamespace 'Microsoft.Insights' | FT` to check.

If it isn't, can you run `Register-AzResourceProvider -ProviderNamespace 'Microsoft.Insights'` and wait for it to succeed and finish and then re-run the `mgDiagSettingsAll.bicep` deployment and let me know the results?

**Comment by teamlittman** [comment]
Thanks Jack. Yes I had obfuscated the LAW id incorrectly when I pasted it in.. it is like this:
    "parLogAnalyticsWorkspaceResourceId": {
      "value": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-alz-logging-001/providers/Microsoft.OperationalInsights/workspaces/alz-log-analytics"
    },

I also checked the RP registration and it was 'NotRegistered'.. so I registered as suggested and waited for the status to change to 'Registered', however the issues remains:
CorrelationId: 9fc20394-d71b-4768-948c-056d037307a9

(Really appreciated the prompt turn around btw!)

**Comment by jtracey93** [comment]
Please try it again after giving the RP time to register

Sent from my iPhone

On 29 May 2023, at 09:07, Steve Littman ***@***.***> wrote:

﻿

Thanks Jack. Yes I had obfuscated the LAW id incorrectly when I pasted it in.. it is like this:
"parLogAnalyticsWorkspaceResourceId": {
"value": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-alz-logging-001/providers/Microsoft.OperationalInsights/workspaces/alz-log-analytics"
},

I also checked the RP registration and it was 'NotRegistered'.. so I registered as suggested and waited for the status to change to 'Registered', however the issues remains:
CorrelationId: 9fc20394-d71b-4768-948c-056d037307a9

(Really appreciated the prompt turn around btw!)

**Comment by teamlittman** [comment]
Thank Jack.. I figured out that I had registered the MS Insights in the wrong subscription.. not my platform subscription, so I changed to the correct one using:
`Set-AzContext -Subscription 'xxxx'`
and then registered using:
`Register-AzResourceProvider -ProviderNamespace 'Microsoft.Insights'`
and then waited a few hours, and its working now.
So I'm officially proving my newb status in Azure :(
Thanks again for all your help.
