### ISSUE TITLE
ALZ-Bicep-4a - Hub (Hub-and-Spoke) Deployment does not complete when DDOS set to false

### ISSUE THREAD

**Issue by michael-novak-80** [Azure/ALZ-Bicep#547]
Hello,

I am having trouble with running the ALZ-Bicep-4a Workflow component. 

I have edited the hubNetworking.parameters.all.json file to exclude the DDoS protection as following:

    "parDdosEnabled": {
      "value": false
    },

However, when I run the deployment, it fails with the following error:

`Resource /subscriptions/connectivitysubID/resourceGroups/rgname/providers/Microsoft.Network/ddosProtectionPlans/alz-ddos-plan referenced by resource /subscriptions/connectivitysubID/resourceGroups/rgname/providers/Microsoft.Network/virtualNetworks/vnet-name was not found. Please make sure that the referenced resource exists.`

## To Reproduce

Steps to reproduce the behaviour:

1.  Set the parDdosEnabled parameter in hubNetworking.parameters.all.json to "false"
```
"parDdosEnabled": {
      "value": false
    },

```
3. Run the ALZ-Bicep-4a Workflow action 
4. Wait for results 

## Expected behaviour

The workflow should not create DDOS Protection and successfully complete.

## Correlation ID

eddb945e-3b14-44ac-81ff-3e2f75f77318

**Comment by michael-novak-80** [comment]
Fixed it by redownloading the repo and started from scratch. Not sure what the issue was.

**Comment by ReneHezser** [comment]
I do have the same experience.

    "parDdosEnabled": {
      "value": false
    },
    "parDdosPlanName": {
      "value": "alz-ddos-plan"
    },

Even when set to false, a ddos plan is being provisioned (and assigned to VNets).

**Comment by gallardo-juan** [comment]
I am seeing this same issue. DDOS is set to disable and getting the exact same error.

**Comment by bojanmisic** [comment]
Same here.

**Comment by jtracey93** [comment]
@bojanmisic please open a new issue.

also please ensure you are updating and committing changes in this file: `config\custom-parameters\hubNetworking.parameters.all.json` if using the acceelerator
