### ISSUE TITLE
logging.bicep is using expired API version

### ISSUE THREAD

**Issue by michael-novak-80** [Azure/ALZ-Bicep#548]
## Describe the bug

logging.bicep file located in \upstream-releases\v0.14.0\infra-as-code\bicep\modules\logging is using expired API version on line 96

`resource resLogAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2021-06-01' = {`

should be updated to 

`resource resLogAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
`

**Comment by jtracey93** [comment]
Thanks @michael-novak-80 this was automatically detected by our daily build task here #545 and fixed with PR #546 this is available from main now and will be in the next release in a few weeks in `v0.15.0`
