### ISSUE TITLE
How to debug workfow script?

### ISSUE THREAD

**Issue by kedar-1** [Azure/ALZ-Bicep#550]
Hello,

performing Github actions on ALZ-Bicep-2 Workflow I have received this error message:

VERBOSE: 
New-AzManagementGroupDeployment: /home/runner/work/web-alz-bicep/web-alz-bicep/pipeline-scripts/Deploy-ALZMGDiagnosticSettings.ps1:25
Line |
  25 |  New-AzManagementGroupDeployment @inputObject
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 07:46:05 - Error: Code=MultipleErrorsOccurred; Message=Multiple error
     | occurred: NotFound,NotFound. Please see details.

Despite I have verified twice the content of parameters file is correct there is an error.

Where to look for details as the error message suggest?

Thanks

**Comment by jtracey93** [comment]
Hey @kedar-1, is this related to #549?

You can see the errors in more detail by looking at the management group deployment history as documented here: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#management-group-deployments

You will need to look on your intermediate root management group (the one below the Tenant Root Group) as this is where the deployment is targeted 👍

**Comment by kedar-1** [comment]
Hi @jtracey93 

I've founf the root cause.

Based on discissusion with customer we have disabled default Landing zone management group creation.

And workflow Step 2 failed because of this.

Don't know how to fix but in a case I have an option to not deploy Online and Copr mg the rest of workflow must be ready to deplyo without errors.

**Comment by kedar-1** [comment]
Forgot to include an info about error related to #544 

Please ensure the Management sub have insight provider registered during deployment.

_Register-AzResourceProvider -ProviderNamespace Microsoft.insights_

**Comment by jtracey93** [comment]
Thanks for the feedback and info. 

To summarize, the issue occurred because you set `parLandingZoneMgAlzDefaultsEnable` to `false` and also the provider needed to be registered on the management sub for insights?

If so we can look to fix both of these in a PR :)

**Comment by jtracey93** [comment]
[like]  Jack Tracey reacted to your message:
________________________________
