### ISSUE TITLE
parPrivateDnsZonesResourceGroup missing in vwanConnectivity.parameters.all.json

### ISSUE THREAD

**Issue by kedar-1** [Azure/ALZ-Bicep#553]
## Describe the bug

According to ALZ ES deployment a separate rg will be created for all private DNS zones.
There is a parameter in BICEP file but parPrivateDnsZonesResourceGroup is missing in vwanConnectivity.parameters.all.json

## To Reproduce

Steps to reproduce the behaviour:

1. Try to deploy vWAN
2. All private zones will be in rg with firewall, vituall wan etc.

## Expected behaviour

Include parPrivateDnsZonesResourceGroup in vwanConnectivity.parameters.all.json

**Comment by jtracey93** [comment]
Hey @kedar-1,

Thanks for raising. Can you provide the link as to where we suggest it will be a separate RG?

We actually dont create this RG but instead expect it to already exist for this parameter `parPrivateDnsZonesResourceGroup` from the `privateDnsZones` module today.

Let us know

Thanks

Jack

**Comment by kedar-1** [comment]
I'm refering this ALZ setup

https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md

**Comment by PMLIO** [comment]
Can confirm the same issues. The vwanCoonectivity.bicep file has this reference but deploys into the hub resource group.
![image](https://github.com/Azure/ALZ-Bicep/assets/38728005/195a8494-510f-4c31-be14-5afba841b119)

**Comment by jtracey93** [comment]
This is not included by default as it relies on a function for a default value to deploy to the same resource group as the deployment has been targeted too. This is so folks deploying the module have a successful experience with default parameters out of the box:

https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep#L88

You can deploy to a resource group of your choice, but it must be created before running this module, and you can add the `parPrivateDnsZonesResourceGroup` parameter either to the command line `New-AzResourceGroupDeployment ..... -parPrivateDnsZonesResourceGroup "<RSG NAME HERE>"` or you can add this to your parameter file:

```json
"parPrivateDnsZonesResourceGroup": {
    "value": "<RSG NAME HERE>"
},
```
