### ISSUE TITLE
💡 Feature Request - Accelerator doesn't update all values across all parameter files (eg mgrp prefix/ law resource-id)

### ISSUE THREAD

**Issue by bram-boer** [Azure/ALZ-Bicep#560]
## Describe the solution you'd like

In the accelerator some parameters are set in the parameter files, but not all. eg log analytics workspace name. also some naming conventions are not set/ updatable. 
not bad as you can edit parameter files in your code, however it shows that some values (eg mgrp prefix / law resource id) are used and defined in multiple parameter files. this works contraproductive 

## Describe alternatives you've considered

one parameter file, or referencing others to build parameters based on previous deployment steps to simplify configuration

## Additional context

As discussed with Jack, Contact me on my MSFT teams, Im willing to help in this development/testing

**Comment by bram-boer** [comment]
Hi @jtracey93 and @oZakari 

I noticed that eg. the LAW subscriptionID and name is not updated in the resource ID parameter ("parLogAnalyticsWorkspaceResourceId")  in several files such as Policy Assignments and DiagSettings parameter files.

**Comment by oZakari** [comment]
Hi @bram-boer, 

Could you share which version of the ALZ PowerShell Module you are using?  You can use `Get-InstalledModule ALZ -AllVersions`.

For the subscription ID not getting replaced, are you seeing the management group subscription ID not getting replaced correctly within subPlacementall.parameters.all.json as well?
![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/31496408-55d7-4259-9ddf-827bdbed2722)


The resource groups should incorporate the prefix you provide when prompted. However, the resources within those resource groups currently have alz as the prefix by default. Is that what you're looking to have changed?

**Comment by jtracey93** [comment]
@bram-boer can you come back to @oZakari here please?
