### ISSUE TITLE
🪲 Bug Report - Support for active/active VNET Gateway

### ISSUE THREAD

**Issue by andrewjmackay** [Azure/ALZ-Bicep#561]
## Describe the bug

ActiveActive Gateway must be created with two IP configurations. (Code: ActiveActiveGatewayMustHaveExactlyTwoIpConfigurations)

## To Reproduce

Steps to reproduce the behaviour:

config\custom-parameters\hubNetworking.parameters.all.json
"parVpnGatewayConfig": {
      "value": {
"activeActive": true
        }

## Expected behaviour
upstream-releases\v0.14.0\infra-as-code\bicep\modules\hubNetworking\hubNetworking.bicep

Wanting to confirm module support for active/active configuration

## Correlation ID

363500a8-01bc-4772-807c-4587532bfb04

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by jtracey93** [comment]
Hey @andrewjmackay,

From reviewing the code I don't believe this is setup to work as the hub networking module currently stands.

For now, you may wish to investigate injecting the use of this module from CARML to plug the gap for now: https://github.com/Azure/ResourceModules/tree/main/modules/network/virtual-network-gateways

**Comment by andrewjmackay** [comment]
Hey @jtracey93 

CARML works for me and can bridge that gap for now.

Thanks for the quick reply, much appreciated.
