### ISSUE TITLE
🪲 Bug Report - Deployment of Deploy-ALZMGDiagnosticSettings.ps1 fails

### ISSUE THREAD

**Issue by joeldroid2** [Azure/ALZ-Bicep#565]
## Describe the bug
On a fresh root tenant (testing account)
When running alz-bicep-1.yml it is failing with InvalidAuthentication Token error
all other steps work fine
I have got full admin rights
and so does the service principal (Cloud Application Administrator role)

## To Reproduce
Nothing special, exactly the same scenario

## Expected behaviour
It should work. I have setup all the pre-requisites and all the management groups are getting created.

## Screenshots 📷
<img width="582" alt="image" src="https://github.com/Azure/ALZ-Bicep/assets/128106123/785701ff-45f0-4218-b744-90f889809893">

## Correlation ID

56d9c1fe-9eb7-44f1-85f5-58a826681abe

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by jtracey93** [comment]
Hey @joeldroid2,

Thanks for the issue, this we have seen before on new subscriptions mainly where the subscription that contains the log analytics workspace hasn't got the `Microsoft.Insights` Resource Provider registered.

Could you run the below PowerShell on that subscription and then try the pipeline again?

```pwsh
Select-AzSubscription -SubscriptionId <YOUR MANAGEMENT SUBSCRIPTION ID>
Register-AzResourceProvider -ProviderNamespace 'Microsoft.Insights'
```

Let us know

Thanks

Jack

CC: @oZakari, do we think we should add this as a step to our pipelines to cover this off in the accelerator. e.g. Check if RP registered on Management Sub, if not register it, if it is skip registration

**Comment by joeldroid2** [comment]
Yes this has fixed the pipeline.
Thanks @jtracey93
