### ISSUE TITLE
Bastion NSG deployed when parAzBastionEnabled -eq $false

### ISSUE THREAD

**Issue by woutermation** [Azure/ALZ-Bicep#573]
## Describe the bug

When setting Bastion to disabled the NSG is still deployed

## To Reproduce

parAzastionEnabled set to false

1. Deploy
2. Check NSG

## Expected behaviour

Expect that the NSG is not deployed; and can be fixed in hubNetworking.bicep line 368

```bicep
resource resBastionNsg 'Microsoft.Network/networkSecurityGroups@2021-08-01' = if (parAzBastionEnabled) {
}
```

**Comment by jtracey93** [comment]
Thanks @woutermation for the issue

Would you like to submit a PR to fix this that we can merge in? 

Let me know

Thanks

Jack
