### ISSUE TITLE
🪲 Bug Report - Policies Definitions Are Not Deleted in Azure When Removed From Main Bicep File

### ISSUE THREAD

**Issue by lwooden** [Azure/ALZ-Bicep#576]
## Describe the bug

This may not be a limitation of Bicep per se, but for deployments of azure role policy definitions at the Management Group level (as specified in this codebase via it's examples) you cannot delete a role policy definition by removing it from the bicep file and running the deploying again. Although this deployment is executed using the default INCREMENTAL mode, the policy that you comment out or delete will still remain unchanged from deployment to deployment. T

## To Reproduce

Steps to reproduce the behaviour:

1. Define 2 role policy definition to be applied at the Management Group level in a bicep file
2. Run that deployment using Azure CLI - >> az deployment mg create --location <LOCATION> --management-group-id <STRING>  --template-file customPolicyDefinitions.bicep
3. Confirm that the policy was created in Azure at the management group level you specified
4. Comment out or delete (1) of the policy definitions from STEP 1
5. Reapply the deployment
6. Check deployment output stating the policy definition is still apart of the deployment (although commented or deleted)
7. Check Azure Portal and see the policy definition still persist

## Expected behaviour

I would expect for the the policy definition to no longer be listed in the deployment result output. That way I can safely delete it from the UI OR implement COMPLETE mode for this deployment so policies not listed in the bicep file will be removed

**Comment by jtracey93** [comment]
Hi @lwooden,

Unfortunately today ARM/Bicep do not support deleting resources, even if using the complete mode deployment as it is not supported above the Resource Group scope; so not useful here.

So today you would have to manually delete the policy definition via Azure PowerShell or CLI or in the Portal, as it's not possible in ARM/Bicep today.

> Theres a good discussion on the Bicep repo here about this for more reading: https://github.com/Azure/bicep/discussions/1418

Also as a side not the https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep module doesn't have any defined outputs today. But as long as you remove or comment out the policy definition/initiative you want to not deploy/update anymore from either, `varCustomPolicySetDefinitionsArray` or `varCustomPolicyDefinitionsArray` or any of the line here https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep#L1876-L1900 

You can then manually delete the policy as stated above and it won't be re-deployed :)

> Also please ensure you save the file before trying to re-deploy after commenting out or deleting the policy in the code; I've forgotten to do this a few times myself 😆 

Hope that helps, please re-open if this doesnt work with a link to an example of your code so we can review and test using something like a [gist](https://gist.github.com/)

Thanks

Jack
