### ISSUE TITLE
❓👂 Question/Feedback - ISO, CIS, MCSB, NIST, PCI etc not part of ALZ? 

### ISSUE THREAD

**Issue by BartDecker** [Azure/ALZ-Bicep#587]
ISO, CIS, MCSB, NIST, PCI etc are not part of ALZ? 

Any (conceptual) reason for that?

**Comment by jtracey93** [comment]
Hi @BartDecker,

Thanks for the issue. 

We assign the MCSB initiative (https://learn.microsoft.com/en-us/security/benchmark/azure/overview) to the intermediate root management group as part of us enabling Defender for Cloud. 

The MCSB includes mapping across CIS, NIST and PCI. 

But then customers are free to add on their own additional policy assignments to add more controls that they need. 

ALZ has to be applicable to all out of the box, so some more restrictive controls you may need as more regulatory compliance frameworks may not be applicable to all

Hope that helps

Let us know

**Comment by BartDecker** [comment]
> Hi @BartDecker,
> 
> Thanks for the issue.
> 
> We assign the MCSB initiative (https://learn.microsoft.com/en-us/security/benchmark/azure/overview) to the intermediate root management group as part of us enabling Defender for Cloud.
> 
> The MCSB includes mapping across CIS, NIST and PCI.
> 
> But then customers are free to add on their own additional policy assignments to add more controls that they need.
> 
> ALZ has to be applicable to all out of the box, so some more restrictive controls you may need as more regulatory compliance frameworks may not be applicable to all
> 
> Hope that helps
> 
> Let us know

Ah I missed that one (MCSB). Found it indeed by searching on def id in the code.
