### ISSUE TITLE
❓👂 Question/Feedback - Is there an ETA for Azure Monitor Baseline Alerts (Preview) to be integrated with ALZ?

### ISSUE THREAD

**Issue by BartDecker** [Azure/ALZ-Bicep#588]
Is there an ETA for Azure Monitor Baseline Alerts (Preview) to be integrated with ALZ?

https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-monitor-baseline-alerts-preview/ba-p/3810463

**Comment by jtracey93** [comment]
Hey @BartDecker,

This work is underway to be integrated into all of the ALZ implementation options (portal, bicep, terraform) and we hope to have completed in the next couple of months.

Looping in @paulgrimley and @arjenhuitema who are leading this work on the AMBA side.

Thanks

Jack

**Comment by paulgrimley** [comment]
@BartDecker thank you for your interest in AMBA, we have been working hard in the background to align as interest is growing and capabilities are expanding to use AMBA framework and we are aligning across teams. As @jtracey93 states we hope to have the work completed in the next couple of months subject to testing and avoiding any unplanned issues. We will keep you posted via https://aka.ms/alz/whatsnew.
