### ISSUE TITLE
Customised ALZ Modules

### ISSUE THREAD

**Issue by awood86** [Azure/ALZ-Bicep#589]
### Let us know the feedback or general question

Hi Guys,

First off really grateful for the accelerator, absolutely helps us so much, so thank you!

Just wanted to question the Incorporating Modified ALZ Modules part, I've modified the vwanConnectivity.bicep module but it has dependencies on the privateDNS modules. Is it right that I'll need to copy both in the custom-modules location?

Thanks

### Version

v0.16.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @awood86,

It's really your call. If you don't need to customise the private dns module and just want to consume it as it is. Then you don't need to copy the dependent modules. 

Hope that helps. 

Thanks

Jack

**Comment by awood86** [comment]
Would this be the best way to do this for every new build? By defining the upstream-release and version, or is there a better way you can advise on?

module modPrivateDnsZones '../../../upstream-releases/v0.16.0/infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep'

**Comment by jtracey93** [comment]
Hi @awood86,

We actually recently published some guidance on this here https://aka.ms/alz/bicep/accelerator

Check it out and let us know

Thanks

Jack

**Comment by awood86** [comment]
Hi @jtracey93, exactly what I was looking for thanks!
