### ISSUE TITLE
🪲 Bug Report - privateDnsZoneLinks fails with index outbound error

### ISSUE THREAD

**Issue by milind045** [Azure/ALZ-Bicep#591]
## Describe the bug
When trying to link a new virtual network to existing Private Dns Zone, the privateDnsZoneLinks module isn't able to extract the correct zone name. The error I see is as below
+++
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '[format('{0}/dnslink-to-{1}', split(parameters('parPrivateDnsZoneResourceId'), '/')[8], variables('varSpokeVirtualNetworkName'))]' at line '1' and column '1172' is not valid: The language expression property array index '8' is out of bounds.. Please see https://aka.ms/arm-functions for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":1172,"path":"properties.template.resources[0]"}}]}
+++

I passed parPrivateDnsZoneResourceId the following value
+++
/subscriptions/xxx/resourceGroups/rg-connectivity/providers/Microsoft.Network/privatelink.analysis.windows.net
+++

## To Reproduce

Steps to reproduce the behaviour:

1. Invoke orchestration module hubPeeredNetwork by passing non-empty parPrivateDnsZoneResourceIds array

## Expected behaviour

The script should not error out and allow new vnet to be linked to the input DNS zones. Simple fix is to change split index to 7 (instead of 8)

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Correlation ID

A correlation ID really helps us investigate your issue further. Please provide one if possible. Details on how to find a correlation ID can be found here: [Correlation ID and support](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#correlation-id-and-support)

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by jtracey93** [comment]
Hey @milind045 

Thanks for the issue. 

However I don't think you have supplied a correct resource ID as it's missing a resource type. 

The resource ID should be: `/subscriptions/xxx/resourceGroups/rg-connectivity/providers/Microsoft.Network/privateDnsZones/privatelink.analysis.windows.net`

Note the `privateDnsZones` addition in the resource ID which makes the resource ID correct and the split function work as required. 

Hope that helps.

Thanks

Jack

**Comment by milind045** [comment]
@jtracey93 You're right! I seem to have dropped one segment from the string while copying/ replacing the input params . Thanks for taking a look on a weekend!
