### ISSUE TITLE
🪲 Bug Report - Documentation wrong infra-as-code/bicep/orchestration/subPlacementAll

### ISSUE THREAD

**Issue by Wopienkaatwork** [Azure/ALZ-Bicep#602]
## Describe the bug

On the page infra-as-code/bicep/orchestration/subPlacementAll there is a typo with the Deploymentname for the PowerShell Deploymentname. 

## To Reproduce

Steps to reproduce the behaviour:

current code states:   DeploymentName        = 'alz-SubPlacementAll-{0}' -f (-join (Get-Date -Format 'yyyyMMddTHHMMssffffZ')[0..63])
but it should be   DeploymentName        = 'alz-SubPlacementAll-{0}' -f (-join (Get-Date -Format 'yyyyMMddTHH**mm**ssffffZ')[0..63])

## Expected behaviour

The PowerShell code for global and China region should be corrected.

**Comment by jtracey93** [comment]
Hey @Wopienkaatwork,

Thanks for raising the issue, this isn't a bug that is preventing deployment, right? More of a "nit pick"?

Also it will be the same across all of our modules from a quick check, so we'd need to make the change to all of them.

Could you share some insight as to why this is an issue and why you would like the change made so we can triage further? 🙂

Finally would you be willing to put a PR in to update all these in every module if so?

Let us know

Thanks

Jack
