### ISSUE TITLE
💡 Feature Request - Enable VPN Basic sku as a valid gateway type

### ISSUE THREAD

**Issue by FlashG75** [Azure/ALZ-Bicep#605]
### Enable the VPN Basic sku to be configured as a valid parameter when deploying hubNetworking

The VPN Basic sku is significantly cheaper than the VpnGw1 sku and despite being legacy is a good option for testing and lab environments.

At the moment, if setting sku to Basic in the hubNetworking.parameters.all.json, the Accelerator Pipeline "Hub (Hub-and-Spoke) Deployment fails with the following error message:

New-AzResourceGroupDeployment: /home/vsts/work/1/s/pipeline-scripts/Deploy-ALZHub-HubAndSpoke.ps1:30
Line |
  30 |  New-AzResourceGroupDeployment @inputObject
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 15:35:18 - The deployment 'alz-Hub-and-SpokeDeploy-20230810T1508096608Z'
     | failed with error(s). Showing 1 out of 1 error(s). Status Message:
     | Virtual network gateway Sku specified is not valid for gateway
     | /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-birchride-connectivity/providers/Microsoft.Network/virtualNetworkGateways/alz-Vpn-Gateway with DeploymentType VMScaleSet. The allowed Skus are VpnGw1AZ,VpnGw2AZ,VpnGw3AZ,VpnGw4AZ,VpnGw5AZ,VpnGw1,VpnGw2,VpnGw3,VpnGw4,VpnGw5. (Code: InvalidGatewaySkuSpecifiedForGatewayDeploymentType)   CorrelationId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by jtracey93** [comment]
Hey @FlashG75,

Im afraid we are not planning to enable support for the basic SKU as it's a legacy SKU.

Apologies, but we must enforce good practices and set our customers up for long term success on the platform.
