### ISSUE TITLE
Enable Azure Vwan Routing Intent

### ISSUE THREAD

**Issue by amp-pds** [Azure/ALZ-Bicep#609]
### Contact Details

alan.phillips@pds.police.uk

### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Enable Azure Vwan Routing Intent with ability to individually set Internet bound traffic, private bound traffic and Inter-hub traffic.

Custom route 'default-to-azfw' also needs removing to all enabling of routing intent.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Allows setting of routing policies and routing intent allows routing of traffic between Vwan hubs in same and other regions. 

### Version

v0.16.1

### check previous github issues

- [X] This feature does has not been requested according to the current issue list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Thanks @amp-pds for raising this ask,

I have the code in development and should be available shortly
