### ISSUE TITLE
Add Azure Firewall custom DNS servers as parameter and resource setting

### ISSUE THREAD

**Issue by amp-pds** [Azure/ALZ-Bicep#626]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Request to include an additional parameter in the vwanConnectivity.bicep module to update the Azure Firewall with custom DNS server IP(s) and the parameter/setting to be included in the resource resFirewallPolicies deployment.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

If using a Private DNS Resolver service or own DNS virtual machines with Azure Firewall DNS proxy enabled, then need a way to pass the IP address(es) to be added as custom DNS servers on the Azure Firewall.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @amp-pds,

This is actually already in a PR here #615 that @juang903 is working on and its nearly ready to be merged, just some linting to sort 👍 

Stay tuned
