### ISSUE TITLE
wrong doco link

### ISSUE THREAD

**Issue by mthemark** [Azure/ALZ-Bicep#627]
https://github.com/Azure/ALZ-Bicep/blame/817cf956ce572f69cf2136551403f7fb957a01b6/docs/wiki/Accelerator.md#L81

think this should refer to following link.
https://github.com/Azure/ALZ-Bicep/wiki/DeploymentFlow#network-topology-deployment

**Comment by jtracey93** [comment]
Hey @mthemark,

Would you like to submit a PR to fix this?

Let us know

Thanks

**Comment by oZakari** [comment]
This has been corrected.
