### ISSUE TITLE
How to parameterize the Policy Assignment Resource ID through Bicep Approach

### ISSUE THREAD

**Issue by rajasekarvaithi01** [Azure/ALZ-Bicep#629]
Hello Everyone ,

we are using this ALZ-Bicep Repo for Policy Deployment.

**Policy Reference URL**: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Update%20Management%20Center/AzUpdateMgmtCenter_ScheduledPatching_Deploy.json

This is MY Policy Assignment File , Here Maintenance Configuration Resource ID Value needs to be parameterize . with Bicep .

![image](https://github.com/Azure/ALZ-Bicep/assets/106740405/b5141051-1b99-4dba-a01c-404d75ad6a84)

Also Every time Maintenance Configuration Resource ID will different . so dynamically needs to pick the value and to pass it in assignment file.

So I need some Guidance How I can get this Resource ID and Pass to Policy Assignment file ?

Notes: I tried  with Az deployment show command to get the Maintenance configuration Resource ID and pass to Policy Assignment through Sed Command in Bash Script. But I need any other Approach I can follow to Parameterize this Value?

**Comment by jtracey93** [comment]
Hi @rajasekarvaithi01,

Thanks for raising the issue and also using ALZ-Bicep 👍

I think what you need to use is the [`parPolicyAssignmentOverrides` parameter](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/generateddocs/policyAssignmentManagementGroup.bicep.md#parpolicyassignmentoverrides) of the [`policyAssignmentManagementGroup.bicep`](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments) module. 

> This is the module we use in ALZ-Bicep's [`alzDefaultPolicyAssignments.bicep`](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults) module which makes all of the default ALZ policy assignments

As you can see [here](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep#L431-L441) we use the `parPolicyAssignmentOverrides` to pass in a parameter value to the policy assignment dynamically from a parameter in the calling bicep file `alzDefaultPolicyAssignments.bicep`. See `emailSecurityContact` as an example.

The Key/Value pairs provided in `parPolicyAssignmentOverrides` allow you to override whatever is in the JSON file for the policy assignment. Which is exactly what you are trying to do and can therefore use too.

You can then in your pipeline step for assigning this policy, just pass in a different input value to the parameter, like `parMsDefenderForCloudEmailSecurityContact` in the above example for the policy assignment parameter of `emailSecurityContact`.

Hope that helps, let us know

Thanks

Jack

**Comment by rajasekarvaithi01** [comment]
Hi @jtracey93 Thankyou for your Detailed Explanation .

I have some Questions Around this 

But this **emailSecurityContact** variable is it pick the value from Pipeline while deploying Policy Assignment.

could you share any reference  / any pipeline commands .for This value getting in to assigned through Pipeline.

**Comment by jtracey93** [comment]
It is indeed. Although I don't have an example for the email one. 

But I do for the `parLogAnalyticsWorkspaceResourceId`

https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml see line 216. 

You just need to specify it as an inline parameter https://learn.microsoft.com/azure/azure-resource-manager/bicep/deploy-cli#inline-parameters or https://learn.microsoft.com/azure/azure-resource-manager/bicep/deploy-powershell#inline-parameters

Let me know if that helps resolve this issue
