### ISSUE TITLE
Description of parTopLevelManagementGroupPrefix within subPlacementAll.bicep inaccurate 

### ISSUE THREAD

**Issue by RT235** [Azure/ALZ-Bicep#634]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I believe the description of this Parameter is misleading, as it's the same text from managementGroups.bicep.

This parameter does not create anything within the subPlacementAll.bicep file, it is used as a prefix, as the Parameter name suggests.

@sys.description('Prefix for the management group hierarchy.  This management group will be created as part of the deployment.')
@minLength(2)
@maxLength(10)
param parTopLevelManagementGroupPrefix string = 'alz'

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @RT235,

We will take this one on if we don't hear from you in 24 hours 👍

Let us know if you do wish to contribute
