### ISSUE TITLE
config\custom-modules cannot dynamically reference other modules that existing within the upstream-releases\[version] folder due to string interpolation not being allowed

### ISSUE THREAD

**Issue by RT235** [Azure/ALZ-Bicep#635]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When creating a custom module, it is recommended within the ALZ-Bicep documentation to create a copy of the existing module and move it to config\custom-modules. This removes it from the upstream-releases\[version] \infra-as-code directory.

 When trying to reference an existing module from a custom module, because you need to go up and then down into the directory structure to reference the module being called, I would like to be able to call a specific version folder, which is not allowed due to string interpolation in file paths.

I want to be able to set this, so that when newer releases are pulled into the repo, I do not want to have to go into every custom module and change the referenced file path. 

This problem never occurs with the default modules as they never have to deal with the version number which can change.
e.g

config\custom-modules\mycustommodule.bicep
module modIntRootMgSubPlacement '../../../upstream-releases/${parFilePath}/infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep'

String interpolation is not supported in file paths.bicep(BCP092)

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @RT235, thanks for bringing this up. As you noted, string concatenation is not supported within file paths for module declarations within Bicep. 

One approach to get around is to utilize tokens and then replace the tokens within your pipelines/workflows.  In your example, you could replace the file path with `module modIntRootMgSubPlacement '../../../upstream-releases/#{UPSTREAM_RELEASE_VERSION}#/infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep`

Within your pipeline/workflow, you could then either use a script or if your organization has validated and is comfortable with using 3rd party GitHub Actions or Azure DevOps tasks, you could utilize https://github.com/cschleiden/replace-tokens for GitHub Actions or https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens for Azure DevOps Pipelines. 

Not entirely sure which platform you're using, but an example of using replace-tokens for GitHub Actions would look like the following: 

```
- name: "Replace Tokens in Bicep Files"
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["config/custom-modules/*.bicep"]'
        env:
          UPSTREAM_RELEASE_VERSION: ${{ env.UPSTREAM_RELEASE_VERSION }}
```

Just make sure you put this after the step that imports the environment variables from your .env file, and it will all update all of your tokens to match value specified in your .env file. 

Hopefully this helps and I will also update the docs with this information as well.

**Comment by jtracey93** [comment]
I'd also like to add that you should also raise this as a feature request on the Azure/Bicep repo directly as I agree this would be a useful feature.

**Comment by RT235** [comment]
> I'd also like to add that you should also raise this as a feature request on the Azure/Bicep repo directly as I agree this would be a useful feature.

Hi Jack, sorry, but where do I raise this as a feature request?

**Comment by jtracey93** [comment]
@RT235, no worries. Right here: https://github.com/Azure/bicep/issues
