### ISSUE TITLE
Add Azure Firewall Threat Intel Mode settings

### ISSUE THREAD

**Issue by amp-pds** [Azure/ALZ-Bicep#638]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

The current module deploys the Azure Firewall with the threat intelligence mode set to alert only.

Request to add params and resource code to enable choice of other modes.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Security requirements to set to alert and deny mode.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Feature Implementation

```Shell
Update to vwanConnectivity.bicep

PARAMS SECTION
@sys.description('The Azure Firewall threat Intelligence mode to enable.')
@allowed([
  'Alert'
  'Deny'
  'Off'
])
param parThreatIntelMode string = 'Alert'

RESOURCE

resource resFirewallPolicies 'Microsoft.Network/firewallPolicies@2023-02-01' = if (parVirtualHubEnabled && parVirtualWanHubs[0].parAzFirewallEnabled) {
  name: parAzFirewallPoliciesName
  location: parLocation
  tags: parTags
  properties: (parAzFirewallTier == 'Basic') ? {
    sku: {
      tier: parAzFirewallTier
    }
  } : {
    dnsSettings: {
      enableProxy: parAzFirewallDnsProxyEnabled
      servers: parAzFirewallDnsServers
    }
    sku: {
      tier: parAzFirewallTier
    }
    threatIntelMode: parThreatIntelMode
  }
}
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @amp-pds, thanks for bringing this up and I think this is a valid ask. Is this something that you'd be interested in opening a PR for? If not, no worries as we'll add it to our backlog.

**Comment by amp-pds** [comment]
Hi,

If you can add to backlog please, though I have included the required code in the feature request.

Thanks Alan.


[A picture containing text, keyboard  Description automatically generated]

  Alan Phillips
   Senior Cloud Solution Architect
   External Consultant
Police Digital Service
[Location]Mayfair Buildings, 4th Floor, 33-39 Farm Street, W1J 5RR

***@***.******@***.***>
***@***.***+44 7771 798 299
