### ISSUE TITLE
How often is then Enterprise Scale repo synct to the ALZ Bicep repo

### ISSUE THREAD

**Issue by neok-g** [Azure/ALZ-Bicep#640]
### Let us know the feedback or general question

Feedback - Question

Like the title states what is the frequence of this (one-way) synchronization?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hi @neok-g,

I take it you are referring to the policies?

If so we document this here: https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive#how-do-the-lib-folders-in-the-alz-bicep-azure-policy-modules-stay-up-to-date

We are working this week on pulling the latest policies in from the recent policy refresh in the `Azure/Enterprise-Scale` repo into ALZ Bicep and making the necessary changes 👍

**Comment by jtracey93** [comment]
Latest policies form ALZ just made available in Bicep in latest release
