### ISSUE TITLE
Can a single subscription be used for all services/apps in the landing zone?

### ISSUE THREAD

**Issue by sujitdmello** [Azure/ALZ-Bicep#642]
### Let us know the feedback or general question

I see from the doc that a minimum of 1 sub is required - but can that 1 sub be used for all modules, including application deployments? Can resource groups be used as a security boundary instead?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @sujitdmello,

It can, but we wouldn't recommend it really.

Scaling within resource groups create complicated RBAC structures and also scaling challenges that are easily solved by adopting the [subscription democratization principal of ALZ](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/design-principles#subscription-democratization). 

> We also have a YouTube video talking to this: https://www.youtube.com/watch?v=R-5oeguxFpo

Hope that helps

**Comment by sujitdmello** [comment]
> Hey @sujitdmello,
> 
> It can, but we wouldn't recommend it really.
> 
> Scaling within resource groups create complicated RBAC structures and also scaling challenges that are easily solved by adopting the [subscription democratization principal of ALZ](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/design-principles#subscription-democratization).
> 
> > We also have a YouTube video talking to this: https://www.youtube.com/watch?v=R-5oeguxFpo
> 
> Hope that helps

Creating subscriptions or getting access to multiple subscriptions is a lot more complex - hence the question. I can certainly appreciate that using them as a security boundary is better. But for smaller deployments (like maybe 1 or 2 app architectures), wondering if a single sub may suffice.
