### ISSUE TITLE
[Least Privilege] - Add support for creating subscriptions and management groups without needing tenant root permissions

### ISSUE THREAD

**Issue by vedagudipati** [Azure/ALZ-Bicep#643]
[AB#31227](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/31227)

### Describe the feature end to end, including deployment scenario details under which the feature would occur.

When customers want to create management groups or subscriptions at a lower Management group scope than the tenant root the invoker should should not need to have permissions at the tenant root which is the case today. 

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

This would allow to support the principal of least privilege, which would help customers to leverage ALZ in a more secure manner.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

The invoking user today needs the permissions to create deployments at the tenant root. Any built in role that can be assigned at root would provide such permissions and can be used as an alternative in the interim.

### Feature Implementation

Tested the scope escape by executing the subscriptionAlias.bicep and managementGroups.bicep at management group scope successfully. It would be great to have them available to be executed at MG scope.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Thanks @vedagudipati, great ask. We will get this on the backlog

**Comment by johnlokerse** [comment]
I am interested in this too and I want to add something to the issue.

At a client I have been looking for a least privilege way to deploy subscriptions using the built-in roles via Bicep, but no success yet. The problem I am still facing is that Bicep validates the deployment with the privilege: `Microsoft.Resources/deployments/validate/action` and breaks the build when it does not have these permissions.

What I have seen so far is that the `Owner` and `Contributor` role have the validate permissions, but these roles have too much rights.

Deploying with other tools like Azure PowerShell on the other hand works like a charm with lesser rights.

**Comment by Acenl12** [comment]
I think this belongs to the subscription vending
