### ISSUE TITLE
Deploy MG hierarchy to non-tenant root MG - `parTopLevelManagementGroupParentId` issues

### ISSUE THREAD

**Issue by jhaywoodcobranet** [Azure/ALZ-Bicep#650]
### What happened? Provide a clear and concise description of the bug, including deployment details.

using parameter 'parTopLevelManagementGroupParentId' kept failing deployment.

I had to update Level 1 

from

parent: {
        id: empty(parTopLevelManagementGroupParentId) ? '/providers/Microsoft.Management/managementGroups/${tenant().tenantId}' : parTopLevelManagementGroupParentId

to 

parent: {
        id: empty(parTopLevelManagementGroupParentId) ? '/providers/Microsoft.Management/managementGroups/${tenant().tenantId}' : '/providers/Microsoft.Management/managementGroups/${parTopLevelManagementGroupParentId}'

### Please provide the correlation id associated with your error or bug.

7bde6722-a04f-418c-b10c-c19e01622d3a

### What was the expected outcome?

Deploy MG hierarchy to non-tenant root MG.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Apologies @jhaywoodcobranet, misread on my side. Have added this fix in an upcoming PR with #643 anyway 👍

**Comment by jhaywoodcobranet** [comment]
Looks good, thanks :)
