### ISSUE TITLE
Version.json file needs updating

### ISSUE THREAD

**Issue by picccard** [Azure/ALZ-Bicep#658]
The version.json was not updated between release v0.16.3 -> v0.16.4. Same as #498

**Comment by jtracey93** [comment]
Yup sorry about this @picccard we have just released v0.16.5 and have updated this file correctly. 

We don't want to go back and change an old release now as it'll cause some got havoc. 

We'll do better 👍

**Comment by picccard** [comment]
hit refresh and its fixed now haha
