### ISSUE TITLE
Accelerator PR workflow scans ALZ modules and reports errors

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#660]
### What happened? Provide a clear and concise description of the bug, including deployment details.

After creating GitHub Actions with the ALZ Accelerator, the workflow _ALZ-Bicep-PR2-Lint_ scans everything in `upstream-releases` too. It runs for more than 15min and reports several errors in files in `upstream-releases`.

Of course it does. `upstream-releases` is not excluded.
https://github.com/Azure/ALZ-Bicep/blob/4013437704683ce55e259d1b3db34c540412e06e/accelerator/.github/workflows/alz-bicep-pr2-lint.yml#L30

But I see it is excluded in the _Azure DevOps_ pipeline:
https://github.com/Azure/ALZ-Bicep/blob/4013437704683ce55e259d1b3db34c540412e06e/accelerator/.azuredevops/pipelines/alz-bicep-pr2-lint.yml#L30

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

I expect `upstream-releases` beeing excluded in the workflow _ALZ-Bicep-PR2-Lint_.
Please correct me, if I'm wrong.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @baarch, thanks for calling this out and you are correct. Would you like to submit a PR for this change?

**Comment by baartch** [comment]
> Hi @baartch, thanks for calling this out and you are correct. Would you like to submit a PR for this change?

I opened a PR https://github.com/Azure/ALZ-Bicep/pull/665
