### ISSUE TITLE
[Policy] - How to handle Policy Exemtpions

### ISSUE THREAD

**Issue by kemtomra** [Azure/ALZ-Bicep#661]
### Let us know the feedback or general question

The recommended approach for handling policyDefinitions is clear, but how are exemptions handled? https://github.com/Azure/ALZ-Bicep/wiki/AddingPolicyDefs 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @kemtomra, we have the following documentation for excluding certain policy assignments.https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies#what-if-i-want-to-exclude-specific-policy-assignments-from-alz-default-policy-assignments
