### ISSUE TITLE
Add option to disable public network access to Automation Account

### ISSUE THREAD

**Issue by amp-pds** [Azure/ALZ-Bicep#664]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Add param to enable option disable public network access to Automation Account in logging.bicep

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

In addition to the central ALZ log analytics workspace, we also deploy individual log analytics workspaces at an application scope  in the landing zones management groups.

These inherit the Azure policy that denies deployment of PaaS services with a public access.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Feature Implementation

```Shell
Add to logging.bicep and param file.

@sys.description('Automation Account - allow public network access.')
param parAutomationAccountPublicNetworkAccess bool = true


Add to logging.bicep

resource resAutomationAccount 'Microsoft.Automation/automationAccounts@2022-08-08' = {
  name: parAutomationAccountName
  location: parAutomationAccountLocation
  tags: parAutomationAccountTags
  identity: parAutomationAccountUseManagedIdentity ? {
    type: 'SystemAssigned'
  } : null
  properties: {
    publicNetworkAccess: parAutomationAccountPublicNetworkAccess
    sku: {
      name: 'Basic'
    }
    encryption: {
      keySource: 'Microsoft.Automation'
    }
  }
}
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hey @amp-pds! This looks like a good ask to me, so we'll work on getting this added in.

**Comment by oZakari** [comment]
Implemented by @picccard.

**Comment by mthemark** [comment]
> 
> @sys.description('Automation Account - allow public network access.')
> param parAutomationAccountPublicNetworkAccess bool = true
> 

should public network access really default to true?

I have just updated to 0.17.0 from 0.16.3 and detected this change...
![image](https://github.com/Azure/ALZ-Bicep/assets/67937071/fd2b02ab-589e-41b9-b8f7-db4875eaaf33)
seems to be unset currently but going to set true to have public access?

**Comment by oZakari** [comment]
Hey @mthemark, good question! When this property is set to null OR true, public access is enabled. You can verify by going into the Networking blade and looking at the Public Access tab as shown below:

![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/5aff7bd6-ef4c-46cc-8bd0-14c1d86a0238)
