### ISSUE TITLE
Incorrect Upstream Release Version in .env file

### ISSUE THREAD

**Issue by KennethBess** [Azure/ALZ-Bicep#666]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Hi,

The .env file in v0.16.6 release contains a reference to release v0.16.5, why the pipeline scripts will fail.
Changing the env value v0.16.6 allow the pipeline scripts to execute successfully.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @KennethBess, thanks for calling this out. Just opened a PR for this so should be fixed shortly.
