### ISSUE TITLE
Feature-Request: Multi-Region -> Hub-and-spoke topology

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#675]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Assuming I want to deploy the Hub-and-spoke network topology and I want to deploy multiple regions, each with its own Hub network.

The recommendation here: https://github.com/Azure/ALZ-Bicep/issues/193#issuecomment-1075620583 is to simply deploy the `hubNetworking` module in each region.

Of course, I could do that. But then, the Hub networks are not automatically peered. And by now, Multi-Region is not supported by the [_Accelerator_](https://github.com/Azure/ALZ-Bicep/wiki/Accelerator).

My suggestion is:
- add an additional parameter to the `hubNetwork` module, where one can add other Hub networks to peer to
- modify the _Accelerator_ pipeline to watch `config/custom-parameters/hubNetworking.parameters.all.*.json` (something with a wildcard, to be able to add the region to the filename)
- modify the _Accelerator_ Powershell script `Deploy-ALZHub-HubAndSpoke.ps1` to loop over all `hubNetworking.parameters` files

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

If I use IAC to deploy the CAF, I don't want any manual steps in the deployment. I'd like to be able to configure the peering between the Hubs in the parameter file too.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @baartch,

Completely agree with the ask, and we are investigating across ALZ implementation tooling all up (TF, Portal & Bicep) about how to enable Multi-Region more easily or by default (as an option).

We will be sending out a survey soon and this would be great feedback to it.

Sign up to the ALZ Notifications DL here: https://aka.ms/alz/notifications/signup and you'll get the survey when its out

**Comment by jtracey93** [comment]
Also related to #375

**Comment by sebassem** [comment]
Guidance for multi-region has been added to networking modules
