### ISSUE TITLE
Missing or Undefined Custom Function 'Edit-LineEnding' in 'Invoke-PolicyToBicep.ps1' Script

### ISSUE THREAD

**Issue by KeysAU** [Azure/ALZ-Bicep#678]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When you execute the "Invoke-PolicyToBicep.ps1" script located at ".github\scripts\Invoke-PolicyToBicep.ps1," it attempts to use a custom function called "Edit-LineEnding." 

However, this function is not present in the ".ps1" script itself. I've searched the repository, but I couldn't find any references to this function. Can you please clarify where this function is supposed to come from?

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/fdbcde3c-3a09-451c-8af1-dcf24aba0069)

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/d4ac6398-fbc9-4289-9178-edbac4e73b9d)

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/42cdea3d-0f62-4add-b09b-759dd35062d1)

### What was the expected outcome?

You can call function Update-FileLineEndingType without error.

### Relevant log output

```Shell
Edit-LineEnding: 
Line |
  49 |    (Get-Content $filePath | Edit-LineEnding -LineEnding $LineEnding) | …
     |                             ~~~~~~~~~~~~~~~
     | The term 'Edit-LineEnding' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @KeysAU, sorry for any confusion. This function is now included within the [ALZ-PowerShell-Module](https://github.com/Azure/Alz-powershell-module). Once you go ahead and install that module, you should be able to call that function.

I'll go ahead and update our documentation before closing this out.

**Comment by KeysAU** [comment]
ah brilliant, yep installed the module and all working. 

Thank you!
