### ISSUE TITLE
Bug Fix for the Foreach-Object Loop in the Invoke-PolicytoBicep.ps1 Script

### ISSUE THREAD

**Issue by KeysAU** [Azure/ALZ-Bicep#683]
### What happened? Provide a clear and concise description of the bug, including deployment details.

In the script invoke-policytoBicep.ps1, there's an error at line 64. Within the foreach-object loop, you've assigned $policyDefinitionName = $Policydef.name, which should be replaced with $_.name (since you're inside a foreach-object loop).

Currently, if you have additional .json files in the \policy_definitions (as suggested in the documentation), the output you receive is ==> Adding '' to 'xxxxxxxxxxxxxxxxxx'.

There is no name. 

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/d9c398e2-70a3-4996-901b-6c4177e93a21)

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/28ea9dba-4261-4b95-a4ee-32379f4200d9)

Bug:
``` 
$policyDefinitionName = $policyDef.name
```

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/de6b1a2a-7385-43ad-bdc4-cfd8e636bdb6)

Correction:
``` 
$policyDefinitionName = $_.name
```
![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/cc020b59-3795-484f-83a6-10db11faa738)

Correct output:

![image](https://github.com/Azure/ALZ-Bicep/assets/38932932/9185ec0a-1ea6-4315-a735-52b172847311)

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

The expected outcome was for the script to correctly assign the name of each policy definition during the foreach-object loop. This would allow for the proper handling of additional .json files in the \policy_definitions, resulting in the correct output.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @KeysAU, I tested this on my end and didn't end up running into the same issue as you. I copied a new policy and change the policy name with a prefix of `Copy`. When debugging it, I was getting the expected values within the converted object (see screenshot below).

![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/93cf58e7-e2ee-481c-abbc-efff9e60204a)

Can you please add a breakpoint on line 73 and let me know what the $policyDef returns for you?
