### ISSUE TITLE
env file is generating wrong UPSTREAM_RELEASE_VERSION

### ISSUE THREAD

**Issue by JimmyKarlsson112** [Azure/ALZ-Bicep#684]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When using the bicep accelerator,  a env file is generated where UPSTREAM_RELEASE_VERSION sets the version of the golder under uppstream releases.
Currently the version you get is 0.16.6, while the generated value in the env file is 0.16.5. This will make the pipeline fail, as it use the env file to generate correct paths.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Env file having correct version number.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @JimmyKarlsson112,

Thanks for the bug. Can you confirm what version of the ALZ PowerShell module you are using?

Is it the latest `0.2.21`?

Let us know

**Comment by JimmyKarlsson112** [comment]
Np,
Yes, the latest, 0.2.21

**Comment by jtracey93** [comment]
Thanks for confirming @jaredfholgate is looking into this

**Comment by jtracey93** [comment]
Hey @JimmyKarlsson112,

@jaredfholgate has worked his magic and we have fixed this in a new release of the ALZ PowerShell module `v0.2.22` please upgrade to that and your issue should be solved

https://www.powershellgallery.com/packages/ALZ/0.2.22

**Comment by JimmyKarlsson112** [comment]
Thanks team awesome!
