### ISSUE TITLE
Bicep Accelerator Private DNS Zone for "privatelink.*.backup.windowsazure.com" Incorrectly lists uksouth

### ISSUE THREAD

**Issue by jamiepla1** [Azure/ALZ-Bicep#695]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When using the Accelerator, I used the location default as uksouth

When referencing the file: config\custom-parameters\hubNetworking.parameters.all.json

for the Private DNS Zone "privatelink.*.backup.windowsazure.com", it uses the region name uksouth rather than the geo code uks

e.g it displays:         "privatelink.uksouth.backup.windowsazure.com"  

rather than 

        "privatelink.uks.backup.windowsazure.com",

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Good catch, @jamiepla1! We will update the Accelerator configuration to utilize the geo-codes for this private DNS zone.

**Comment by simonhutson** [comment]
The documentation also needs to be updated to reflect the correct geo codes - https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/vwanConnectivity/README.md.

Refer to the following lists for regions codes: [https://download.microsoft.com/download/1/2/6/126a410b-0e06-45ed-b2df-84f353034fa1/AzureRegionCodesList.docx](https://download.microsoft.com/download/1/2/6/126a410b-0e06-45ed-b2df-84f353034fa1/AzureRegionCodesList.docx)
