### ISSUE TITLE
No tags in private DNS zone links

### ISSUE THREAD

**Issue by sergey-netdev** [Azure/ALZ-Bicep#697]
### What happened? Provide a clear and concise description of the bug, including deployment details.

The private dns zone module does not pass incoming `parTags` to `resVirtualNetworkLink` and `resVirtualNetworkLinkFailover` which causes weird deployment errors if there are polices like "Require a tag and its value on resources" `/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62` in place.

https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep

Also, please consider changing the link names, "link-vqlscyvvqtsm4" is *very* misleading.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

```
resource resVirtualNetworkLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = [for privateDnsZoneName in varPrivateDnsZonesMerge: if (!empty(parVirtualNetworkIdToLink)) {
//  name: '${privateDnsZoneName}/${take('link-${uniqueString(parVirtualNetworkIdToLink)}', 80)}'
  name: '${privateDnsZoneName}/${take('dns-${parVirtualNetworkNameToLink}-link-${privateDnsZoneName}', 80)}'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: parVirtualNetworkIdToLink
    }
  }
  dependsOn: resPrivateDnsZones
  **tags: parTags**
}]
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @sergey-netdev, thanks for raising this. Would you like to submit a PR for this addition?
