### ISSUE TITLE
Create Bicep modules for Policy Assignments at the Subscription and Resource Group Scope

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/ALZ-Bicep#702]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

I have found that ALZ-Bicep can only handle policy assignments at the management group scope utilising policyAssignmentManagementGroup.bicep

From my experience it is essential to have the ability to scope assignments at the subscription level and on the odd occasion, for example for multi-team subscriptions/landing zones, at the resource group level.

I believe the code should support all scoping levels.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Policy assignment is one of the fundamental principles of ALZ - its essential that at least subscription scope is supported.

This will lead to over-complex MG structures if left.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Created user stories which can be referenced here: 

- https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_backlogs/backlog/Azure%20Landing%20Zones%20Bicep%20Team/Features?showParents=false
- https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_backlogs/backlog/Azure%20Landing%20Zones%20Bicep%20Team/Features?showParents=false

**Comment by oZakari** [comment]
There is now an [AVM Pattern Module](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/policy-assignment) to handle policy assignments at the management group, subscription, and resource group scopes.

**Comment by MilesCameron-DMs** [comment]
Nice! Thanks for letting me know @oZakari
