### ISSUE TITLE
Bicep Landing Zone  - .env

### ISSUE THREAD

**Issue by jzryk8** [Azure/ALZ-Bicep#705]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Have downloaded the Landing Zone Accelerator (Bicep) all good. However the Pipelines all refer to an .env file that I cannot see anywhere, where is this and what is meant to be in there variable wise ? - sorry newbie.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @jzryk8, no worries at all! Not sure if you've seen this documentation, but the process for provisioning your file structure if using the Accelerator is outlined [here:](https://github.com/Azure/ALZ-Bicep/wiki/Accelerator).

Essentially, there is an ALZ-PowerShell-Module and associated cmdlet that you'll use to provision the file structure necessary to run the pipelines/workflows. Your .env file will be provisioned automatically within the root directory, and you shouldn't have to download any files manually from the GitHub repository page. 

Will close for now, but if you have any other questions feel free to reopen.

**Comment by kardiojack** [comment]
The documentation is unclear on how to create these initial subscriptions that the Accelerator PowerShell script asks for. Others seem to be confused as well: https://www.reddit.com/r/AZURE/comments/16jemms/azure_landing_zone_bicep_accelerator_explain/

If the answer is to manually create the subscriptions, that seems to defeat much of the purpose of the accelerator. In other words, I would like to be able to use the accelerator with an empty root management group and a single global admin who has the proper permissions.

**Comment by oZakari** [comment]
Hey @kardiojack, agreed, we could add a bit more clarity around subscription creation. I've created an issue based upon your comment for tracking the documentation changes needed. 

In the meantime, take a look at the [Bicep Subscription Vending documentation](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/subscription-vending#why-subscription-vending) and associated[ Bicep module](https://github.com/Azure/bicep-lz-vending) as it should hopefully provide some additional context.

**Comment by kardiojack** [comment]
Thanks for your help! After creating the subscriptions manually, the accelerator seemed to work great--definitely a useful and needed tool your team is working on.
