### ISSUE TITLE
Policy Assignment "Deploy-ASC-Monitoring" has no identity. Intention?

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#707]
### Let us know the feedback or general question

Hi everyone
I'm a little confused about this.

We have many _Non-compliant_ resources in the Policy Assignment named _Enable Monitoring in Microsoft Defender for Cloud_.
![image](https://github.com/Azure/ALZ-Bicep/assets/26668031/b67f7b4f-be17-44e8-a266-1546ca799aec)

When I click on _Create remediation task_ I get a 404.
![image](https://github.com/Azure/ALZ-Bicep/assets/26668031/424858d7-17a5-4a67-b2b4-4628249b2c0f)

And when I check the template, it is the only deploy template (`policy_assignment_es_deploy_***`) where identity is set to `none`. All the other deploy templates have a `SystemAssigned` identity.
https://github.com/Azure/ALZ-Bicep/blob/17edce484a4eef9d0d82951677bf927128efc4c2/infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json#L16

Could it be that `./infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json` needs a `SystemAssigned` identity too?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @baartch,

Thanks for raising. This policy assignment is actually for the [initiative (`1f3afdf9-d0c9-4c3d-847f-89da613e70a8`) which is the "Microsoft cloud security benchmark" initiative](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/1f3afdf9-d0c9-4c3d-847f-89da613e70a8.html).

This initiative doesn't use an effect that requires an identity, so remediation tasks are not possible for this one.

Unfortunately it's assignment name is some legacy technical debt we have that we are aware of, but it would be a breaking change to change it's name, but it's not deploying anything, just a bad name 😟

Hope that helps
