### ISSUE TITLE
Modify the route name to all_traffic

### ISSUE THREAD

**Issue by ri-we** [Azure/ALZ-Bicep#709]
https://github.com/Azure/ALZ-Bicep/blob/bf31ea38d2529dafb64be80562a50f6a79095790/infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep#L278C32-L278C32

Please modify the route name from name: 'default-to-azfw' to name: 'all_traffic'

So the portal will show "Secured by Azure Firewall" in the security configuration.

![securehub](https://github.com/Azure/ALZ-Bicep/assets/11402818/cee05088-08eb-4747-bcbc-dca22d50c934)

**Comment by oZakari** [comment]
Hi @ri-we, thanks for the call out. I'll look into parameterizing the name, so you can change it as needed.
