### ISSUE TITLE
Unable to deploy BGP custom address for VPN via Bicep. 

### ISSUE THREAD

**Issue by azure4adam** [Azure/ALZ-Bicep#714]
### What happened? Provide a clear and concise description of the bug, including deployment details.

My customer is deploying the VPN using bicep however whenever they set the Custom BGP Address it doesn’t end up applying, they can only get it to set and stick when set through the GUI. Is this a bug you have seen before in bicep? 

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Bicep template to create BGP custom address for VPN configuration

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @azure4adam, thanks for raising this issue. I am going through a verifying in my deployment now and will follow-up shortly to see if I can replicate.

**Comment by oZakari** [comment]
Hi @azure4adam, I tested on my end and the BGP peering address was correctly populated with the hub-networking module. 

![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/8a0a48fe-6a1f-4aaf-b644-14b0f1eb326a)

I think I see where they may be running into issues as the `bgpPeeringAddress` within the parVpnGatewayConfig appears to not be used within the actual module, so if they put the address there it makes sense that it wouldn't be getting added during the deployment.

Within the config, can you please verify that the parameter object for the gateway config looks similar to the following screenshot:
![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/fea8c8bb-ce45-4fc2-8a02-2acd765e112c)

Specifically, make sure that they have the object property `enableBgp` property is set to true and that they pass the BGP peering address within the `bgpSettings` property.

**Comment by oZakari** [comment]
Closing as taken offline and actual question is beyond the scope of ALZ-Bicep.

**Comment by azure4adam** [comment]
Thanks for help @oZakari.
