### ISSUE TITLE
Replace Log Analytics agents (OMS/MMA) with Azure Monitor agent

### ISSUE THREAD

**Issue by alexeyzolotukhin** [Azure/ALZ-Bicep#723]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

ALZ Bicep comes with a policy that automatically deploys a Log Analytics agent extension for VMs. According to Microsoft these agents will reach their end of support by August 2024 and Microsoft recommends replacing them with Azure Microsoft agent. Are there any plans to update this policy to use the recommended new agent? Thank you :)

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

This is important for compliance and support reasons. Failing to update this policy will affect any org that relies on it to deploy Log Analytics agents for their VMs.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @alexeyzolotukhin,

Thanks for raising the issue. We are working on this as we speak and released this to the portal just last week.

We are busy working on adding this to Terraform and Bicep ALZ options as we speak, however we have the additional brownfield customer considerations to also factor in.

Stay tuned via the roadmap and issue upstream: https://github.com/Azure/Enterprise-Scale/issues/1055#issuecomment-1914567769 & https://github.com/Azure/Enterprise-Scale/wiki/ALZ-AMA-Update
