### ISSUE TITLE
Module for Express Route Connection Not Found

### ISSUE THREAD

**Issue by jacobrhouse** [Azure/ALZ-Bicep#727]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Allows the express route to connect to VNET gateway

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

It completes the connections of networking hub resources

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

I am having to search for connection code and look to modify the parameters. This code should be included or is not found by me. 

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @jacobrhouse,

You're correct in noting that our networking modules currently do not include connection-related properties or resources. The decision to exclude this particular resource type is based on our desire to maintain simplicity and avoid unnecessary complexity in our codebase at this time.

If you're looking to incorporate this resource into your own deployment, I recommend exploring the connection resource available within the [Azure Verified Modules](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/connection). These modules have been thoroughly reviewed, providing a reliable and trusted solution for your networking needs.

Thank you for your understanding and for reaching out with your question.
