### ISSUE TITLE
[Guidance required] - ALZ-Bicep-3-SubPlacement failed

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ALZ-Bicep#734]
### Let us know the feedback or general question

Question
Testing it out with GitHub Actions, using a single subscription:
ALZ-Bicep-1-Core and ALZ-Bicep-2-PolicyAssignments worked.
ALZ-Bicep-3-SubPlacement failed
New-AzManagementGroupDeployment: /home/runner/work/march05/march05/pipeline-scripts/Deploy-ALZSubscriptionPlacement.ps1:29
Line |
  29 |  New-AzManagementGroupDeployment @inputObject
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 09:58:41 - The deployment
     | 'alz-SubscriptionPlacementDeployment-20240305T0903326953Z' failed with
     | error(s). Showing 3 out of 3 error(s). Status Message: Failed to add
     | subscription to management group (Code:Conflict)  Status Message: Failed
     | to add subscription to management group (Code:Conflict)  Status Message:
     | At least one resource deployment operation failed. Please list
     | deployment operations for details. Please see
     | https://aka.ms/arm-deployment-operations for usage details. (Code:
     | DeploymentFailed)  - Failed to add subscription to management group
     | (Code:Conflict)   CorrelationId: c1c64b1b-14dd-43b3-a909-69f493468d35
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
**Does it mean that it will always fail with only one subscription?**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jzryk8** [comment]
No I have used on single and multiple substitutions

**Comment by oZakari** [comment]
Hi @jamesyoung007, as @jzryk8 mentioned, you should be able to place a single subscription. However, make sure that in your parameter file, you don't have the same subscription specified under multiple management groups params or you'll run into a race condition where multiple deployments are going to try and be moving the same subscription under different management group ids. 

![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/6486a720-9197-426f-befa-a81b4e68ee96)

Let me know if that is the issue you're running into. Thanks!

**Comment by jamesyoung007** [comment]
Thanks, I do have the subId in the parameter file as below screenshot,
which I hid for security purposes.

[image: image.png]

**Comment by oZakari** [comment]
Got it, so you'll want to take a look at this [reference architecture](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md) for a single platform subscription management group and single platform subscription. 

I assume you also have the platform management groups (connectivity, identity, and management) deployed as well, so you'll want to delete those and then take a look at the modules that support the `parPlatformMgAlzDefaultsEnable` parameter and set that to false. 

Please re-open if you are still running into issues, happy to help!

**Comment by jamesyoung007** [comment]
Thanks Zach,

1. Deleted platform management groups (connectivity, identity, and
management).
2. Updated parPlatformMgAlzDefaultsEnable value to False in 3 files.
3. Tried to run ALZ-Bicep-3-SubPlacement, failed.

**Comment by oZakari** [comment]
Can you confirm if for your subPlacementAll.parameters.all.json file, that `parPlatformManagementMgSubs`, `parPlatformConnectivityMgSubs`, and `parPlatformIdentityMgSubs` are empty and that you only have that platform subscription included within `parPlatformMgSubs` as shown below:

![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/77219690-9f43-494b-a520-c0afa7593fde)

**Comment by jamesyoung007** [comment]
Yes, it works! Sorry I didn't empty the value and move it to parPlatformMgSubs,
apologies, and thanks a lot, much appreciated, Zach!
