### ISSUE TITLE
Incorporating Modified ALZ Modules - Pipeline failed after following the example

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ALZ-Bicep#737]
### Let us know the feedback or general question

Followed all the steps below:
Example: Steps to follow for ALZ-Bicep Logging, Automation & Sentinel Module
Copy logging.bicep module file from upstream-releases directory to config\custom-modules directory

Modify the copied module file in custom-modules directory as needed. If new parameters are added to the module, you will need to update the relevant parameter file in the config\custom-parameters directory as well.

Update the config\custom-modules\logging.bicep file with the following comment at the top of the file:

// This module has been modified from the upstream-releases version <UpstreamReleaseVersion>

Update the pipeline-scripts\Deploy-ALZLoggingAndSentinel.ps1 file and change the TemplateFile variable to point to the modified module file location as shown below:

[Parameter()]
[String]$TemplateFile = "config\custom-modules\logging.bicep",
In order to trigger new deployments when subsequent changes are made, add the new module file path to the path-based filter workflow trigger in the ALZ-Bicep-1-Core workflow file as shown below:

on:
  push:
    paths:
      - "config/custom-modules/logging.bicep"

![image](https://github.com/Azure/ALZ-Bicep/assets/22153315/7b957824-b60e-44e8-bfe5-c22c1568a68c)
<img width="1323" alt="image" src="https://github.com/Azure/ALZ-Bicep/assets/22153315/ecbae016-0851-4f5a-9e20-56f126823182">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @jamesyoung007, the error looks to be related to the customerUsageAttributes module that is referenced at a particular location in relation to the logging module location.  This module is only used by us to track telemetry data. 

To get around this error, you can copy that module into your custom-module folder and then adjust the path within your logging module, which would be line 249 for the default location. You could also just remove the module reference entirely if you are already opting out as defined by the `parTelemetryOptOut` parameter.

**Comment by oZakari** [comment]
I'll also adjust the wording that for the Accelerator documentation to call this out as something to look out for when moving a module to the custom-modules directory.

**Comment by jamesyoung007** [comment]
Sounds good, thanks for the heads up!
