### ISSUE TITLE
Unable to open protected message for Community Call today, 11th march

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#738]
### Let us know the feedback or general question

Sorry guys for posting this here, but this seems the only way, I am able to get in contact.

I received an email from @jtr with a protected message regarding a Community call. I'm unable to open this message. I tried with my company account, then I would have to send a message to our administrator for enabling access to this application (I don't want to do this), and I tried OTP, then I got: You don't have permission to view this message. What I'm doing wrong?

I'm interessted in the Community Call but I see no way to open this message....
Thanks
Andy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @baartch ,

All details can be found at https://aka.ms/alz/communitycallregister
