### ISSUE TITLE
Add support for Firewall Policy SNAT parameter

### ISSUE THREAD

**Issue by fhpx** [Azure/ALZ-Bicep#739]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

The resource `firewallPolicies` does not currently support the parameter `snat`. 

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Adding "Manually specified IP ranges" to SNAT Exceptions in Azure Portal works fine. But since this is a property of the Firewall Policy this configuration will be removed during redeployment of the hubNetworking-module.

### Can you describe any alternatives that you have taken since this feature does not exist?

Only option I see as of now is to manually re-add configuration in portal, after hubNetworking as been deployed.
Another option would be to deploy a Route Server, and auto-learn private ranges. But it is not desirable to introduce a new paid resource, and dynamic routing, to solve this minor issue.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hey @fhpx, looking at this property it should be something we can incorporate. Will add this to the backlog. Thanks for reaching out!
