### ISSUE TITLE
Feature Request - Implement Budgets - Subscriptions/Management Group

### ISSUE THREAD

**Issue by awood86** [Azure/ALZ-Bicep#741]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Budgets on all subscriptions and management groups

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Quite an important feature for most businesses moving their workloads into the cloud, so budget alerting would be great to increase awareness and ensuring that budgets are aligned

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

When deploying landing zones, I have an additional pipeline/biceps that apply budgets

### Feature Implementation

```Shell
Haven't created a branch but can certainly share
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @awood86, have you seen this policy that can help you do this https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Budget.html

**Comment by jtracey93** [comment]
Also i think this is something we'd probably move from a deployment angle to the Subscription Vending modules, would you agree?

**Comment by awood86** [comment]
> Hey @awood86, have you seen this policy that can help you do this https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Budget.html

I hadn't! But that's certainly a worthwhile policy to implement, thanks for sharing.



> Also i think this is something we'd probably move from a deployment angle to the Subscription Vending modules, would you agree?

Yeah would agree on that too, especially as the core platform subscriptions would be covered under the above mentioned policy

**Comment by oZakari** [comment]
Thanks @jtracey93, feel free to move this issue to the Subscription Vending modules if needed.

**Comment by jtracey93** [comment]
Will link to https://github.com/Azure/bicep-lz-vending/issues/4 and close this one
