### ISSUE TITLE
resErGatewayLock is improperly scoped on resVpnGateway

### ISSUE THREAD

**Issue by DavidLHannah** [Azure/ALZ-Bicep#743]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When you use the _parExpressRouteGatewayLock_ to enable a resource lock on the _resErGateway_ resoucre, the lock _resErGatewayLock_ is in fact created on the _resVpnGateway_ resource.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

When you use the _parExpressRouteGatewayLock_ to enable a resource lock on the _resErGateway_ resource, the lock _resErGatewayLock_ should be created scoped to the _resErGateway_ resource

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Great catch, @DavidLHannah, and thank you for your PR as well!
