### ISSUE TITLE
Deployment alz-bicep-4a-hubspoke fails when AzureFirewall disabled

### ISSUE THREAD

**Issue by jbarrancos** [Azure/ALZ-Bicep#746]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When disabling AzureFirewall in HubSpoke configuration hubNetworking.parameters.all.json:

  _"parAzFirewallEnabled": {
      "value": false
   }_

and having no AzureFirewallSubnet in the _"parSubnets": { }_  It still wants a subnet named AzureFirewallSubnet:

_Resource /subscriptions/xxxxx/resourceGroups/rg-xxxx-connectivity/providers/Microsoft.Network/virtualNetworks/vnt-hub-prd-we-001/subnets/AzureFirewallSubnet not found. (Code: NotFound)_

It seems that this is related to the following part in the: ALZ-Platform\upstream-releases\V0.17.1\infra-as-code\bicep\modules\hubNetworking\hubNetworking.bicep file:

_resource resAzureFirewallSubnetRef 'Microsoft.Network/virtualNetworks/subnets@2023-02-01' existing = {
  parent: resHubVnet
  name: 'AzureFirewallSubnet'
}_

Which should be checking if AzureFirewall is enabled, before expecting the subnet:

_resource resAzureFirewallSubnetRef 'Microsoft.Network/virtualNetworks/subnets@2023-02-01' existing = **if (parAzFirewallEnabled)** {
  parent: resHubVnet
  name: 'AzureFirewallSubnet'
}_

This fixes the issue.

### Please provide the correlation id associated with your error or bug.

c666a676-ac51-4ebc-adf7-50e0b3a73cbb

### What was the expected outcome?

Deployment without expecting FirewallSubnet

### Relevant log output

```Shell
{
  "code": "NotFound",
  "message": "Resource /subscriptions/xxxxx/resourceGroups/rg-xxxx-connectivity/providers/Microsoft.Network/virtualNetworks/vnt-hub-prd-we-001/subnets/AzureFirewallSubnet not found.",
  "details": []
}
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hey @jbarrancos, appreciate you calling out this issue. We do actually have a team member working on improving this specifically for this module. See https://github.com/orgs/Azure/projects/610/views/1?pane=issue&itemId=52291857. I am glad you were able to get it sorted out, and thanks for sharing your approach!

cc: @FallenHoot
