### ISSUE TITLE
Enforce-GR-KeyVault policy is assigned to the wrong scope

### ISSUE THREAD

**Issue by achechen** [Azure/ALZ-Bicep#751]
### What happened? Provide a clear and concise description of the bug, including deployment details.

According to https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#platform Enforce-GR-KeyVault policy assignment should be scoped to Platform management group.

However, https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep assigns it to the Management management group:

```
// Module - Policy Assignment - Enforce-GR-KeyVault
module modPolicyAssignmentMgmtEnforceGrKeyVault '../../../policy/assignments/policyAssignmentManagementGroup.bicep' = if (!contains(parExcludedPolicyAssignments, varPolicyAssignmentEnforceGRKeyVault.libDefinition.name)) {
  scope: managementGroup(varManagementGroupIds.platformManagement)
  name: varModuleDeploymentNames.modPolicyAssignmentMgmtEnforceGrKeyVault
```

### Please provide the correlation id associated with your error or bug.

n/a

### What was the expected outcome?

Enforce-GR-KeyVault policy assignment should be scoped to Platform management group

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Great catch on that @achechen! Would you be interested in submitting a PR to the scope reference in the module you called out?

**Comment by achechen** [comment]
PR submitted: #752
