### ISSUE TITLE
Support for deploying multiple vWAN Hubs in regions which may or may not support Azure Firewall Availability Zones

### ISSUE THREAD

**Issue by simonhutson** [Azure/ALZ-Bicep#759]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

/config/custom-parameters/vwanConnectivity.parameters.all.json provides the ability to create multiple vWAN hubs via the parVirtualWanHubs parameter, but only allows you to specify a single Availability Zone configuration via the parAzFirewallAvailabilityZones parameter.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Many Azure paired regions have a primary region which supports AZs and a satellite region which doesn't (e.g. uksouth and ukwest), and customers often deploy vWAN hubs across paired regions. This means that you can only choose non-zonal Azure Firewall deployments if you are also deploying multiple vWAN hubs in regions with mixed support for AZs.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Good callout on this as this! I will add this to the backlog to be prioritized.
