### ISSUE TITLE
Management Group API is too outdated

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/ALZ-Bicep#760]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Deploying Bicep managementGroups.bicep module fails with `Use a more recent API version...`

### Please provide the correlation id associated with your error or bug.

N/A

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @SvenAelterman, are you potentially using an older version of the module or an older release? Currently, we have 2023-04-01 which is the latest API available for management groups.

**Comment by oZakari** [comment]
Closing this, but please re-open if you need additional assistance.
