### ISSUE TITLE
PowerShell and CLI scripts for mgDiagSettings and mgDiagSettingsAll should register the microsoft.insights provider

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/ALZ-Bicep#765]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

When deploying to new subscriptions, users must manually register the provider.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Less manual intervention required.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @SvenAelterman, within our [ALZ-Bicep Accelerator](https://github.com/Azure/ALZ-Bicep/wiki/Accelerator), which I recommend looking into for deploying the modules, we have a [PowerShell script](https://github.com/Azure/ALZ-Bicep/blob/main/accelerator/pipeline-scripts/Deploy-ALZMGDiagnosticSettings.ps1) which does handle this as part of the automated deployments through GitHub Actions and Azure DevOps.

I'll go ahead and add the script to the module docs for reference though as well.
