### ISSUE TITLE
Sample `all` parameters file for alzDefaultPolicyAssignments.bicep does not include all parameters

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/ALZ-Bicep#766]
### What happened? Provide a clear and concise description of the bug, including deployment details.

At least parameter `parLandingZoneChildrenMgAlzDefaultsEnable` is missing from the "all" parameters sample json file. Others might be missing too.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hey @SvenAelterman, the parameter `parLandingZoneChildrenMgAlzDefaultsEnable` is located [here](https://github.com/Azure/ALZ-Bicep/blob/e43912fa20bdb81fe050e8e5ef0ec9fb796a5e9f/infra-as-code/bicep/modules/policy/assignments/alzDefaults/parameters/alzDefaultPolicyAssignments.parameters.all.json#L21). Will be closing but reach out if you have any other questions!
