### ISSUE TITLE
ALZ AMA

### ISSUE THREAD

**Issue by integyjc** [Azure/ALZ-Bicep#782]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Can you advise if the BiCep version of ALZ has been updated to deploy the AMA agent exclusively? https://github.com/Azure/Enterprise-Scale/wiki/ALZ-AMA-Update

And if not when this might happen? Thanks

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Rolling out new customer deployments with the LA agent is not ideal with deprecation happening in August

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @integyjc,

thanks for the issue. We have not yet moved ALZ Bicep to AMA or replacement for MMA. 

We have just finished getting a number of built-in policies updated to enable us to complete this migration however, which we are planning for June 2024, providing the rollout of the updates to the built-in policies complete as expected (currently looking good). We have this documented here: https://github.com/orgs/Azure/projects/487?pane=issue&itemId=30803412

Thanks

cc: @paulgrimley @arjenhuitema

**Comment by integyjc** [comment]
Thanks @jtracey93 sorry I should have spotted that on the roadmap.

Fingers crossed for June
