### ISSUE TITLE
Azure Bastion Kerberos Authentication

### ISSUE THREAD

**Issue by gerrynicol** [Azure/ALZ-Bicep#783]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Not a bug this one, but more a question on the architecture relating to Azure Bation. If you want to use kerberos with Azure Bastion it seems like you have to have the Domain Controllers in the same vNET as your Bastion resource. This goes against the main landing zone design with the identity resources being separated and in their own Subscription. Can youprovide further guidance on this please.

### Please provide the correlation id associated with your error or bug.

https://learn.microsoft.com/en-us/azure/bastion/kerberos-authentication-portal

Considerations
The Kerberos setting for Azure Bastion can be configured in the Azure portal only and not with native client.
VMs migrated from on-premises to Azure aren't currently supported for Kerberos. 
Cross-realm authentication isn't currently supported for Kerberos.
The Domain controller must be an Azure Hosted VM within the same VNET that bastion is deployed.

### What was the expected outcome?

N\A

### Relevant log output

```Shell
N\A
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Thanks for the issue @gerrynicol, ive unmarked as a bug for now. 

We'll reach out to the bastion PG to confirm why this is and discuss with them.

In the meantime have you tried deploying it in the ALZ aligned way, e.g. the DCs in the identity subscription and bastion in another vNet and connected via vnet peering? Does it actually work as I have a suspicion it should and the docs may be misleading.

Let me know if you are able to test and confirm

Thanks

Jack

#RR

**Comment by gerrynicol** [comment]
Thanks @jtracey93. On initial testing it does appear not to work. The set up is as follows
- DC in Identity vNET peered to HUB
- Bastion in Hub (Basic SKU)
- Workload in Spoke peered vNET to HUB

Bastion seems to work ok to the Workload in the Spoke when Kerberos Authentication is unticked. (For this it seems to be using NTLM auth). When it is then ticked Bastion connectivity then fails.

**Comment by jtracey93** [comment]
Have you tried with the standard SKU?

**Comment by gerrynicol** [comment]
Have just tested with Standard and it looks like the same issue.

**Comment by oZakari** [comment]
Just an update that we are in contact with the product group and are just waiting them to confirm.

**Comment by oZakari** [comment]
Hi @gerrynicol, we have received confirmation from the product group that Azure Bastion Kerberos does indeed have a limitation which requires the resource to be in the same VNet as the domain controller VM(s).

We have opened an internal feedback item for the product group to investigate so they can work towards offering a workaround, or ideally remove the limitation entirely. 

We will be adding a disclaimer to the CAF document adding this disclaimer this our [CAF documentation](https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-virtual-machine-remote-access) as we do realize this is currently a blocker for adopting this feature in terms of staying aligned to the ALZ guidance.
