### ISSUE TITLE
Running pipeline with IS_PULL_REQUEST: "true" causes failure

### ISSUE THREAD

**Issue by integyjc** [Azure/ALZ-Bicep#784]
### What happened? Provide a clear and concise description of the bug, including deployment details.

We are attempting to run the policy assignments pipeline with the IS_PULL_REQUEST: "true" variable set within the pipeline file. This causes the pipeline to fail with the following error:

New-AzManagementGroupDeployment: /home/vsts/work/1/s/pipeline-scripts/Deploy-ALZPolicyAssignments.ps1:29
Line |
  29 |  New-AzManagementGroupDeployment @inputObject
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Additional content found in JSON reference object. A JSON reference
     | object should only have a $ref property. Path
     | 'parTopLevelPolicyAssignmentSovereigntyGlobal.defaultValue'.
##[error]PowerShell exited with code '1'.

The deployment will succeed if we set the pull request variable to false.

Can anyone advise if this is a bug or something we are doing wrong? Many thanks 

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

The ability to receive a what-if report of the deployment prior to running it in production. 

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @integyjc, this is a known issue with Az PowerShell. Please see the following [wiki](https://github.com/Azure/ALZ-Bicep/wiki/KnownIssues#issue-1-what-if-check-fails-within-azure-devops-pipelinegithub-actions-workflow-with-the-error-additional-content-found-in-json-reference-object-a-json-reference-object-should-only-have-a-ref-property-path-parresourcelockconfigdefaultvalue) for reference and how to get around it.

Will go ahead and close this, but please respond back if you still have any other questions.
