### ISSUE TITLE
How to Integrate AzureMonitorBaseline Alerts needs some work

### ISSUE THREAD

**Issue by ThojoUno** [Azure/ALZ-Bicep#796]
### What happened? Provide a clear and concise description of the bug, including deployment details.

https://github.com/Azure/ALZ-Bicep/wiki/AzureMonitorBaselineAlerts
Instructions show how to copy patterns/alz to local repo and execute, but pipeline script still references TemplateUri, so you are still using remote repo. To replace TemplateUri with TemplateFile will require modification to alzArm.json and update deploymentUri linked templates.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @ThojoUno, thanks for catching that. I will go ahead and get that switched out.

**Comment by oZakari** [comment]
Closing this as the existing guidance is specific to the Classic ALZ Bicep Accelerator which has been deprecated. We are working with the AMBA team to build the proposed ALZ AMBA Pattern Module as noted [here](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-pattern-modules/).
