### ISSUE TITLE
custom-parameters, azuredevops\pipelines and pipeline scripts

### ISSUE THREAD

**Issue by gerrynicol** [Azure/ALZ-Bicep#813]
### Let us know the feedback or general question

Hi there,

Quick question on the above three folders in the directory tree. If I want to customise the names in the parameter files in custom-parameters is the best option to create new parameter files in the custom-parameters folder (as otherwise the vaules I set seem to  get overwritten with every new release). I undertsand I would then have to update the devops pipeline scripts to reflect this. Also I would have to update the Deploy*.ps1 scripts in the pipeline-scripts folder. Or is there any easier way to do this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gerrynicol** [comment]
I think I've got a solution to this. After updating the parameterf i;es with my updated resource names, just take a copy of the parameter files and place in the custom-modules folder. After an update, just replace the 'new ones' with the saved ones.. Also have to update the .env file. Is this a sensible solution?

**Comment by oZakari** [comment]
Hi @gerrynicol,

You have uncovered a bug. 🙂 Your temporary solution makes sense, but we will work on fixing that. The parameter files should not be replaced during an upgrade. We need to add a toggle to the Deploy-Accelerator cmdlet to prevent it from affecting the custom-parameters directory.


A new version of the Accelerator is coming out soon. While we will continue to support the old Accelerator for some time, we recommend checking out the new version, which will be included in release v0.19.0.
