### ISSUE TITLE
Migrating to V2

### ISSUE THREAD

**Issue by benhogg** [Azure/ALZ-Bicep#818]
### Let us know the feedback or general question

Hi,

I noticed that V2 of the accelerator has been released and on the V1 accelerator page (https://github.com/Azure/ALZ-Bicep/wiki/Accelerator) It states

"The classic version of the ALZ Bicep Accelerator will be maintained for a limited time. We recommend migrating to the new version as soon as possible."

Is there any guidance or best practice on how to migrate existing deployments to the new V2 environment?

Thanks 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @benhogg, the V2 Accelerator is quite a bit different in terms of how it is orchestrated and managed. Therefore, I would recommend deploying the V2 version as if you were starting from scratch. Then before deploying anything, create a new pull request which overwrites/modifies the modules and parameters to mimic what you currently have deployed from a Bicep module perspective. Then before merging your PR and deploying you can use the what-if operator to ensure there are no changes in terms of the ALZ-Bicep resources. 

As a note, we will be releasing the [AVM pattern modules ](https://github.com/Azure/ALZ-Bicep/issues/791)likely towards the end of the calendar year so if you want to wait until then that should be fine as well. I will try to add it bit more clarity for the docs around this as well, but if you need any additional clarification please feel free to reach back out to this issue!
