### ISSUE TITLE
Deploy-Diagnotics-LogAnalytics Diag Settings leads to non-compliant resource in Azure Policy

### ISSUE THREAD

**Issue by coriet** [Azure/ALZ-Bicep#820]
### Let us know the feedback or general question

Currently 'policy_definition_es_Deploy-Diagnostics-LogAnalytics.json' mentions that the deployed 'Policy will set the diagnostic with all metrics and category enabled', however "Summary Logs" are missing. Therefore the policy will always show non-compliant resources in Azure Policy.

Changing from:

"logs": [
      {
        "category": "Audit",
        "enabled": "[parameters('logsEnabled')]"
      }
 ]

To:

"logs": [
      {
        "category": "Audit",
        "enabled": "[parameters('logsEnabled')]"
      },
      {
        "category": "SummaryLogs",
        "enabled": "[parameters('logsEnabled')]"
      }
 ]

Will fix the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @coriet,

In the [last policy refresh of ALZ](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#-policy-refresh-h2-fy24:~:text=Diagnostic%20Settings%20v2%20have%20arrived%20covering%20140%20Azure%20services%20and%20greatly%20simplifying%20implementation%20and%20management.) we moved away from the custom diagnostic settings policies we used to the new [built-in initiatives](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/0884adba-2312-4468-abeb-5422caed1038.html) for this that utilise category groups that avoid these scenarios from occurring.

Have you updated to the latest release of ALZ Bicep and adopted this change as per the release notes? https://github.com/Azure/ALZ-Bicep/releases

> N.B. the policy refresh work occurred in `v0.18.0`

**Comment by coriet** [comment]
Thank you @jtracey93 I will do so. Thank you for the feedback.
