### ISSUE TITLE
Bug-Issue with ALZ Default Policy Assignments Module resulting in file exceeded 4 MB size

### ISSUE THREAD

**Issue by oZakari** [Azure/ALZ-Bicep#821]
### What happened? Provide a clear and concise description of the bug, including deployment details.

There is an issue with the size of the ALZ Default Policy Assignments module and the child modules it instantiates. This issue will occur depending upon the size of your parameter file which is where this issue came up. As such, need to reduce comment sizes and/or reduce descriptions as a starting point. 

### Please provide the correlation id associated with your error or bug.

N/A

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxgaulhofer** [comment]
Any update for this issue? or workarround?

**Comment by oZakari** [comment]
Hi @maxgaulhofer, just submitted a PR (referenced above) to help mitigate this for most scenarios. Within that PR you'll also see that I've added this as a known issue, so if you are adding custom policies assignments to the module, it provides some approaches for getting around.

**Comment by Anto4595** [comment]
@jtracey93 @oZakari Any workaround on this issue. as I am on this. Any alternate way we have.

**Comment by jtracey93** [comment]
See https://github.com/Azure/ALZ-Bicep/pull/831/files#diff-dece681ec0c3e90a251c83f793984ecaa9384ba2b7c2be50900206934222fb20
