### ISSUE TITLE
Bicep Code to Full Code

### ISSUE THREAD

**Issue by Anto4595** [Azure/ALZ-Bicep#824]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Hello @jtracey93 

I am trying the bicep Code. And I can able to see in GitHub repo for each resource creation we have Management group, policy and etc we need to run one by one.

Do we have overall bicep code that can be run so that once the Management is created. then the subscriptions and resources and policies.

Just Like how we deploy in Portal where deploys one by one. Do we have something in Bicep.

Awaiting Reply...

Thank You....

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

NA

### Please provide the correlation id associated with your error or bug.

NA

### Can you describe any alternatives that you have taken since this feature does not exist?

NA

### Feature Implementation

```Shell
NA
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hi @Anto4595 

There is no single bicep deployment to do it all. Each module is separate and needs to be deployed in the correct order as defined here: https://github.com/Azure/ALZ-Bicep/wiki/DeploymentFlow

Hope that helps
