### ISSUE TITLE
Logging module includes property `sku` for sentinel

### ISSUE THREAD

**Issue by picccard** [Azure/ALZ-Bicep#828]
Logging module template includes a non-allowed "sku" property for `microsoft.operationsmanagement/solutions`

Template-spec for the resource does not include the sku-property, I'm guessing the RP modified the existing template-spec-api to remove the sku-property sometime after the [simplified-pricing(`Unified`)](https://learn.microsoft.com/en-us/azure/sentinel/enroll-simplified-pricing-tier?tabs=microsoft-sentinel#change-pricing-tier-to-simplified) was introduced.

https://learn.microsoft.com/en-gb/azure/templates/microsoft.operationsmanagement/solutions?pivots=deployment-language-bicep

![image](https://github.com/user-attachments/assets/82c0e7bd-7f6f-4218-bf43-a0d48a199208)

**Comment by oZakari** [comment]
Hi @picccard, that makes sense to me as well. @jtracey93 is this something we can remove or was this supporting some edge case that it needs to stay in?

**Comment by jtracey93** [comment]
This was done way back in https://github.com/Azure/ALZ-Bicep/pull/582 relating to https://learn.microsoft.com/azure/sentinel/enroll-simplified-pricing-tier?tabs=microsoft-sentinel#change-pricing-tier-to-simplified and i introduced it in a non-breaking way.

The API version it was pinned to should still support the deployment and bicep linter may be incorrectly flagging this, have you deployed it @picccard to confirm?

Happy for it to be removed if not needed, but to my understanding it should be fine to leave to cover customers using the classic pricing tier

**Comment by oZakari** [comment]
Just tested it, and the classic pricing model still works with this API version so will leave it in.
