### ISSUE TITLE
How can I configure to store the script in GitHub Via Bicep

### ISSUE THREAD

**Issue by Anto4595** [Azure/ALZ-Bicep#830]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Hello @jtracey93, @Springstone 

I have a question regarding Azure Bicep. I had a look at the link on how we can deploy a new Enterprise Scale Environment using Azure Bicep.

https://github.com/Azure/ALZ-Bicep/wiki/DeploymentFlow

Also I checked the videos how you guys are deploying it.

So if I am making the changes in the parameters and bicep file for each module and deploying it for my environment how can I make it available in the GitHub Repos. Any configuration should I need to additionally or anything you can share related to this.

Thank You...

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

NA

### Please provide the correlation id associated with your error or bug.

NA

### Can you describe any alternatives that you have taken since this feature does not exist?

NA

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anto4595** [comment]
Hello @jtracey93 

Thank you for sharing.

So we have a GitHub Organization and we want to to move the deployments that we do using Bicep https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules

Which one should I go with https://github.com/Azure/ALZ-Bicep/tree/main/accelerator

Do you have any video step by step explaining it. ?

**Comment by oZakari** [comment]
Closing for now, but feel free to respond here with any other questions. On the other hand, if you run into issues or potential bugs with the Accelerator, please feel free to open a new issue.
