### ISSUE TITLE
Are you sure 'parUserAssignedManagedIdentityResourceId' is optional?

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#855]
### What happened? Provide a clear and concise description of the bug, including deployment details.

While upgrading from `v0.17.4` to `v0.18.0` using the Accelerator V1 I get the error:

```
New-AzManagementGroupDeployment: /home/vsts/work/1/s/pipeline-scripts/Deploy-ALZPolicyAssignments.ps1:29
Line |
  29 |  New-AzManagementGroupDeployment @inputObject
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  InvalidTemplate - Long running operation failed with status 'Failed'.
     | Additional Info:'Deployment template validation failed: 'The template
     | variable 'varUserAssignedManagedIdentityResourceName' is not valid: The
     | language expression property array index '8' is out of bounds.. Please
     | see https://aka.ms/arm-functions for usage details.'.'

```

In my opinion the error is caused by this [line](https://github.com/Azure/ALZ-Bicep/blob/79b1fbbc20c94b3f3c805f5abd05cfe855ae5871/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep#L125).
```bicep
var varUserAssignedManagedIdentityResourceName = split(parUserAssignedManagedIdentityResourceId, '/')[8]
```

I think it cannot work, when a few lines [above](https://github.com/Azure/ALZ-Bicep/blob/79b1fbbc20c94b3f3c805f5abd05cfe855ae5871/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep#L78) and in the [docs](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/generateddocs/alzDefaultPolicyAssignments.bicep.md) the param `parUserAssignedManagedIdentityResourceId` is optional.
```bicep
param parUserAssignedManagedIdentityResourceId string = ''
```

Am I missing something? Has the UAMI to be created manually?

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baartch** [comment]
Ok. I figured it out.

I installed an old version of the PS Module and ran the command to create a new enviroment into a temp directory and compared the files in `custom-parameters` afterwards.
```bash
Install-Module -Name ALZ -RequiredVersion "1.1.6"
New-ALZEnvironment -alzEnvironmentDestination "tmp" -alzBicepVersion "v0.18.0"
```
I had to add some parameters to my files.

**Comment by oZakari** [comment]
Hey @baartch, I'll update the parameters that it is a required param as well.
