### ISSUE TITLE
Question - How to override/modify a policy?

### ISSUE THREAD

**Issue by cspring86** [Azure/ALZ-Bicep#859]
### Let us know the feedback or general question

I've got a general question about policies.

Apologies if this is already answered in the documentation, but I couldn't see anything, so here's the question.

Is there any way to override or modify a policy?

For example, I'd like to change a policy's effect from "Deny" to "Audit".

Ideally, I'd like to do this through the repository created by the accelerator so all changes are tracked through version control.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @cspring86, here are the [steps ](https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies#how-do-i-extend-the-alz-bicep-alz-default-policy-assignments-module) for extending the ALZ Default Policy Assignments module. 

You can override the `templateFilePath` directory property within the bicep-templates.yaml file for the ALZ Default Policy Assignments module with a custom module as well as a custom `lib` directory as well. 

![image](https://github.com/user-attachments/assets/e67724ab-f210-4d26-9270-7580144e4c62)
