### ISSUE TITLE
Release 0.19.4 missing accelerator.zip and -.tar.gz

### ISSUE THREAD

**Issue by xhoogland** [Azure/ALZ-Bicep#871]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I have executed the following line in PowerShell 7.4.5 (as tab in Windows Terminal):
Deploy-Accelerator -inputs D:\xxx\accelerator\config\inputs.yaml -targetDirectory D:\xxx\accelerator\output

This used to work in the previous combination of the last 3.x-version for the bootstrap and 0.19.3 for the starter. I am using the combination of bicep, alz_azuredevops and starter complete.

### Please provide the correlation id associated with your error or bug.

N/a.

### What was the expected outcome?

That the script created a terraform which I could perhaps apply.

### Relevant log output

```Shell
Getting ready to deploy the accelerator with you...

Checking you have the latest version of Terraform installed...
Although you have selected Bicep, the Accelerator leverages the Terraform tool to bootstrap your Version Control System and Azure. This is will not impact your choice of Bicep post this initial bootstrap. Please refer to our documentation for further details...

Checking and Downloading the bootstrap module...
The directory for D:\xxx\accelerator\output\bootstrap\v4.0.1 has been created and populated.

Checking and downloading the starter module...
Invoke-WebRequest: C:\path\to\PowerShell\Modules\ALZ\4.0.0\Private\Shared\Get-GithubRelease.ps1:126
Line |
 126 |          Invoke-WebRequest -Uri $releaseArtifactUrl -OutFile $targetPa …
     |                                 ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
Failed to download the release v0.19.4 from the GitHub repository Azure/ALZ-Bicep
Exception: C:\path\to\PowerShell\Modules\ALZ\4.0.0\Private\Shared\Get-GithubRelease.ps1:130
Line |
 130 |              throw
     |              ~~~~~
     | ScriptHalted
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-novak-80** [comment]
I back this up, am encountering the same issue.

**Comment by jtracey93** [comment]
Thanks both @xhoogland & @michael-novak-80 ,

Can you confirm you have upgrade the ALZ PowerShell module to the latest version `v4.0.0` https://github.com/Azure/ALZ-PowerShell-Module/releases/tag/4.0.0 & https://www.powershellgallery.com/packages/ALZ/4.0.0

If not please upgrade and try again and let us know 👍 

cc: @jaredfholgate  @oZakari

**Comment by michael-novak-80** [comment]
Yes, am on v. 4.0.0 ALZ module, previous versions removed and reinstalled from scratch. 

> Thanks both @xhoogland & @michael-novak-80 ,
> 
> Can you confirm you have upgrade the ALZ PowerShell module to the latest version `v4.0.0` https://github.com/Azure/ALZ-PowerShell-Module/releases/tag/4.0.0 & https://www.powershellgallery.com/packages/ALZ/4.0.0
> 
> If not please upgrade and try again and let us know 👍
> 
> cc: @jaredfholgate @oZakari

**Comment by xhoogland** [comment]
Yes, I can confirm. Not behind my laptop currently but Update-Module
-WhatIf does not show this module anymore.
This morning it did and afterwards I executed Update-Module.

**Comment by jaredfholgate** [comment]
The artifacts are there now. Apologies there was an issue with our workflow trigger.

**Comment by michael-novak-80** [comment]
Many thanks for fixing this.

**Comment by jaredfholgate** [comment]
Referencing the PR: https://github.com/Azure/ALZ-Bicep/pull/872

**Comment by xhoogland** [comment]
Nice fast fix, thanks!
