### ISSUE TITLE
Missing policy assignment - Subnets should be private

### ISSUE THREAD

**Issue by brotheroneill** [Azure/ALZ-Bicep#878]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I'm struggling to locate a policy assignment and have to assume it's been missed, or there's a compelling reason why it's not being assigned? it's one of the built-in one that's referenced in the [Enterprise Scale ALZ Policy xlsx](https://github.com/Azure/Enterprise-Scale/wiki/media/ALZ%20Policy%20Assignments%20v2.xlsx) called 'Subnets should be private', suggesting it's assigned at both Platform and Landing Zones scope. 

I should point out that we're a couple of versions behind at the moment, and I've identified this as part of a gap analysis to validate what's changing between our current and your latest version of the repo. I've not deployed the latest to see if the assignment actually shows in the portal yet, but have reviewed the assignments in alzDefaultPolicyAssignments.bicep and couldn't identify it. 

I _think_ this is being raised in the right place, as the assignments are maintained here with the definitions and initiatives being pulled from the Enterprise Scale repo. 

### Please provide the correlation id associated with your error or bug.

n/a

### What was the expected outcome?

I'd expect to see the policy assignment in the `alzDefaultPolicyAssignments.bicep` file, but can't. I've also looked for anything that resembles it but is called something else like `...-defaultOutboundAccess` etc., but no joy. 

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hey @brotheroneill,

We haven't ingested the policy refresh yet that happened last week in ALZ. This is on the plan to complete by the end of this month.

Hope that helps

If you need it in the meantime you can add a custom assignment as per the wiki (https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies) using the assignment file from the portal here as inspiration: https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-SubnetPrivatePolicyAssignment.json

Thanks

Jack
