### ISSUE TITLE
How to clean up?

### ISSUE THREAD

**Issue by raffertyuy** [Azure/ALZ-Bicep#882]
Hi, I deployed a deprecated version of this ALZ Accelerator and I'm hoping to clean up and start afresh.
Is there any guidance on how to clean up?

**Comment by oZakari** [comment]
Hi @raffertyuy,

If you're in a lab environment and want to test the new accelerator, you can use the script available in this [directory](https://github.com/jtracey93/PublicScripts/tree/master/Azure/PowerShell/Enterprise-scale) to completely remove your existing deployment from the Classic Accelerator. Please note that this script is **not** directly owned or managed by Microsoft. It was created by Microsoft's ALZ Technical Lead, but it will fully wipe everything in your environment. Be sure to read the README carefully to understand the script before running it.

If you're in a production environment, it might be better to wait on migrating to the new Accelerator. We have a [refactor](https://github.com/Azure/ALZ-Bicep/issues/791) in progress for ALZ-Bicep to incorporate Azure Verified Modules, expected around January. Holding off would reduce the effort on your end, as the only major change in the current deployment is the pipeline model.
