### ISSUE TITLE
Tags not set on managed identity/DCRs in the logging module

### ISSUE THREAD

**Issue by earldata** [Azure/ALZ-Bicep#883]
### What happened? Provide a clear and concise description of the bug, including deployment details.

parTags is not set on the managed identity or data collection rules in logging.bicep.  This causes an issue for organisations with mandatory tagging policies.

https://github.com/Azure/ALZ-Bicep/blob/546b9fd1b2f68d37d24641adeeddfe0ace542c30/infra-as-code/bicep/modules/logging/logging.bicep#L188
https://github.com/Azure/ALZ-Bicep/blob/546b9fd1b2f68d37d24641adeeddfe0ace542c30/infra-as-code/bicep/modules/logging/logging.bicep#L244
https://github.com/Azure/ALZ-Bicep/blob/546b9fd1b2f68d37d24641adeeddfe0ace542c30/infra-as-code/bicep/modules/logging/logging.bicep#L312
https://github.com/Azure/ALZ-Bicep/blob/546b9fd1b2f68d37d24641adeeddfe0ace542c30/infra-as-code/bicep/modules/logging/logging.bicep#L583

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @earldata, I will add these in this week. Thanks for calling it out.
