### ISSUE TITLE
Errors when deploying ALZ Bicep custom policies

### ISSUE THREAD

**Issue by sweprs** [Azure/ALZ-Bicep#885]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Hi

We have the same error as in #769 and #326

We see that some of the policys/policy sets gets deployed but we get the error as in #769 and #326 despite rerunning the job several times.

We run our deployment in a Azude DevOps pipeline and we clone the ALZ repo and then deploy it with the following powershell code.
Its my understanding that if we change and pass the parameter for the ManagementGroupId (our own mg-group id) as below this will be used and not the 'alz' in the customPolicyDefinitions.parameters.all.json

Or do we need to change the value in customPolicyDefinitions.parameters.all.json?

$inputObject = @{
      DeploymentName        = -join ('alz-PolicyDefsDeployment-{0}' -f (Get-Date -Format 'yyyyMMddTHHMMssffffZ'))[0..63]
      Location              = 'swedencentral'
      ManagementGroupId     = 'our own intermediate root'
      TemplateFile          = "ALZ-Bicep/infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep"
      TemplateParameterFile = 'ALZ-Bicep/infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json'}

      New-AzManagementGroupDeployment @inputObject

### Please provide the correlation id associated with your error or bug.

73f8511f-ac4b-4e79-a868-273f8f730ecf

### What was the expected outcome?

That all the policies and policy sets should be deployed

### Relevant log output

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-Guardrails-Network' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-AppGw-Without-Tls,Deny-MgmtPorts-From-Internet,Deny-Service-Endpoints,Deny-Subnet-Without-Nsg,Deny-Subnet-Without-Udr,Modify-NSG,Modify-UDR'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deploy-MDFC-Config_20240319' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-ASC-SecurityContacts'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deny-PublicPaaSEndpoints' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-LogicApp-Public-Network'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-Encryption-CMK' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-EH-Premium-CMK'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deploy-Sql-Security_20240529' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Sql-AuditingSettings,Deploy-Sql-SecurityAlertPolicies,Deploy-Sql-vulnerabilityAssessments_20230706'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-Guardrails-AppServices' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-AppService-without-BYOC'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-ALZ-Decomm' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Vm-autoShutdown'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'DenyAction-DeleteProtection' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'DenyAction-ActivityLogs,DenyAction-DiagnosticLogs'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-Guardrails-Storage' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-Storage-ContainerDeleteRetentionPolicy,Deny-Storage-CopyScope,Deny-Storage-CorsRules,Deny-Storage-LocalUser,Deny-Storage-NetworkAclsBypass,Deny-Storage-NetworkAclsVirtualNetworkRules,Deny-Storage-ResourceAccessRulesResourceId,Deny-Storage-ResourceAccessRulesTenantId,Deny-Storage-ServicesEncryption,Deny-Storage-SFTP'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-ALZ-Sandbox' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-VNET-Peer-Cross-Sub'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deploy-Diagnostics-LogAnalytics' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Diagnostics-ACI,Deploy-Diagnostics-ACR,Deploy-Diagnostics-AnalysisService,Deploy-Diagnostics-ApiForFHIR,Deploy-Diagnostics-APIMgmt,Deploy-Diagnostics-ApplicationGateway,Deploy-Diagnostics-WebServerFarm,Deploy-Diagnostics-Website,Deploy-Diagnostics-AA,Deploy-Diagnostics-AVDScalingPlans,Deploy-Diagnostics-Bastion,Deploy-Diagnostics-CDNEndpoints,Deploy-Diagnostics-CognitiveServices,Deploy-Diagnostics-CosmosDB,Deploy-Diagnostics-Databricks,Deploy-Diagnostics-DataExplorerCluster,Deploy-Diagnostics-DataFactory,Deploy-Diagnostics-DLAnalytics,Deploy-Diagnostics-EventGridSub,Deploy-Diagnostics-EventGridTopic,Deploy-Diagnostics-EventGridSystemTopic,Deploy-Diagnostics-ExpressRoute,Deploy-Diagnostics-Firewall,Deploy-Diagnostics-FrontDoor,Deploy-Diagnostics-Function,Deploy-Diagnostics-HDInsight,Deploy-Diagnostics-iotHub,Deploy-Diagnostics-LoadBalancer,Deploy-Diagnostics-LogAnalytics,Deploy-Diagnostics-LogicAppsISE,Deploy-Diagnostics-MariaDB,Deploy-Diagnostics-MediaService,Deploy-Diagnostics-MlWorkspace,Deploy-Diagnostics-MySQL,Deploy-Diagnostics-NIC,Deploy-Diagnostics-NetworkSecurityGroups,Deploy-Diagnostics-PostgreSQL,Deploy-Diagnostics-PowerBIEmbedded,Deploy-Diagnostics-RedisCache,Deploy-Diagnostics-Relay,Deploy-Diagnostics-SignalR,Deploy-Diagnostics-SQLElasticPools,Deploy-Diagnostics-SQLMI,Deploy-Diagnostics-TimeSeriesInsights,Deploy-Diagnostics-TrafficManager,Deploy-Diagnostics-VM,Deploy-Diagnostics-VirtualNetwork,Deploy-Diagnostics-VMSS,Deploy-Diagnostics-VNetGW,Deploy-Diagnostics-VWanS2SVPNGW,Deploy-Diagnostics-WVDAppGroup,Deploy-Diagnostics-WVDHostPools,Deploy-Diagnostics-WVDWorkspace'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deploy-MDFC-DefenderSQL-AMA' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-MDFC-SQL-AMA,Deploy-MDFC-Arc-SQL-DCR-Association,Deploy-MDFC-Arc-Sql-DefenderSQL-DCR,Deploy-MDFC-SQL-DefenderSQL,Deploy-MDFC-SQL-DefenderSQL-DCR'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-Guardrails-APIM' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-APIM-TLS'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-EncryptTransit' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-AppServiceApiApp-http,Append-AppService-httpsonly,Append-AppService-latestTLS,Deny-AppServiceFunctionApp-http,Deploy-MySQL-sslEnforcement,Deny-MySql-http,Deploy-PostgreSQL-sslEnforcement,Deny-PostgreSql-http,Deny-Redis-http,Append-Redis-disableNonSslPort,Append-Redis-sslEnforcement,Deploy-SqlMi-minTLS,Deny-SqlMi-minTLS,Deploy-SQL-minTLS,Deny-Sql-minTLS,Deploy-Storage-sslEnforcement,Deny-Storage-minTLS,Deny-AppServiceWebApp-http'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deploy-Sql-Security' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Sql-AuditingSettings,Deploy-Sql-SecurityAlertPolicies,Deploy-Sql-vulnerabilityAssessments'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-Guardrails-OpenAI' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-CognitiveServices-NetworkAcls,Deny-CognitiveServices-RestrictOutboundNetworkAccess'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Enforce-EncryptTransit_20240509' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-AppServiceApiApp-http,Append-AppService-httpsonly,Append-AppService-latestTLS,Deny-EH-minTLS,Deny-LogicApps-Without-Https,Deploy-LogicApp-TLS,Deny-AppServiceFunctionApp-http,Deploy-MySQL-sslEnforcement,Deny-MySql-http,Deploy-PostgreSQL-sslEnforcement,Deny-PostgreSql-http,Deny-Redis-http,Append-Redis-disableNonSslPort,Append-Redis-sslEnforcement,Deploy-SqlMi-minTLS,Deny-SqlMi-minTLS,Deploy-SQL-minTLS,Deny-Sql-minTLS,Deploy-Storage-sslEnforcement,Deny-AppServiceWebApp-http'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Audit-UnusedResourcesCostOptimization' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Audit-AzureHybridBenefit,Audit-Disks-UnusedResourcesCostOptimization,Audit-PublicIpAddresses-UnusedResourcesCostOptimization,Audit-ServerFarms-UnusedResourcesCostOptimization'."},{"code":"InvalidCreatePolicySetDefinitionRequest","message":"The policy set definition 'Deploy-MDFC-Config' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-ASC-SecurityContacts'."}]}

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @sweprs, the `[ManagementGroupId](https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azmanagementgroupdeployment?view=azps-12.4.0#-managementgroupid)` in the `New-AzManagementGroupDeployment` PowerShell cmdlet is separate from the `parTargetManagementGroupId` Bicep parameter, so setting the `managementgroupId` will not override that value.

As it stands, `parTargetManagementGroupId` is used to create the variable `varTargetManagementGroupResourceId`, which generates a tenant-level resource ID. This tenant-level resource ID is then explicitly used to determine where custom policy definitions are deployed. This is why you’re encountering an error for each policy definition that references this variable—since the `ALZ` (default value for the parameter) isn't found at the `ManagementGroupID` scope.

To resolve this, set the parameter to your intermediate root management group ID either within the parameters file directory or overwriting the actual Bicep parameter using the PowerShell cmdlet as follow.
```
inputObject = @{
   DeploymentName        = -join ('alz-PolicyDefsDeployment-{0}' -f (Get-Date -Format 'yyyyMMddTHHMMssffffZ'))[0..63]
   Location              = 'eastus'
   ManagementGroupId     = ''your-intermediate-root-management-group-id'
   TemplateFile          = "infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep"
   TemplateParameterFile = 'infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json'
   parTargetManagementGroupId 'your-intermediate-root-management-group-id'
   }

   New-AzManagementGroupDeployment @inputObject
```

The remaining custom policies should deploy without issue, but feel free to re-open if you have questions.
