### ISSUE TITLE
Hub vNET Subnet Delegation

### ISSUE THREAD

**Issue by gerrynicol** [Azure/ALZ-Bicep#886]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I am trying to create a subnet for the dns resolver in the Hub vnet using the hubNetworking.parameters.all.json file and setting the delegations parameter as below. The deployment succeeds but the delegationon on the subnet is not applied. 

          "delegations": [
            {
              "name": "Microsoft.Network/dnsResolvers",
              "properties": {
                "serviceName": "Microsoft.Network/dnsResolvers"
              }
            }
          ]

### Please provide the correlation id associated with your error or bug.

no error

### What was the expected outcome?

The delegation Microsoft.Network/dnsResolvers is added to the subnet

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @gerrynicol, delegations are a part of the parSubnets parameter which is an array of objects. To delegate a service to a subnet, you can use something similar to the following as an example within your parameters file.

```json
"parSubnets": {
      "value": [
        {
          "name": "DNSResolveSubnetr",
          "ipAddressRange": "10.20.0.0/24",
          "networkSecurityGroupId": "",
          "routeTableId": "",
          "delegation": "Microsoft.Network/dnsResolvers"
        },
        {
          "name": "GatewaySubnet",
          "ipAddressRange": "10.20.254.0/24",
          "networkSecurityGroupId": "",
          "routeTableId": ""
        },
        {
          "name": "AzureFirewallSubnet",
          "ipAddressRange": "10.20.255.0/24",
          "networkSecurityGroupId": "",
          "routeTableId": ""
        },
        {
          "name": "AzureFirewallManagementSubnet",
          "ipAddressRange": "10.20.253.0/24",
          "networkSecurityGroupId": "",
          "routeTableId": ""
        },
        {
          "name": "PrivateDNSResolver",
          "ipAddressRange": "10.10.255.0/24",
          "networkSecurityGroupId": "",
          "routeTableId": "",
          "delegation": "Microsoft.Network/dnsResolvers"
        }
      ]
    }
```

This should fix it for you, but please feel free to re-open if you ahve remaining questions.
