### ISSUE TITLE
PLEASE VOTE: Symbolic Names For Parameters, Variables, Resources, Modules & Outputs

### ISSUE THREAD

**Issue by jtracey93** [Azure/ALZ-Bicep#89]
As documented in our [Contributing wiki page](https://github.com/Azure/ALZ-Bicep/wiki/Contributing#bicep-elements-naming-standards) (also shown in the table below) we follow the [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) naming pattern for our symbolic names in all our code and modules.

**Current Naming Pattern - Hungarian Notation**

| Element Type | Naming Prefix | Example |
| :------------: | :-------------: | :------- |
| Parameters | `par` | `parLocation`, `parManagementGroupsNamePrefix` |
| Variables | `var` | `varConditionExpression`, `varIntermediateRootManagementGroupName` |
| Resources | `res` | `resIntermediateRootManagementGroup`, `resResourceGroupLogAnalytics` |
| Modules | `mod` | `modManagementGroups`, `modLogAnalytics` |
| Outputs | `out` | `outIntermediateRootManagementGroupID`, `outLogAnalyticsWorkspaceID` |

**Reasons why we did this**

1. Easier for those new to Infra-as-Code the understand where to find things and navigate the links/dependencies/references in the code base
2. Doesn't require any tooling or extensions to be installed to navigate code
    - Useful in things like Pull Request reviews where no IDE and tooling is generally used
3. Bicep language does not state we shouldn't use this pattern
4. Keeps it close to ARM where you would have the type defined in references like `"[parameter('region')]"`
5. Better than having no naming standard at all 😎

** **WE WANT YOU TO HELP US DECIDE THE FUTURE AND VOTE (SEE BELOW)** **

Whether you agree and like the use of Hungarian notation or not, we want you to vote on this form to let us know either way: https://forms.office.com/r/Ppu2z6kfvq

_(make sure you log your vote even if you are a fan and do like the use of Hungarian notation. As if we only get responses from users who don't like it or poll will be unfairly biased 😊)_

Also feel free to leave comments below if you want to 👍

**Comment by kilasuit** [comment]
I like this as can be easy to scan code to understand context as per [this issue](https://github.com/Azure/bicep/issues/1389) that I raised in Bicep (albeit with additonal `.`)
And like you say it's notsaid it shouldn't/can't be used in bicep code

**Comment by pazdedav** [comment]
Congrats with the first release 🍾, @jtracey93 and the team. I am planning to test it in my sandbox today ;)

I also voted in the poll. As this is a highly opinionated topic, I feel a lot of people will vote about the notation itself and not necessarily in the context of this project. But I guess this is expected ;)

**Comment by jtracey93** [comment]
Thanks to everyone who has voted, the results are in!

![image](https://user-images.githubusercontent.com/41163455/155953868-be8f8334-d36a-411e-a552-5e1cdea24b82.png)

With this data we will keep using Hungarian notation here for the foreseeable future 👍
