### ISSUE TITLE
Azure Policy Assignment - Configure Azure PaaS services to use private DNS zones

### ISSUE THREAD

**Issue by gerrynicol** [Azure/ALZ-Bicep#897]
### What happened? Provide a clear and concise description of the bug, including deployment details.

It looks like the Table Storage Private DNS Zone is missing from this policy. Is this still an issue as per the link below?

https://github.com/Azure/Enterprise-Scale/issues/1502

### Please provide the correlation id associated with your error or bug.

No error, missing DNS zone for table storage 

### What was the expected outcome?

Zone added

### Relevant log output

```Shell

```

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @gerrynicol, this looks to have been corrected in this PR [here ](https://github.com/Azure/ALZ-Bicep/pull/894 )from the upstream (Enterprise Scale) repo which was just merged.

If you're still having issues, please let us know.

**Comment by gerrynicol** [comment]
@oZakari I don't think this has been updated in the assignments, only the definition files, based on that link you provided, but I could be wrong

infra-as-code/bicep/modules/policy/definitions/lib/policy_set_definitions/policy_set_definition_es_Deploy-Private-DNS-Zones.json
infra-as-code/bicep/modules/policy/definitions/lib/policy_set_definitions/policy_set_definition_es_Deploy-Private-DNS-Zones.parameters.json

**Comment by oZakari** [comment]
Ah yes, I see what're you saying. Thanks for clarification and good catch! Looks like we missed that in the PR that fixed the definitions. Reopening this.
