### ISSUE TITLE
Question - Multi-region support future plans (if any)

### ISSUE THREAD

**Issue by cspring86** [Azure/ALZ-Bicep#909]
### Let us know the feedback or general question

We're currently using the Hub and Spoke network topology and we have a requirement to roll out (mutually independent) workloads across up to 6-8 regions.

I see that there has been some work done to support 2 regions, so we can currently deploy workloads in 2 regions as spokes to their respective hubs.

Are we expecting support for more than 2 regions in the future or can we use the current functionality to deploy across as many regions as we want?

For example, could we make 2-region deployments per region pair:
- eastus2 - centralus
- northeurope - westeurope
- etc

How would you advise we proceed if we had to implement this right now?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @cspring86, great question! Yes, this is something we are actively working on as part of the Azure Verified Modules (AVM) Refactor (#791). The goal is to enable the creation of multiple hub networks, each with its own peering settings.

We’re aiming to have this implemented in the early months of the new year. In the meantime, if you’d like to get started, you can use the same module we plan to leverage for this functionality: [Hub Networking Module](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/network/hub-networking).
