### ISSUE TITLE
Placeholder value in alzDefaultPolicyAssignments.parameters.min.json has been overwritten by a real guid.

### ISSUE THREAD

**Issue by brotheroneill** [Azure/ALZ-Bicep#920]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Hi Team, 

In the latest release (v0.20.1) it looks like a default value (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) in infra-as-code/bicep/modules/policy/assignments/alzDefaults/parameters/alzDefaultPolicyAssignments.parameters.min.json has been overwritten by a real guid. Assuming this wasn't intended? 

It looks like this is the only file, the full version still has the placeholder value.

### What was the expected outcome?

n/a

### Relevant log output

```Shell
n/a
```

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Thanks for the call out on this as it was unintended. Subscription is deleted as well.
